/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * AssociatedBudgetRuleResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class AssociatedBudgetRuleResponse {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nullable
  private String code;

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  @javax.annotation.Nullable
  private String details;

  public static final String SERIALIZED_NAME_RULE_ID = "ruleId";
  @SerializedName(SERIALIZED_NAME_RULE_ID)
  @javax.annotation.Nullable
  private String ruleId;

  public AssociatedBudgetRuleResponse() {
  }

  public AssociatedBudgetRuleResponse code(@javax.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * An enumerated success or error code for machine use.
   * @return code
   */
  @javax.annotation.Nullable

  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public AssociatedBudgetRuleResponse details(@javax.annotation.Nullable String details) {
    this.details = details;
    return this;
  }

  /**
   * A human-readable description of the error, if unsuccessful
   * @return details
   */
  @javax.annotation.Nullable

  public String getDetails() {
    return details;
  }

  public void setDetails(@javax.annotation.Nullable String details) {
    this.details = details;
  }


  public AssociatedBudgetRuleResponse ruleId(@javax.annotation.Nullable String ruleId) {
    this.ruleId = ruleId;
    return this;
  }

  /**
   * The budget rule identifier.
   * @return ruleId
   */
  @javax.annotation.Nullable

  public String getRuleId() {
    return ruleId;
  }

  public void setRuleId(@javax.annotation.Nullable String ruleId) {
    this.ruleId = ruleId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssociatedBudgetRuleResponse associatedBudgetRuleResponse = (AssociatedBudgetRuleResponse) o;
    return Objects.equals(this.code, associatedBudgetRuleResponse.code) &&
        Objects.equals(this.details, associatedBudgetRuleResponse.details) &&
        Objects.equals(this.ruleId, associatedBudgetRuleResponse.ruleId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, details, ruleId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssociatedBudgetRuleResponse {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    ruleId: ").append(toIndentedString(ruleId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("code");
    openapiFields.add("details");
    openapiFields.add("ruleId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AssociatedBudgetRuleResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AssociatedBudgetRuleResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AssociatedBudgetRuleResponse is not found in the empty JSON string", AssociatedBudgetRuleResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AssociatedBudgetRuleResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AssociatedBudgetRuleResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull()) && !jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      if ((jsonObj.get("details") != null && !jsonObj.get("details").isJsonNull()) && !jsonObj.get("details").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `details` to be a primitive type in the JSON string but got `%s`", jsonObj.get("details").toString()));
      }
      if ((jsonObj.get("ruleId") != null && !jsonObj.get("ruleId").isJsonNull()) && !jsonObj.get("ruleId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ruleId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ruleId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AssociatedBudgetRuleResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AssociatedBudgetRuleResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AssociatedBudgetRuleResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AssociatedBudgetRuleResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<AssociatedBudgetRuleResponse>() {
           @Override
           public void write(JsonWriter out, AssociatedBudgetRuleResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AssociatedBudgetRuleResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AssociatedBudgetRuleResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AssociatedBudgetRuleResponse
   * @throws IOException if the JSON string is invalid with respect to AssociatedBudgetRuleResponse
   */
  public static AssociatedBudgetRuleResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AssociatedBudgetRuleResponse.class);
  }

  /**
   * Convert an instance of AssociatedBudgetRuleResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

