/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.IOException;
import java.util.*;

/**
 * A list of multi country bid recommendation themes and associated bid recommendations.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class MultiCountryThemeBasedBidRecommendationResponse {
  public static final String SERIALIZED_NAME_BID_RECOMMENDATIONS = "bidRecommendations";
  @SerializedName(SERIALIZED_NAME_BID_RECOMMENDATIONS)
  @javax.annotation.Nonnull
  private List<@Valid MultiCountryThemeBasedBidRecommendation> bidRecommendations = new ArrayList<>();

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  @javax.annotation.Nullable
  private List<@Valid MultiCountryBidRecommendationError> errors = new ArrayList<>();

  public MultiCountryThemeBasedBidRecommendationResponse() {
  }

  public MultiCountryThemeBasedBidRecommendationResponse bidRecommendations(@javax.annotation.Nonnull List<@Valid MultiCountryThemeBasedBidRecommendation> bidRecommendations) {
    this.bidRecommendations = bidRecommendations;
    return this;
  }

  public MultiCountryThemeBasedBidRecommendationResponse addBidRecommendationsItem(MultiCountryThemeBasedBidRecommendation bidRecommendationsItem) {
    if (this.bidRecommendations == null) {
      this.bidRecommendations = new ArrayList<>();
    }
    this.bidRecommendations.add(bidRecommendationsItem);
    return this;
  }

  /**
   * Get bidRecommendations
   * @return bidRecommendations
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid
 @Size(min=0,max=2)
  public List<@Valid MultiCountryThemeBasedBidRecommendation> getBidRecommendations() {
    return bidRecommendations;
  }

  public void setBidRecommendations(@javax.annotation.Nonnull List<@Valid MultiCountryThemeBasedBidRecommendation> bidRecommendations) {
    this.bidRecommendations = bidRecommendations;
  }


  public MultiCountryThemeBasedBidRecommendationResponse errors(@javax.annotation.Nullable List<@Valid MultiCountryBidRecommendationError> errors) {
    this.errors = errors;
    return this;
  }

  public MultiCountryThemeBasedBidRecommendationResponse addErrorsItem(MultiCountryBidRecommendationError errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * List of errors occurred while processing multi country request.
   * @return errors
   */
  @javax.annotation.Nullable
  @Valid

  public List<@Valid MultiCountryBidRecommendationError> getErrors() {
    return errors;
  }

  public void setErrors(@javax.annotation.Nullable List<@Valid MultiCountryBidRecommendationError> errors) {
    this.errors = errors;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiCountryThemeBasedBidRecommendationResponse multiCountryThemeBasedBidRecommendationResponse = (MultiCountryThemeBasedBidRecommendationResponse) o;
    return Objects.equals(this.bidRecommendations, multiCountryThemeBasedBidRecommendationResponse.bidRecommendations) &&
        Objects.equals(this.errors, multiCountryThemeBasedBidRecommendationResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bidRecommendations, errors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiCountryThemeBasedBidRecommendationResponse {\n");
    sb.append("    bidRecommendations: ").append(toIndentedString(bidRecommendations)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bidRecommendations");
    openapiFields.add("errors");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("bidRecommendations");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MultiCountryThemeBasedBidRecommendationResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MultiCountryThemeBasedBidRecommendationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MultiCountryThemeBasedBidRecommendationResponse is not found in the empty JSON string", MultiCountryThemeBasedBidRecommendationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MultiCountryThemeBasedBidRecommendationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MultiCountryThemeBasedBidRecommendationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MultiCountryThemeBasedBidRecommendationResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("bidRecommendations").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `bidRecommendations` to be an array in the JSON string but got `%s`", jsonObj.get("bidRecommendations").toString()));
      }

      JsonArray jsonArraybidRecommendations = jsonObj.getAsJsonArray("bidRecommendations");
      // validate the required field `bidRecommendations` (array)
      for (int i = 0; i < jsonArraybidRecommendations.size(); i++) {
        MultiCountryThemeBasedBidRecommendation.validateJsonElement(jsonArraybidRecommendations.get(i));
      };
      if (jsonObj.get("errors") != null && !jsonObj.get("errors").isJsonNull()) {
        JsonArray jsonArrayerrors = jsonObj.getAsJsonArray("errors");
        if (jsonArrayerrors != null) {
          // ensure the json data is an array
          if (!jsonObj.get("errors").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `errors` to be an array in the JSON string but got `%s`", jsonObj.get("errors").toString()));
          }

          // validate the optional field `errors` (array)
          for (int i = 0; i < jsonArrayerrors.size(); i++) {
            MultiCountryBidRecommendationError.validateJsonElement(jsonArrayerrors.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MultiCountryThemeBasedBidRecommendationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MultiCountryThemeBasedBidRecommendationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MultiCountryThemeBasedBidRecommendationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MultiCountryThemeBasedBidRecommendationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<MultiCountryThemeBasedBidRecommendationResponse>() {
           @Override
           public void write(JsonWriter out, MultiCountryThemeBasedBidRecommendationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MultiCountryThemeBasedBidRecommendationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MultiCountryThemeBasedBidRecommendationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MultiCountryThemeBasedBidRecommendationResponse
   * @throws IOException if the JSON string is invalid with respect to MultiCountryThemeBasedBidRecommendationResponse
   */
  public static MultiCountryThemeBasedBidRecommendationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MultiCountryThemeBasedBidRecommendationResponse.class);
  }

  /**
   * Convert an instance of MultiCountryThemeBasedBidRecommendationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

