/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * OptimizationRulesAPISwaggerRuleConditionV2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class OptimizationRulesAPISwaggerRuleConditionV2 {
  public static final String SERIALIZED_NAME_ATTRIBUTE_NAME = "attributeName";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_NAME)
  @javax.annotation.Nullable
  private OptimizationRulesAPISwaggerRuleAttributeV2 attributeName;

  public static final String SERIALIZED_NAME_CRITERIA = "criteria";
  @SerializedName(SERIALIZED_NAME_CRITERIA)
  @javax.annotation.Nullable
  private OptimizationRulesAPISwaggerRuleCriteria criteria;

  public OptimizationRulesAPISwaggerRuleConditionV2() {
  }

  public OptimizationRulesAPISwaggerRuleConditionV2 attributeName(@javax.annotation.Nullable OptimizationRulesAPISwaggerRuleAttributeV2 attributeName) {
    this.attributeName = attributeName;
    return this;
  }

  /**
   * Get attributeName
   * @return attributeName
   */
  @javax.annotation.Nullable
  @Valid

  public OptimizationRulesAPISwaggerRuleAttributeV2 getAttributeName() {
    return attributeName;
  }

  public void setAttributeName(@javax.annotation.Nullable OptimizationRulesAPISwaggerRuleAttributeV2 attributeName) {
    this.attributeName = attributeName;
  }


  public OptimizationRulesAPISwaggerRuleConditionV2 criteria(@javax.annotation.Nullable OptimizationRulesAPISwaggerRuleCriteria criteria) {
    this.criteria = criteria;
    return this;
  }

  /**
   * Get criteria
   * @return criteria
   */
  @javax.annotation.Nullable
  @Valid

  public OptimizationRulesAPISwaggerRuleCriteria getCriteria() {
    return criteria;
  }

  public void setCriteria(@javax.annotation.Nullable OptimizationRulesAPISwaggerRuleCriteria criteria) {
    this.criteria = criteria;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OptimizationRulesAPISwaggerRuleConditionV2 optimizationRulesAPISwaggerRuleConditionV2 = (OptimizationRulesAPISwaggerRuleConditionV2) o;
    return Objects.equals(this.attributeName, optimizationRulesAPISwaggerRuleConditionV2.attributeName) &&
        Objects.equals(this.criteria, optimizationRulesAPISwaggerRuleConditionV2.criteria);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeName, criteria);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OptimizationRulesAPISwaggerRuleConditionV2 {\n");
    sb.append("    attributeName: ").append(toIndentedString(attributeName)).append("\n");
    sb.append("    criteria: ").append(toIndentedString(criteria)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attributeName");
    openapiFields.add("criteria");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OptimizationRulesAPISwaggerRuleConditionV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OptimizationRulesAPISwaggerRuleConditionV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OptimizationRulesAPISwaggerRuleConditionV2 is not found in the empty JSON string", OptimizationRulesAPISwaggerRuleConditionV2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OptimizationRulesAPISwaggerRuleConditionV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OptimizationRulesAPISwaggerRuleConditionV2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `attributeName`
      if (jsonObj.get("attributeName") != null && !jsonObj.get("attributeName").isJsonNull()) {
        OptimizationRulesAPISwaggerRuleAttributeV2.validateJsonElement(jsonObj.get("attributeName"));
      }
      // validate the optional field `criteria`
      if (jsonObj.get("criteria") != null && !jsonObj.get("criteria").isJsonNull()) {
        OptimizationRulesAPISwaggerRuleCriteria.validateJsonElement(jsonObj.get("criteria"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OptimizationRulesAPISwaggerRuleConditionV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OptimizationRulesAPISwaggerRuleConditionV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OptimizationRulesAPISwaggerRuleConditionV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OptimizationRulesAPISwaggerRuleConditionV2.class));

       return (TypeAdapter<T>) new TypeAdapter<OptimizationRulesAPISwaggerRuleConditionV2>() {
           @Override
           public void write(JsonWriter out, OptimizationRulesAPISwaggerRuleConditionV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OptimizationRulesAPISwaggerRuleConditionV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OptimizationRulesAPISwaggerRuleConditionV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OptimizationRulesAPISwaggerRuleConditionV2
   * @throws IOException if the JSON string is invalid with respect to OptimizationRulesAPISwaggerRuleConditionV2
   */
  public static OptimizationRulesAPISwaggerRuleConditionV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OptimizationRulesAPISwaggerRuleConditionV2.class);
  }

  /**
   * Convert an instance of OptimizationRulesAPISwaggerRuleConditionV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

