/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Filter on optimization rules.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class OptimizationRulesAPISwaggerOptimizationRuleFilter {
  public static final String SERIALIZED_NAME_OPTIMIZATION_RULE_ID = "optimizationRuleId";
  @SerializedName(SERIALIZED_NAME_OPTIMIZATION_RULE_ID)
  @javax.annotation.Nullable
  private OptimizationRulesAPISwaggerEntityFieldFilter optimizationRuleId;

  public static final String SERIALIZED_NAME_RULE_CATEGORY = "ruleCategory";
  @SerializedName(SERIALIZED_NAME_RULE_CATEGORY)
  @javax.annotation.Nullable
  private OptimizationRulesAPISwaggerEntityFieldFilter ruleCategory;

  public static final String SERIALIZED_NAME_RULE_SUB_CATEGORY = "ruleSubCategory";
  @SerializedName(SERIALIZED_NAME_RULE_SUB_CATEGORY)
  @javax.annotation.Nullable
  private OptimizationRulesAPISwaggerEntityFieldFilter ruleSubCategory;

  public OptimizationRulesAPISwaggerOptimizationRuleFilter() {
  }

  public OptimizationRulesAPISwaggerOptimizationRuleFilter optimizationRuleId(@javax.annotation.Nullable OptimizationRulesAPISwaggerEntityFieldFilter optimizationRuleId) {
    this.optimizationRuleId = optimizationRuleId;
    return this;
  }

  /**
   * Get optimizationRuleId
   * @return optimizationRuleId
   */
  @javax.annotation.Nullable
  @Valid

  public OptimizationRulesAPISwaggerEntityFieldFilter getOptimizationRuleId() {
    return optimizationRuleId;
  }

  public void setOptimizationRuleId(@javax.annotation.Nullable OptimizationRulesAPISwaggerEntityFieldFilter optimizationRuleId) {
    this.optimizationRuleId = optimizationRuleId;
  }


  public OptimizationRulesAPISwaggerOptimizationRuleFilter ruleCategory(@javax.annotation.Nullable OptimizationRulesAPISwaggerEntityFieldFilter ruleCategory) {
    this.ruleCategory = ruleCategory;
    return this;
  }

  /**
   * Get ruleCategory
   * @return ruleCategory
   */
  @javax.annotation.Nullable
  @Valid

  public OptimizationRulesAPISwaggerEntityFieldFilter getRuleCategory() {
    return ruleCategory;
  }

  public void setRuleCategory(@javax.annotation.Nullable OptimizationRulesAPISwaggerEntityFieldFilter ruleCategory) {
    this.ruleCategory = ruleCategory;
  }


  public OptimizationRulesAPISwaggerOptimizationRuleFilter ruleSubCategory(@javax.annotation.Nullable OptimizationRulesAPISwaggerEntityFieldFilter ruleSubCategory) {
    this.ruleSubCategory = ruleSubCategory;
    return this;
  }

  /**
   * Get ruleSubCategory
   * @return ruleSubCategory
   */
  @javax.annotation.Nullable
  @Valid

  public OptimizationRulesAPISwaggerEntityFieldFilter getRuleSubCategory() {
    return ruleSubCategory;
  }

  public void setRuleSubCategory(@javax.annotation.Nullable OptimizationRulesAPISwaggerEntityFieldFilter ruleSubCategory) {
    this.ruleSubCategory = ruleSubCategory;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OptimizationRulesAPISwaggerOptimizationRuleFilter optimizationRulesAPISwaggerOptimizationRuleFilter = (OptimizationRulesAPISwaggerOptimizationRuleFilter) o;
    return Objects.equals(this.optimizationRuleId, optimizationRulesAPISwaggerOptimizationRuleFilter.optimizationRuleId) &&
        Objects.equals(this.ruleCategory, optimizationRulesAPISwaggerOptimizationRuleFilter.ruleCategory) &&
        Objects.equals(this.ruleSubCategory, optimizationRulesAPISwaggerOptimizationRuleFilter.ruleSubCategory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(optimizationRuleId, ruleCategory, ruleSubCategory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OptimizationRulesAPISwaggerOptimizationRuleFilter {\n");
    sb.append("    optimizationRuleId: ").append(toIndentedString(optimizationRuleId)).append("\n");
    sb.append("    ruleCategory: ").append(toIndentedString(ruleCategory)).append("\n");
    sb.append("    ruleSubCategory: ").append(toIndentedString(ruleSubCategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("optimizationRuleId");
    openapiFields.add("ruleCategory");
    openapiFields.add("ruleSubCategory");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OptimizationRulesAPISwaggerOptimizationRuleFilter
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OptimizationRulesAPISwaggerOptimizationRuleFilter.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OptimizationRulesAPISwaggerOptimizationRuleFilter is not found in the empty JSON string", OptimizationRulesAPISwaggerOptimizationRuleFilter.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OptimizationRulesAPISwaggerOptimizationRuleFilter.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OptimizationRulesAPISwaggerOptimizationRuleFilter` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `optimizationRuleId`
      if (jsonObj.get("optimizationRuleId") != null && !jsonObj.get("optimizationRuleId").isJsonNull()) {
        OptimizationRulesAPISwaggerEntityFieldFilter.validateJsonElement(jsonObj.get("optimizationRuleId"));
      }
      // validate the optional field `ruleCategory`
      if (jsonObj.get("ruleCategory") != null && !jsonObj.get("ruleCategory").isJsonNull()) {
        OptimizationRulesAPISwaggerEntityFieldFilter.validateJsonElement(jsonObj.get("ruleCategory"));
      }
      // validate the optional field `ruleSubCategory`
      if (jsonObj.get("ruleSubCategory") != null && !jsonObj.get("ruleSubCategory").isJsonNull()) {
        OptimizationRulesAPISwaggerEntityFieldFilter.validateJsonElement(jsonObj.get("ruleSubCategory"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OptimizationRulesAPISwaggerOptimizationRuleFilter.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OptimizationRulesAPISwaggerOptimizationRuleFilter' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OptimizationRulesAPISwaggerOptimizationRuleFilter> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OptimizationRulesAPISwaggerOptimizationRuleFilter.class));

       return (TypeAdapter<T>) new TypeAdapter<OptimizationRulesAPISwaggerOptimizationRuleFilter>() {
           @Override
           public void write(JsonWriter out, OptimizationRulesAPISwaggerOptimizationRuleFilter value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OptimizationRulesAPISwaggerOptimizationRuleFilter read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OptimizationRulesAPISwaggerOptimizationRuleFilter given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OptimizationRulesAPISwaggerOptimizationRuleFilter
   * @throws IOException if the JSON string is invalid with respect to OptimizationRulesAPISwaggerOptimizationRuleFilter
   */
  public static OptimizationRulesAPISwaggerOptimizationRuleFilter fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OptimizationRulesAPISwaggerOptimizationRuleFilter.class);
  }

  /**
   * Convert an instance of OptimizationRulesAPISwaggerOptimizationRuleFilter to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

