/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import javax.validation.constraints.Size;
import java.io.IOException;
import java.util.*;

/**
 * Recurrence
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class Recurrence {
  public static final String SERIALIZED_NAME_DAYS_OF_WEEK = "daysOfWeek";
  @SerializedName(SERIALIZED_NAME_DAYS_OF_WEEK)
  @javax.annotation.Nullable
  private List<DayOfWeek> daysOfWeek = new ArrayList<>();

  public static final String SERIALIZED_NAME_INTRA_DAY_SCHEDULE = "intraDaySchedule";
  @SerializedName(SERIALIZED_NAME_INTRA_DAY_SCHEDULE)
  @javax.annotation.Nullable
  private List<@Valid TimeOfDay> intraDaySchedule = new ArrayList<>();

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private RecurrenceType type;

  public Recurrence() {
  }

  public Recurrence daysOfWeek(@javax.annotation.Nullable List<DayOfWeek> daysOfWeek) {
    this.daysOfWeek = daysOfWeek;
    return this;
  }

  public Recurrence addDaysOfWeekItem(DayOfWeek daysOfWeekItem) {
    if (this.daysOfWeek == null) {
      this.daysOfWeek = new ArrayList<>();
    }
    this.daysOfWeek.add(daysOfWeekItem);
    return this;
  }

  /**
   * Object representing days of the week for weekly type rule. It is not required for daily recurrence type
   * @return daysOfWeek
   */
  @javax.annotation.Nullable
  @Valid

  public List<DayOfWeek> getDaysOfWeek() {
    return daysOfWeek;
  }

  public void setDaysOfWeek(@javax.annotation.Nullable List<DayOfWeek> daysOfWeek) {
    this.daysOfWeek = daysOfWeek;
  }


  public Recurrence intraDaySchedule(@javax.annotation.Nullable List<@Valid TimeOfDay> intraDaySchedule) {
    this.intraDaySchedule = intraDaySchedule;
    return this;
  }

  public Recurrence addIntraDayScheduleItem(TimeOfDay intraDayScheduleItem) {
    if (this.intraDaySchedule == null) {
      this.intraDaySchedule = new ArrayList<>();
    }
    this.intraDaySchedule.add(intraDayScheduleItem);
    return this;
  }

  /**
   * List of objects representing start and end time of desired intra-day budget rule window
   * @return intraDaySchedule
   */
  @javax.annotation.Nullable
  @Valid
 @Size(max=1)
  public List<@Valid TimeOfDay> getIntraDaySchedule() {
    return intraDaySchedule;
  }

  public void setIntraDaySchedule(@javax.annotation.Nullable List<@Valid TimeOfDay> intraDaySchedule) {
    this.intraDaySchedule = intraDaySchedule;
  }


  public Recurrence type(@javax.annotation.Nullable RecurrenceType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @Valid

  public RecurrenceType getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable RecurrenceType type) {
    this.type = type;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recurrence recurrence = (Recurrence) o;
    return Objects.equals(this.daysOfWeek, recurrence.daysOfWeek) &&
        Objects.equals(this.intraDaySchedule, recurrence.intraDaySchedule) &&
        Objects.equals(this.type, recurrence.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daysOfWeek, intraDaySchedule, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recurrence {\n");
    sb.append("    daysOfWeek: ").append(toIndentedString(daysOfWeek)).append("\n");
    sb.append("    intraDaySchedule: ").append(toIndentedString(intraDaySchedule)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("daysOfWeek");
    openapiFields.add("intraDaySchedule");
    openapiFields.add("type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Recurrence
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Recurrence.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Recurrence is not found in the empty JSON string", Recurrence.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Recurrence.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Recurrence` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("daysOfWeek") != null && !jsonObj.get("daysOfWeek").isJsonNull() && !jsonObj.get("daysOfWeek").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `daysOfWeek` to be an array in the JSON string but got `%s`", jsonObj.get("daysOfWeek").toString()));
      }
      if (jsonObj.get("intraDaySchedule") != null && !jsonObj.get("intraDaySchedule").isJsonNull()) {
        JsonArray jsonArrayintraDaySchedule = jsonObj.getAsJsonArray("intraDaySchedule");
        if (jsonArrayintraDaySchedule != null) {
          // ensure the json data is an array
          if (!jsonObj.get("intraDaySchedule").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `intraDaySchedule` to be an array in the JSON string but got `%s`", jsonObj.get("intraDaySchedule").toString()));
          }

          // validate the optional field `intraDaySchedule` (array)
          for (int i = 0; i < jsonArrayintraDaySchedule.size(); i++) {
            TimeOfDay.validateJsonElement(jsonArrayintraDaySchedule.get(i));
          };
        }
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        RecurrenceType.validateJsonElement(jsonObj.get("type"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Recurrence.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Recurrence' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Recurrence> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Recurrence.class));

       return (TypeAdapter<T>) new TypeAdapter<Recurrence>() {
           @Override
           public void write(JsonWriter out, Recurrence value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Recurrence read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Recurrence given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Recurrence
   * @throws IOException if the JSON string is invalid with respect to Recurrence
   */
  public static Recurrence fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Recurrence.class);
  }

  /**
   * Convert an instance of Recurrence to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

