/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * The advertising performance metric. ROAS is the only supported metric.
 */
@JsonAdapter(RuleConditionMetric.Adapter.class)
public enum RuleConditionMetric {
  
  AVERAGE_BID("AVERAGE_BID"),
  
  ROAS("ROAS");

  private String value;

  RuleConditionMetric(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RuleConditionMetric fromValue(String value) {
    for (RuleConditionMetric b : RuleConditionMetric.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RuleConditionMetric> {
    @Override
    public void write(final JsonWriter jsonWriter, final RuleConditionMetric enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RuleConditionMetric read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RuleConditionMetric.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    RuleConditionMetric.fromValue(value);
  }
}

