/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * SponsoredProductsEntityNotFoundError
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class SponsoredProductsEntityNotFoundError {
  public static final String SERIALIZED_NAME_CAUSE = "cause";
  @SerializedName(SERIALIZED_NAME_CAUSE)
  @javax.annotation.Nullable
  private SponsoredProductsErrorCause cause;

  public static final String SERIALIZED_NAME_ENTITY_ID = "entityId";
  @SerializedName(SERIALIZED_NAME_ENTITY_ID)
  @javax.annotation.Nonnull
  private String entityId;

  public static final String SERIALIZED_NAME_ENTITY_TYPE = "entityType";
  @SerializedName(SERIALIZED_NAME_ENTITY_TYPE)
  @javax.annotation.Nonnull
  private SponsoredProductsEntityType entityType;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nonnull
  private String message;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  @javax.annotation.Nonnull
  private SponsoredProductsEntityNotFoundErrorReason reason;

  public SponsoredProductsEntityNotFoundError() {
  }

  public SponsoredProductsEntityNotFoundError cause(@javax.annotation.Nullable SponsoredProductsErrorCause cause) {
    this.cause = cause;
    return this;
  }

  /**
   * Get cause
   * @return cause
   */
  @javax.annotation.Nullable
  @Valid

  public SponsoredProductsErrorCause getCause() {
    return cause;
  }

  public void setCause(@javax.annotation.Nullable SponsoredProductsErrorCause cause) {
    this.cause = cause;
  }


  public SponsoredProductsEntityNotFoundError entityId(@javax.annotation.Nonnull String entityId) {
    this.entityId = entityId;
    return this;
  }

  /**
   * The entity id in the request
   * @return entityId
   */
  @javax.annotation.Nonnull
  @NotNull

  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(@javax.annotation.Nonnull String entityId) {
    this.entityId = entityId;
  }


  public SponsoredProductsEntityNotFoundError entityType(@javax.annotation.Nonnull SponsoredProductsEntityType entityType) {
    this.entityType = entityType;
    return this;
  }

  /**
   * Get entityType
   * @return entityType
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  public SponsoredProductsEntityType getEntityType() {
    return entityType;
  }

  public void setEntityType(@javax.annotation.Nonnull SponsoredProductsEntityType entityType) {
    this.entityType = entityType;
  }


  public SponsoredProductsEntityNotFoundError message(@javax.annotation.Nonnull String message) {
    this.message = message;
    return this;
  }

  /**
   * Human readable error message
   * @return message
   */
  @javax.annotation.Nonnull
  @NotNull

  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nonnull String message) {
    this.message = message;
  }


  public SponsoredProductsEntityNotFoundError reason(@javax.annotation.Nonnull SponsoredProductsEntityNotFoundErrorReason reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  public SponsoredProductsEntityNotFoundErrorReason getReason() {
    return reason;
  }

  public void setReason(@javax.annotation.Nonnull SponsoredProductsEntityNotFoundErrorReason reason) {
    this.reason = reason;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SponsoredProductsEntityNotFoundError sponsoredProductsEntityNotFoundError = (SponsoredProductsEntityNotFoundError) o;
    return Objects.equals(this.cause, sponsoredProductsEntityNotFoundError.cause) &&
        Objects.equals(this.entityId, sponsoredProductsEntityNotFoundError.entityId) &&
        Objects.equals(this.entityType, sponsoredProductsEntityNotFoundError.entityType) &&
        Objects.equals(this.message, sponsoredProductsEntityNotFoundError.message) &&
        Objects.equals(this.reason, sponsoredProductsEntityNotFoundError.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cause, entityId, entityType, message, reason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SponsoredProductsEntityNotFoundError {\n");
    sb.append("    cause: ").append(toIndentedString(cause)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cause");
    openapiFields.add("entityId");
    openapiFields.add("entityType");
    openapiFields.add("message");
    openapiFields.add("reason");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("entityId");
    openapiRequiredFields.add("entityType");
    openapiRequiredFields.add("message");
    openapiRequiredFields.add("reason");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SponsoredProductsEntityNotFoundError
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SponsoredProductsEntityNotFoundError.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SponsoredProductsEntityNotFoundError is not found in the empty JSON string", SponsoredProductsEntityNotFoundError.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SponsoredProductsEntityNotFoundError.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SponsoredProductsEntityNotFoundError` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SponsoredProductsEntityNotFoundError.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `cause`
      if (jsonObj.get("cause") != null && !jsonObj.get("cause").isJsonNull()) {
        SponsoredProductsErrorCause.validateJsonElement(jsonObj.get("cause"));
      }
      if (!jsonObj.get("entityId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `entityId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("entityId").toString()));
      }
      // validate the required field `entityType`
      SponsoredProductsEntityType.validateJsonElement(jsonObj.get("entityType"));
      if (!jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      // validate the required field `reason`
      SponsoredProductsEntityNotFoundErrorReason.validateJsonElement(jsonObj.get("reason"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SponsoredProductsEntityNotFoundError.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SponsoredProductsEntityNotFoundError' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SponsoredProductsEntityNotFoundError> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SponsoredProductsEntityNotFoundError.class));

       return (TypeAdapter<T>) new TypeAdapter<SponsoredProductsEntityNotFoundError>() {
           @Override
           public void write(JsonWriter out, SponsoredProductsEntityNotFoundError value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SponsoredProductsEntityNotFoundError read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SponsoredProductsEntityNotFoundError given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SponsoredProductsEntityNotFoundError
   * @throws IOException if the JSON string is invalid with respect to SponsoredProductsEntityNotFoundError
   */
  public static SponsoredProductsEntityNotFoundError fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SponsoredProductsEntityNotFoundError.class);
  }

  /**
   * Convert an instance of SponsoredProductsEntityNotFoundError to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

