/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * The budget control strategy for ads served off Amazon . &#x60;OffAmazonBudgetControlStrategy&#x60; is optional for create and update requests. Value |  Description | |-----------|------------| | &#x60;MAXIMIZE_REACH&#x60; | Prioritize more reach using your target settings. This setting may result in more impressions and opportunities for sales off Amazon. | | &#x60;MINIMIZE_SPEND&#x60; | Optimize ad delivery to minimize spending. This setting may result in fewer impressions off Amazon, but it can help control spend. |
 */
@JsonAdapter(SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy.Adapter.class)
public enum SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy {
  
  MAXIMIZE_REACH("MAXIMIZE_REACH"),
  
  MINIMIZE_SPEND("MINIMIZE_SPEND");

  private String value;

  SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy fromValue(String value) {
    for (SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy b : SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy> {
    @Override
    public void write(final JsonWriter jsonWriter, final SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    SponsoredProductsCreateOrUpdateOffAmazonBudgetControlStrategy.fromValue(value);
  }
}

