/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * SponsoredProductsTargetingClauseSuccessResponseItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class SponsoredProductsTargetingClauseSuccessResponseItem {
  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  @javax.annotation.Nonnull
  private Integer index;

  public static final String SERIALIZED_NAME_TARGET_ID = "targetId";
  @SerializedName(SERIALIZED_NAME_TARGET_ID)
  @javax.annotation.Nullable
  private String targetId;

  public static final String SERIALIZED_NAME_TARGETING_CLAUSE = "targetingClause";
  @SerializedName(SERIALIZED_NAME_TARGETING_CLAUSE)
  @javax.annotation.Nullable
  private SponsoredProductsTargetingClause targetingClause;

  public SponsoredProductsTargetingClauseSuccessResponseItem() {
  }

  public SponsoredProductsTargetingClauseSuccessResponseItem index(@javax.annotation.Nonnull Integer index) {
    this.index = index;
    return this;
  }

  /**
   * the index of the targetingClause in the array from the request body
   * minimum: 0
   * @return index
   */
  @javax.annotation.Nonnull
  @NotNull
 @Min(0)
  public Integer getIndex() {
    return index;
  }

  public void setIndex(@javax.annotation.Nonnull Integer index) {
    this.index = index;
  }


  public SponsoredProductsTargetingClauseSuccessResponseItem targetId(@javax.annotation.Nullable String targetId) {
    this.targetId = targetId;
    return this;
  }

  /**
   * the targetingClause ID
   * @return targetId
   */
  @javax.annotation.Nullable

  public String getTargetId() {
    return targetId;
  }

  public void setTargetId(@javax.annotation.Nullable String targetId) {
    this.targetId = targetId;
  }


  public SponsoredProductsTargetingClauseSuccessResponseItem targetingClause(@javax.annotation.Nullable SponsoredProductsTargetingClause targetingClause) {
    this.targetingClause = targetingClause;
    return this;
  }

  /**
   * Get targetingClause
   * @return targetingClause
   */
  @javax.annotation.Nullable
  @Valid

  public SponsoredProductsTargetingClause getTargetingClause() {
    return targetingClause;
  }

  public void setTargetingClause(@javax.annotation.Nullable SponsoredProductsTargetingClause targetingClause) {
    this.targetingClause = targetingClause;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SponsoredProductsTargetingClauseSuccessResponseItem sponsoredProductsTargetingClauseSuccessResponseItem = (SponsoredProductsTargetingClauseSuccessResponseItem) o;
    return Objects.equals(this.index, sponsoredProductsTargetingClauseSuccessResponseItem.index) &&
        Objects.equals(this.targetId, sponsoredProductsTargetingClauseSuccessResponseItem.targetId) &&
        Objects.equals(this.targetingClause, sponsoredProductsTargetingClauseSuccessResponseItem.targetingClause);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, targetId, targetingClause);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SponsoredProductsTargetingClauseSuccessResponseItem {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
    sb.append("    targetingClause: ").append(toIndentedString(targetingClause)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("index");
    openapiFields.add("targetId");
    openapiFields.add("targetingClause");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("index");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SponsoredProductsTargetingClauseSuccessResponseItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SponsoredProductsTargetingClauseSuccessResponseItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SponsoredProductsTargetingClauseSuccessResponseItem is not found in the empty JSON string", SponsoredProductsTargetingClauseSuccessResponseItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SponsoredProductsTargetingClauseSuccessResponseItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SponsoredProductsTargetingClauseSuccessResponseItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SponsoredProductsTargetingClauseSuccessResponseItem.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("targetId") != null && !jsonObj.get("targetId").isJsonNull()) && !jsonObj.get("targetId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetId").toString()));
      }
      // validate the optional field `targetingClause`
      if (jsonObj.get("targetingClause") != null && !jsonObj.get("targetingClause").isJsonNull()) {
        SponsoredProductsTargetingClause.validateJsonElement(jsonObj.get("targetingClause"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SponsoredProductsTargetingClauseSuccessResponseItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SponsoredProductsTargetingClauseSuccessResponseItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SponsoredProductsTargetingClauseSuccessResponseItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SponsoredProductsTargetingClauseSuccessResponseItem.class));

       return (TypeAdapter<T>) new TypeAdapter<SponsoredProductsTargetingClauseSuccessResponseItem>() {
           @Override
           public void write(JsonWriter out, SponsoredProductsTargetingClauseSuccessResponseItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SponsoredProductsTargetingClauseSuccessResponseItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SponsoredProductsTargetingClauseSuccessResponseItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SponsoredProductsTargetingClauseSuccessResponseItem
   * @throws IOException if the JSON string is invalid with respect to SponsoredProductsTargetingClauseSuccessResponseItem
   */
  public static SponsoredProductsTargetingClauseSuccessResponseItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SponsoredProductsTargetingClauseSuccessResponseItem.class);
  }

  /**
   * Convert an instance of SponsoredProductsTargetingClauseSuccessResponseItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

