/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * SponsoredProductsProductAd
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class SponsoredProductsProductAd {
  public static final String SERIALIZED_NAME_AD_GROUP_ID = "adGroupId";
  @SerializedName(SERIALIZED_NAME_AD_GROUP_ID)
  @javax.annotation.Nonnull
  private String adGroupId;

  public static final String SERIALIZED_NAME_AD_ID = "adId";
  @SerializedName(SERIALIZED_NAME_AD_ID)
  @javax.annotation.Nonnull
  private String adId;

  public static final String SERIALIZED_NAME_ASIN = "asin";
  @SerializedName(SERIALIZED_NAME_ASIN)
  @javax.annotation.Nullable
  private String asin;

  public static final String SERIALIZED_NAME_CAMPAIGN_ID = "campaignId";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_ID)
  @javax.annotation.Nonnull
  private String campaignId;

  public static final String SERIALIZED_NAME_CUSTOM_TEXT = "customText";
  @SerializedName(SERIALIZED_NAME_CUSTOM_TEXT)
  @javax.annotation.Nullable
  private String customText;

  public static final String SERIALIZED_NAME_EXTENDED_DATA = "extendedData";
  @SerializedName(SERIALIZED_NAME_EXTENDED_DATA)
  @javax.annotation.Nullable
  private SponsoredProductsProductAdExtendedData extendedData;

  public static final String SERIALIZED_NAME_GLOBAL_AD_ID = "globalAdId";
  @SerializedName(SERIALIZED_NAME_GLOBAL_AD_ID)
  @javax.annotation.Nullable
  private String globalAdId;

  public static final String SERIALIZED_NAME_GLOBAL_STORE_SETTING = "globalStoreSetting";
  @SerializedName(SERIALIZED_NAME_GLOBAL_STORE_SETTING)
  @javax.annotation.Nullable
  private SponsoredProductsGlobalStoreSetting globalStoreSetting;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  @javax.annotation.Nullable
  private String sku;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nonnull
  private SponsoredProductsEntityState state;

  public SponsoredProductsProductAd() {
  }

  public SponsoredProductsProductAd adGroupId(@javax.annotation.Nonnull String adGroupId) {
    this.adGroupId = adGroupId;
    return this;
  }

  /**
   * The ad group identifier.
   * @return adGroupId
   */
  @javax.annotation.Nonnull
  @NotNull

  public String getAdGroupId() {
    return adGroupId;
  }

  public void setAdGroupId(@javax.annotation.Nonnull String adGroupId) {
    this.adGroupId = adGroupId;
  }


  public SponsoredProductsProductAd adId(@javax.annotation.Nonnull String adId) {
    this.adId = adId;
    return this;
  }

  /**
   * The product ad identifier.
   * @return adId
   */
  @javax.annotation.Nonnull
  @NotNull

  public String getAdId() {
    return adId;
  }

  public void setAdId(@javax.annotation.Nonnull String adId) {
    this.adId = adId;
  }


  public SponsoredProductsProductAd asin(@javax.annotation.Nullable String asin) {
    this.asin = asin;
    return this;
  }

  /**
   * The ASIN associated with the product. Defined for vendors only.
   * @return asin
   */
  @javax.annotation.Nullable

  public String getAsin() {
    return asin;
  }

  public void setAsin(@javax.annotation.Nullable String asin) {
    this.asin = asin;
  }


  public SponsoredProductsProductAd campaignId(@javax.annotation.Nonnull String campaignId) {
    this.campaignId = campaignId;
    return this;
  }

  /**
   * The campaign identifier.
   * @return campaignId
   */
  @javax.annotation.Nonnull
  @NotNull

  public String getCampaignId() {
    return campaignId;
  }

  public void setCampaignId(@javax.annotation.Nonnull String campaignId) {
    this.campaignId = campaignId;
  }


  public SponsoredProductsProductAd customText(@javax.annotation.Nullable String customText) {
    this.customText = customText;
    return this;
  }

  /**
   * The custom text that is associated with this ad. Defined for custom text ads only.
   * @return customText
   */
  @javax.annotation.Nullable

  public String getCustomText() {
    return customText;
  }

  public void setCustomText(@javax.annotation.Nullable String customText) {
    this.customText = customText;
  }


  public SponsoredProductsProductAd extendedData(@javax.annotation.Nullable SponsoredProductsProductAdExtendedData extendedData) {
    this.extendedData = extendedData;
    return this;
  }

  /**
   * Get extendedData
   * @return extendedData
   */
  @javax.annotation.Nullable
  @Valid

  public SponsoredProductsProductAdExtendedData getExtendedData() {
    return extendedData;
  }

  public void setExtendedData(@javax.annotation.Nullable SponsoredProductsProductAdExtendedData extendedData) {
    this.extendedData = extendedData;
  }


  public SponsoredProductsProductAd globalAdId(@javax.annotation.Nullable String globalAdId) {
    this.globalAdId = globalAdId;
    return this;
  }

  /**
   * The global ad identifier that manages this marketplace ad.
   * @return globalAdId
   */
  @javax.annotation.Nullable

  public String getGlobalAdId() {
    return globalAdId;
  }

  public void setGlobalAdId(@javax.annotation.Nullable String globalAdId) {
    this.globalAdId = globalAdId;
  }


  public SponsoredProductsProductAd globalStoreSetting(@javax.annotation.Nullable SponsoredProductsGlobalStoreSetting globalStoreSetting) {
    this.globalStoreSetting = globalStoreSetting;
    return this;
  }

  /**
   * Get globalStoreSetting
   * @return globalStoreSetting
   */
  @javax.annotation.Nullable
  @Valid

  public SponsoredProductsGlobalStoreSetting getGlobalStoreSetting() {
    return globalStoreSetting;
  }

  public void setGlobalStoreSetting(@javax.annotation.Nullable SponsoredProductsGlobalStoreSetting globalStoreSetting) {
    this.globalStoreSetting = globalStoreSetting;
  }


  public SponsoredProductsProductAd sku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
    return this;
  }

  /**
   * The SKU associated with the product. Defined for seller accounts only.
   * @return sku
   */
  @javax.annotation.Nullable

  public String getSku() {
    return sku;
  }

  public void setSku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
  }


  public SponsoredProductsProductAd state(@javax.annotation.Nonnull SponsoredProductsEntityState state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  public SponsoredProductsEntityState getState() {
    return state;
  }

  public void setState(@javax.annotation.Nonnull SponsoredProductsEntityState state) {
    this.state = state;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SponsoredProductsProductAd sponsoredProductsProductAd = (SponsoredProductsProductAd) o;
    return Objects.equals(this.adGroupId, sponsoredProductsProductAd.adGroupId) &&
        Objects.equals(this.adId, sponsoredProductsProductAd.adId) &&
        Objects.equals(this.asin, sponsoredProductsProductAd.asin) &&
        Objects.equals(this.campaignId, sponsoredProductsProductAd.campaignId) &&
        Objects.equals(this.customText, sponsoredProductsProductAd.customText) &&
        Objects.equals(this.extendedData, sponsoredProductsProductAd.extendedData) &&
        Objects.equals(this.globalAdId, sponsoredProductsProductAd.globalAdId) &&
        Objects.equals(this.globalStoreSetting, sponsoredProductsProductAd.globalStoreSetting) &&
        Objects.equals(this.sku, sponsoredProductsProductAd.sku) &&
        Objects.equals(this.state, sponsoredProductsProductAd.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adGroupId, adId, asin, campaignId, customText, extendedData, globalAdId, globalStoreSetting, sku, state);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SponsoredProductsProductAd {\n");
    sb.append("    adGroupId: ").append(toIndentedString(adGroupId)).append("\n");
    sb.append("    adId: ").append(toIndentedString(adId)).append("\n");
    sb.append("    asin: ").append(toIndentedString(asin)).append("\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    customText: ").append(toIndentedString(customText)).append("\n");
    sb.append("    extendedData: ").append(toIndentedString(extendedData)).append("\n");
    sb.append("    globalAdId: ").append(toIndentedString(globalAdId)).append("\n");
    sb.append("    globalStoreSetting: ").append(toIndentedString(globalStoreSetting)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("adGroupId");
    openapiFields.add("adId");
    openapiFields.add("asin");
    openapiFields.add("campaignId");
    openapiFields.add("customText");
    openapiFields.add("extendedData");
    openapiFields.add("globalAdId");
    openapiFields.add("globalStoreSetting");
    openapiFields.add("sku");
    openapiFields.add("state");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("adGroupId");
    openapiRequiredFields.add("adId");
    openapiRequiredFields.add("campaignId");
    openapiRequiredFields.add("state");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SponsoredProductsProductAd
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SponsoredProductsProductAd.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SponsoredProductsProductAd is not found in the empty JSON string", SponsoredProductsProductAd.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SponsoredProductsProductAd.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SponsoredProductsProductAd` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SponsoredProductsProductAd.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("adGroupId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `adGroupId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("adGroupId").toString()));
      }
      if (!jsonObj.get("adId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `adId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("adId").toString()));
      }
      if ((jsonObj.get("asin") != null && !jsonObj.get("asin").isJsonNull()) && !jsonObj.get("asin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `asin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asin").toString()));
      }
      if (!jsonObj.get("campaignId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `campaignId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("campaignId").toString()));
      }
      if ((jsonObj.get("customText") != null && !jsonObj.get("customText").isJsonNull()) && !jsonObj.get("customText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customText").toString()));
      }
      // validate the optional field `extendedData`
      if (jsonObj.get("extendedData") != null && !jsonObj.get("extendedData").isJsonNull()) {
        SponsoredProductsProductAdExtendedData.validateJsonElement(jsonObj.get("extendedData"));
      }
      if ((jsonObj.get("globalAdId") != null && !jsonObj.get("globalAdId").isJsonNull()) && !jsonObj.get("globalAdId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `globalAdId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("globalAdId").toString()));
      }
      // validate the optional field `globalStoreSetting`
      if (jsonObj.get("globalStoreSetting") != null && !jsonObj.get("globalStoreSetting").isJsonNull()) {
        SponsoredProductsGlobalStoreSetting.validateJsonElement(jsonObj.get("globalStoreSetting"));
      }
      if ((jsonObj.get("sku") != null && !jsonObj.get("sku").isJsonNull()) && !jsonObj.get("sku").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sku` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sku").toString()));
      }
      // validate the required field `state`
      SponsoredProductsEntityState.validateJsonElement(jsonObj.get("state"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SponsoredProductsProductAd.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SponsoredProductsProductAd' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SponsoredProductsProductAd> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SponsoredProductsProductAd.class));

       return (TypeAdapter<T>) new TypeAdapter<SponsoredProductsProductAd>() {
           @Override
           public void write(JsonWriter out, SponsoredProductsProductAd value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SponsoredProductsProductAd read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SponsoredProductsProductAd given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SponsoredProductsProductAd
   * @throws IOException if the JSON string is invalid with respect to SponsoredProductsProductAd
   */
  public static SponsoredProductsProductAd fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SponsoredProductsProductAd.class);
  }

  /**
   * Convert an instance of SponsoredProductsProductAd to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

