/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Contains suggested recommendation for the auto targeting group.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class TargetingGroupBidRecommendation {
  /**
   * Type of suggested action.
   */
  @JsonAdapter(ActionEnum.Adapter.class)
  public enum ActionEnum {
    ADD("ADD"),
    
    DECREASE("DECREASE"),
    
    INCREASE("INCREASE"),
    
    REMOVE("REMOVE");

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ActionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ActionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ActionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ActionEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ActionEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  @javax.annotation.Nullable
  private ActionEnum action;

  public static final String SERIALIZED_NAME_AD_GROUP_ID = "adGroupId";
  @SerializedName(SERIALIZED_NAME_AD_GROUP_ID)
  @javax.annotation.Nullable
  private String adGroupId;

  public static final String SERIALIZED_NAME_SUGGESTED_BID = "suggestedBid";
  @SerializedName(SERIALIZED_NAME_SUGGESTED_BID)
  @javax.annotation.Nullable
  private Double suggestedBid;

  public static final String SERIALIZED_NAME_TARGET_ID = "targetId";
  @SerializedName(SERIALIZED_NAME_TARGET_ID)
  @javax.annotation.Nullable
  private String targetId;

  /**
   * The type of targeting group expression. | Value | Description | | --- | --- | | &#x60;LOOSE_MATCH&#x60; | This will show your ad to shoppers who use search terms loosely related to your products.| | &#x60;CLOSE_MATCH&#x60; | This will show your ad to shoppers who use search terms closely related to your products.| | &#x60;COMPLEMENTS&#x60; | This will show your ad to shoppers who view the detail pages of products that complement your product.| | &#x60;SUBSTITUTES&#x60; | This will show your ad to shoppers who use detail pages of products similar to yours.|
   */
  @JsonAdapter(TargetingGroupExpressionEnum.Adapter.class)
  public enum TargetingGroupExpressionEnum {
    CLOSE_MATCH("CLOSE_MATCH"),
    
    COMPLEMENTS("COMPLEMENTS"),
    
    LOOSE_MATCH("LOOSE_MATCH"),
    
    SUBSTITUTES("SUBSTITUTES");

    private String value;

    TargetingGroupExpressionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TargetingGroupExpressionEnum fromValue(String value) {
      for (TargetingGroupExpressionEnum b : TargetingGroupExpressionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TargetingGroupExpressionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TargetingGroupExpressionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TargetingGroupExpressionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TargetingGroupExpressionEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TargetingGroupExpressionEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TARGETING_GROUP_EXPRESSION = "targetingGroupExpression";
  @SerializedName(SERIALIZED_NAME_TARGETING_GROUP_EXPRESSION)
  @javax.annotation.Nullable
  private TargetingGroupExpressionEnum targetingGroupExpression;

  public TargetingGroupBidRecommendation() {
  }

  public TargetingGroupBidRecommendation action(@javax.annotation.Nullable ActionEnum action) {
    this.action = action;
    return this;
  }

  /**
   * Type of suggested action.
   * @return action
   */
  @javax.annotation.Nullable

  public ActionEnum getAction() {
    return action;
  }

  public void setAction(@javax.annotation.Nullable ActionEnum action) {
    this.action = action;
  }


  public TargetingGroupBidRecommendation adGroupId(@javax.annotation.Nullable String adGroupId) {
    this.adGroupId = adGroupId;
    return this;
  }

  /**
   * The ad group identifier.
   * @return adGroupId
   */
  @javax.annotation.Nullable

  public String getAdGroupId() {
    return adGroupId;
  }

  public void setAdGroupId(@javax.annotation.Nullable String adGroupId) {
    this.adGroupId = adGroupId;
  }


  public TargetingGroupBidRecommendation suggestedBid(@javax.annotation.Nullable Double suggestedBid) {
    this.suggestedBid = suggestedBid;
    return this;
  }

  /**
   * The suggested bid value associated with this targeting.
   * @return suggestedBid
   */
  @javax.annotation.Nullable

  public Double getSuggestedBid() {
    return suggestedBid;
  }

  public void setSuggestedBid(@javax.annotation.Nullable Double suggestedBid) {
    this.suggestedBid = suggestedBid;
  }


  public TargetingGroupBidRecommendation targetId(@javax.annotation.Nullable String targetId) {
    this.targetId = targetId;
    return this;
  }

  /**
   * The target identifier.
   * @return targetId
   */
  @javax.annotation.Nullable

  public String getTargetId() {
    return targetId;
  }

  public void setTargetId(@javax.annotation.Nullable String targetId) {
    this.targetId = targetId;
  }


  public TargetingGroupBidRecommendation targetingGroupExpression(@javax.annotation.Nullable TargetingGroupExpressionEnum targetingGroupExpression) {
    this.targetingGroupExpression = targetingGroupExpression;
    return this;
  }

  /**
   * The type of targeting group expression. | Value | Description | | --- | --- | | &#x60;LOOSE_MATCH&#x60; | This will show your ad to shoppers who use search terms loosely related to your products.| | &#x60;CLOSE_MATCH&#x60; | This will show your ad to shoppers who use search terms closely related to your products.| | &#x60;COMPLEMENTS&#x60; | This will show your ad to shoppers who view the detail pages of products that complement your product.| | &#x60;SUBSTITUTES&#x60; | This will show your ad to shoppers who use detail pages of products similar to yours.|
   * @return targetingGroupExpression
   */
  @javax.annotation.Nullable

  public TargetingGroupExpressionEnum getTargetingGroupExpression() {
    return targetingGroupExpression;
  }

  public void setTargetingGroupExpression(@javax.annotation.Nullable TargetingGroupExpressionEnum targetingGroupExpression) {
    this.targetingGroupExpression = targetingGroupExpression;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TargetingGroupBidRecommendation targetingGroupBidRecommendation = (TargetingGroupBidRecommendation) o;
    return Objects.equals(this.action, targetingGroupBidRecommendation.action) &&
        Objects.equals(this.adGroupId, targetingGroupBidRecommendation.adGroupId) &&
        Objects.equals(this.suggestedBid, targetingGroupBidRecommendation.suggestedBid) &&
        Objects.equals(this.targetId, targetingGroupBidRecommendation.targetId) &&
        Objects.equals(this.targetingGroupExpression, targetingGroupBidRecommendation.targetingGroupExpression);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, adGroupId, suggestedBid, targetId, targetingGroupExpression);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TargetingGroupBidRecommendation {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    adGroupId: ").append(toIndentedString(adGroupId)).append("\n");
    sb.append("    suggestedBid: ").append(toIndentedString(suggestedBid)).append("\n");
    sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
    sb.append("    targetingGroupExpression: ").append(toIndentedString(targetingGroupExpression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("action");
    openapiFields.add("adGroupId");
    openapiFields.add("suggestedBid");
    openapiFields.add("targetId");
    openapiFields.add("targetingGroupExpression");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TargetingGroupBidRecommendation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TargetingGroupBidRecommendation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TargetingGroupBidRecommendation is not found in the empty JSON string", TargetingGroupBidRecommendation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TargetingGroupBidRecommendation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TargetingGroupBidRecommendation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("action") != null && !jsonObj.get("action").isJsonNull()) && !jsonObj.get("action").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `action` to be a primitive type in the JSON string but got `%s`", jsonObj.get("action").toString()));
      }
      // validate the optional field `action`
      if (jsonObj.get("action") != null && !jsonObj.get("action").isJsonNull()) {
        ActionEnum.validateJsonElement(jsonObj.get("action"));
      }
      if ((jsonObj.get("adGroupId") != null && !jsonObj.get("adGroupId").isJsonNull()) && !jsonObj.get("adGroupId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `adGroupId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("adGroupId").toString()));
      }
      if ((jsonObj.get("targetId") != null && !jsonObj.get("targetId").isJsonNull()) && !jsonObj.get("targetId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetId").toString()));
      }
      if ((jsonObj.get("targetingGroupExpression") != null && !jsonObj.get("targetingGroupExpression").isJsonNull()) && !jsonObj.get("targetingGroupExpression").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetingGroupExpression` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetingGroupExpression").toString()));
      }
      // validate the optional field `targetingGroupExpression`
      if (jsonObj.get("targetingGroupExpression") != null && !jsonObj.get("targetingGroupExpression").isJsonNull()) {
        TargetingGroupExpressionEnum.validateJsonElement(jsonObj.get("targetingGroupExpression"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TargetingGroupBidRecommendation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TargetingGroupBidRecommendation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TargetingGroupBidRecommendation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TargetingGroupBidRecommendation.class));

       return (TypeAdapter<T>) new TypeAdapter<TargetingGroupBidRecommendation>() {
           @Override
           public void write(JsonWriter out, TargetingGroupBidRecommendation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TargetingGroupBidRecommendation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TargetingGroupBidRecommendation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TargetingGroupBidRecommendation
   * @throws IOException if the JSON string is invalid with respect to TargetingGroupBidRecommendation
   */
  public static TargetingGroupBidRecommendation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TargetingGroupBidRecommendation.class);
  }

  /**
   * Convert an instance of TargetingGroupBidRecommendation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

