sourceUrl=https://d1y2lf8k3vrkfu.cloudfront.net/openapi/en-us/dest/AmazonAdsAPIALLMerged_prod_3p.json
sourceSha256=caf73369a27e2830e7b2714cf24350cbbd45e0b11673e237823878705f74e584
generatorVersion=7.24.0
operations=CreateCampaign,DeleteCampaign,QueryCampaign,UpdateCampaign
