sourceUrl=https://d1y2lf8k3vrkfu.cloudfront.net/openapi/en-us/dest/AmazonAdsAPIALLTargetsContract_prod_3p.json
sourceSha256=99dd1446a54717d822c6485cbf81b7a9c4cc5817c083e9b634301d30b4767bed
generatorVersion=7.24.0
operations=CreateTarget,DeleteTarget,QueryTarget,UpdateTarget
