/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.IOException;
import java.util.*;

/**
 * CampaignOptimizationRule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class CampaignOptimizationRule {
  public static final String SERIALIZED_NAME_CAMPAIGN_IDS = "campaignIds";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_IDS)
  @javax.annotation.Nullable
  private List<String> campaignIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_CAMPAIGN_OPTIMIZATION_ID = "campaignOptimizationId";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_OPTIMIZATION_ID)
  @javax.annotation.Nonnull
  private String campaignOptimizationId;

  public static final String SERIALIZED_NAME_CREATED_DATE = "createdDate";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE)
  @javax.annotation.Nullable
  private String createdDate;

  public static final String SERIALIZED_NAME_RECURRENCE = "recurrence";
  @SerializedName(SERIALIZED_NAME_RECURRENCE)
  @javax.annotation.Nullable
  private RecurrenceType recurrence;

  public static final String SERIALIZED_NAME_RULE_ACTION = "ruleAction";
  @SerializedName(SERIALIZED_NAME_RULE_ACTION)
  @javax.annotation.Nullable
  private RuleAction ruleAction;

  public static final String SERIALIZED_NAME_RULE_CONDITION = "ruleCondition";
  @SerializedName(SERIALIZED_NAME_RULE_CONDITION)
  @javax.annotation.Nullable
  private List<@Valid RuleCondition> ruleCondition = new ArrayList<>();

  public static final String SERIALIZED_NAME_RULE_NAME = "ruleName";
  @SerializedName(SERIALIZED_NAME_RULE_NAME)
  @javax.annotation.Nullable
  private String ruleName;

  public static final String SERIALIZED_NAME_RULE_STATUS = "ruleStatus";
  @SerializedName(SERIALIZED_NAME_RULE_STATUS)
  @javax.annotation.Nullable
  private RuleStatus ruleStatus;

  public static final String SERIALIZED_NAME_RULE_TYPE = "ruleType";
  @SerializedName(SERIALIZED_NAME_RULE_TYPE)
  @javax.annotation.Nullable
  private RuleType ruleType;

  public CampaignOptimizationRule() {
  }

  public CampaignOptimizationRule campaignIds(@javax.annotation.Nullable List<String> campaignIds) {
    this.campaignIds = campaignIds;
    return this;
  }

  public CampaignOptimizationRule addCampaignIdsItem(String campaignIdsItem) {
    if (this.campaignIds == null) {
      this.campaignIds = new ArrayList<>();
    }
    this.campaignIds.add(campaignIdsItem);
    return this;
  }

  /**
   * Get campaignIds
   * @return campaignIds
   */
  @javax.annotation.Nullable
 @Size(max=100)
  public List<String> getCampaignIds() {
    return campaignIds;
  }

  public void setCampaignIds(@javax.annotation.Nullable List<String> campaignIds) {
    this.campaignIds = campaignIds;
  }


  public CampaignOptimizationRule campaignOptimizationId(@javax.annotation.Nonnull String campaignOptimizationId) {
    this.campaignOptimizationId = campaignOptimizationId;
    return this;
  }

  /**
   * The persistent rule identifier.
   * @return campaignOptimizationId
   */
  @javax.annotation.Nonnull
  @NotNull
 @Size(max=355)
  public String getCampaignOptimizationId() {
    return campaignOptimizationId;
  }

  public void setCampaignOptimizationId(@javax.annotation.Nonnull String campaignOptimizationId) {
    this.campaignOptimizationId = campaignOptimizationId;
  }


  public CampaignOptimizationRule createdDate(@javax.annotation.Nullable String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * Time of campaign optimization rule creation in ISO 8061. Read-only.
   * @return createdDate
   */
  @javax.annotation.Nullable

  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(@javax.annotation.Nullable String createdDate) {
    this.createdDate = createdDate;
  }


  public CampaignOptimizationRule recurrence(@javax.annotation.Nullable RecurrenceType recurrence) {
    this.recurrence = recurrence;
    return this;
  }

  /**
   * Get recurrence
   * @return recurrence
   */
  @javax.annotation.Nullable
  @Valid

  public RecurrenceType getRecurrence() {
    return recurrence;
  }

  public void setRecurrence(@javax.annotation.Nullable RecurrenceType recurrence) {
    this.recurrence = recurrence;
  }


  public CampaignOptimizationRule ruleAction(@javax.annotation.Nullable RuleAction ruleAction) {
    this.ruleAction = ruleAction;
    return this;
  }

  /**
   * Get ruleAction
   * @return ruleAction
   */
  @javax.annotation.Nullable
  @Valid

  public RuleAction getRuleAction() {
    return ruleAction;
  }

  public void setRuleAction(@javax.annotation.Nullable RuleAction ruleAction) {
    this.ruleAction = ruleAction;
  }


  public CampaignOptimizationRule ruleCondition(@javax.annotation.Nullable List<@Valid RuleCondition> ruleCondition) {
    this.ruleCondition = ruleCondition;
    return this;
  }

  public CampaignOptimizationRule addRuleConditionItem(RuleCondition ruleConditionItem) {
    if (this.ruleCondition == null) {
      this.ruleCondition = new ArrayList<>();
    }
    this.ruleCondition.add(ruleConditionItem);
    return this;
  }

  /**
   * Get ruleCondition
   * @return ruleCondition
   */
  @javax.annotation.Nullable
  @Valid
 @Size(max=3)
  public List<@Valid RuleCondition> getRuleCondition() {
    return ruleCondition;
  }

  public void setRuleCondition(@javax.annotation.Nullable List<@Valid RuleCondition> ruleCondition) {
    this.ruleCondition = ruleCondition;
  }


  public CampaignOptimizationRule ruleName(@javax.annotation.Nullable String ruleName) {
    this.ruleName = ruleName;
    return this;
  }

  /**
   * The campaign optimization rule name.
   * @return ruleName
   */
  @javax.annotation.Nullable
 @Size(max=355)
  public String getRuleName() {
    return ruleName;
  }

  public void setRuleName(@javax.annotation.Nullable String ruleName) {
    this.ruleName = ruleName;
  }


  public CampaignOptimizationRule ruleStatus(@javax.annotation.Nullable RuleStatus ruleStatus) {
    this.ruleStatus = ruleStatus;
    return this;
  }

  /**
   * Get ruleStatus
   * @return ruleStatus
   */
  @javax.annotation.Nullable
  @Valid

  public RuleStatus getRuleStatus() {
    return ruleStatus;
  }

  public void setRuleStatus(@javax.annotation.Nullable RuleStatus ruleStatus) {
    this.ruleStatus = ruleStatus;
  }


  public CampaignOptimizationRule ruleType(@javax.annotation.Nullable RuleType ruleType) {
    this.ruleType = ruleType;
    return this;
  }

  /**
   * Get ruleType
   * @return ruleType
   */
  @javax.annotation.Nullable
  @Valid

  public RuleType getRuleType() {
    return ruleType;
  }

  public void setRuleType(@javax.annotation.Nullable RuleType ruleType) {
    this.ruleType = ruleType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignOptimizationRule campaignOptimizationRule = (CampaignOptimizationRule) o;
    return Objects.equals(this.campaignIds, campaignOptimizationRule.campaignIds) &&
        Objects.equals(this.campaignOptimizationId, campaignOptimizationRule.campaignOptimizationId) &&
        Objects.equals(this.createdDate, campaignOptimizationRule.createdDate) &&
        Objects.equals(this.recurrence, campaignOptimizationRule.recurrence) &&
        Objects.equals(this.ruleAction, campaignOptimizationRule.ruleAction) &&
        Objects.equals(this.ruleCondition, campaignOptimizationRule.ruleCondition) &&
        Objects.equals(this.ruleName, campaignOptimizationRule.ruleName) &&
        Objects.equals(this.ruleStatus, campaignOptimizationRule.ruleStatus) &&
        Objects.equals(this.ruleType, campaignOptimizationRule.ruleType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignIds, campaignOptimizationId, createdDate, recurrence, ruleAction, ruleCondition, ruleName, ruleStatus, ruleType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignOptimizationRule {\n");
    sb.append("    campaignIds: ").append(toIndentedString(campaignIds)).append("\n");
    sb.append("    campaignOptimizationId: ").append(toIndentedString(campaignOptimizationId)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    recurrence: ").append(toIndentedString(recurrence)).append("\n");
    sb.append("    ruleAction: ").append(toIndentedString(ruleAction)).append("\n");
    sb.append("    ruleCondition: ").append(toIndentedString(ruleCondition)).append("\n");
    sb.append("    ruleName: ").append(toIndentedString(ruleName)).append("\n");
    sb.append("    ruleStatus: ").append(toIndentedString(ruleStatus)).append("\n");
    sb.append("    ruleType: ").append(toIndentedString(ruleType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("campaignIds");
    openapiFields.add("campaignOptimizationId");
    openapiFields.add("createdDate");
    openapiFields.add("recurrence");
    openapiFields.add("ruleAction");
    openapiFields.add("ruleCondition");
    openapiFields.add("ruleName");
    openapiFields.add("ruleStatus");
    openapiFields.add("ruleType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("campaignOptimizationId");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CampaignOptimizationRule
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CampaignOptimizationRule.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CampaignOptimizationRule is not found in the empty JSON string", CampaignOptimizationRule.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CampaignOptimizationRule.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CampaignOptimizationRule` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CampaignOptimizationRule.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("campaignIds") != null && !jsonObj.get("campaignIds").isJsonNull() && !jsonObj.get("campaignIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `campaignIds` to be an array in the JSON string but got `%s`", jsonObj.get("campaignIds").toString()));
      }
      if (!jsonObj.get("campaignOptimizationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `campaignOptimizationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("campaignOptimizationId").toString()));
      }
      if ((jsonObj.get("createdDate") != null && !jsonObj.get("createdDate").isJsonNull()) && !jsonObj.get("createdDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdDate").toString()));
      }
      // validate the optional field `recurrence`
      if (jsonObj.get("recurrence") != null && !jsonObj.get("recurrence").isJsonNull()) {
        RecurrenceType.validateJsonElement(jsonObj.get("recurrence"));
      }
      // validate the optional field `ruleAction`
      if (jsonObj.get("ruleAction") != null && !jsonObj.get("ruleAction").isJsonNull()) {
        RuleAction.validateJsonElement(jsonObj.get("ruleAction"));
      }
      if (jsonObj.get("ruleCondition") != null && !jsonObj.get("ruleCondition").isJsonNull()) {
        JsonArray jsonArrayruleCondition = jsonObj.getAsJsonArray("ruleCondition");
        if (jsonArrayruleCondition != null) {
          // ensure the json data is an array
          if (!jsonObj.get("ruleCondition").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `ruleCondition` to be an array in the JSON string but got `%s`", jsonObj.get("ruleCondition").toString()));
          }

          // validate the optional field `ruleCondition` (array)
          for (int i = 0; i < jsonArrayruleCondition.size(); i++) {
            RuleCondition.validateJsonElement(jsonArrayruleCondition.get(i));
          };
        }
      }
      if ((jsonObj.get("ruleName") != null && !jsonObj.get("ruleName").isJsonNull()) && !jsonObj.get("ruleName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ruleName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ruleName").toString()));
      }
      // validate the optional field `ruleStatus`
      if (jsonObj.get("ruleStatus") != null && !jsonObj.get("ruleStatus").isJsonNull()) {
        RuleStatus.validateJsonElement(jsonObj.get("ruleStatus"));
      }
      // validate the optional field `ruleType`
      if (jsonObj.get("ruleType") != null && !jsonObj.get("ruleType").isJsonNull()) {
        RuleType.validateJsonElement(jsonObj.get("ruleType"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CampaignOptimizationRule.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CampaignOptimizationRule' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CampaignOptimizationRule> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CampaignOptimizationRule.class));

       return (TypeAdapter<T>) new TypeAdapter<CampaignOptimizationRule>() {
           @Override
           public void write(JsonWriter out, CampaignOptimizationRule value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CampaignOptimizationRule read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CampaignOptimizationRule given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CampaignOptimizationRule
   * @throws IOException if the JSON string is invalid with respect to CampaignOptimizationRule
   */
  public static CampaignOptimizationRule fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CampaignOptimizationRule.class);
  }

  /**
   * Convert an instance of CampaignOptimizationRule to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

