/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.IOException;
import java.util.*;

/**
 * GetCampaignRecommendationsRequestV2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class GetCampaignRecommendationsRequestV2 {
  public static final String SERIALIZED_NAME_CAMPAIGNS = "campaigns";
  @SerializedName(SERIALIZED_NAME_CAMPAIGNS)
  @javax.annotation.Nonnull
  private List<@Valid Campaign> campaigns = new ArrayList<>();

  public static final String SERIALIZED_NAME_MAX_RESULTS = "maxResults";
  @SerializedName(SERIALIZED_NAME_MAX_RESULTS)
  @javax.annotation.Nullable
  private Integer maxResults;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "nextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public GetCampaignRecommendationsRequestV2() {
  }

  public GetCampaignRecommendationsRequestV2 campaigns(@javax.annotation.Nonnull List<@Valid Campaign> campaigns) {
    this.campaigns = campaigns;
    return this;
  }

  public GetCampaignRecommendationsRequestV2 addCampaignsItem(Campaign campaignsItem) {
    if (this.campaigns == null) {
      this.campaigns = new ArrayList<>();
    }
    this.campaigns.add(campaignsItem);
    return this;
  }

  /**
   * List of campaigns with specific recommendation types requested.
   * @return campaigns
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid
 @Size(min=1,max=10)
  public List<@Valid Campaign> getCampaigns() {
    return campaigns;
  }

  public void setCampaigns(@javax.annotation.Nonnull List<@Valid Campaign> campaigns) {
    this.campaigns = campaigns;
  }


  public GetCampaignRecommendationsRequestV2 maxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
    return this;
  }

  /**
   * Optional. Limits the number of items to return in the response.
   * minimum: 1
   * maximum: 5
   * @return maxResults
   */
  @javax.annotation.Nullable
 @Min(1) @Max(5)
  public Integer getMaxResults() {
    return maxResults;
  }

  public void setMaxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
  }


  public GetCampaignRecommendationsRequestV2 nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * Optional. Token to retrieve subsequent page of results.
   * @return nextToken
   */
  @javax.annotation.Nullable

  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCampaignRecommendationsRequestV2 getCampaignRecommendationsRequestV2 = (GetCampaignRecommendationsRequestV2) o;
    return Objects.equals(this.campaigns, getCampaignRecommendationsRequestV2.campaigns) &&
        Objects.equals(this.maxResults, getCampaignRecommendationsRequestV2.maxResults) &&
        Objects.equals(this.nextToken, getCampaignRecommendationsRequestV2.nextToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaigns, maxResults, nextToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCampaignRecommendationsRequestV2 {\n");
    sb.append("    campaigns: ").append(toIndentedString(campaigns)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("campaigns");
    openapiFields.add("maxResults");
    openapiFields.add("nextToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("campaigns");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetCampaignRecommendationsRequestV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetCampaignRecommendationsRequestV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetCampaignRecommendationsRequestV2 is not found in the empty JSON string", GetCampaignRecommendationsRequestV2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetCampaignRecommendationsRequestV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetCampaignRecommendationsRequestV2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetCampaignRecommendationsRequestV2.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("campaigns").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `campaigns` to be an array in the JSON string but got `%s`", jsonObj.get("campaigns").toString()));
      }

      JsonArray jsonArraycampaigns = jsonObj.getAsJsonArray("campaigns");
      // validate the required field `campaigns` (array)
      for (int i = 0; i < jsonArraycampaigns.size(); i++) {
        Campaign.validateJsonElement(jsonArraycampaigns.get(i));
      };
      if ((jsonObj.get("nextToken") != null && !jsonObj.get("nextToken").isJsonNull()) && !jsonObj.get("nextToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nextToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextToken").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetCampaignRecommendationsRequestV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetCampaignRecommendationsRequestV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetCampaignRecommendationsRequestV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetCampaignRecommendationsRequestV2.class));

       return (TypeAdapter<T>) new TypeAdapter<GetCampaignRecommendationsRequestV2>() {
           @Override
           public void write(JsonWriter out, GetCampaignRecommendationsRequestV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetCampaignRecommendationsRequestV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetCampaignRecommendationsRequestV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetCampaignRecommendationsRequestV2
   * @throws IOException if the JSON string is invalid with respect to GetCampaignRecommendationsRequestV2
   */
  public static GetCampaignRecommendationsRequestV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetCampaignRecommendationsRequestV2.class);
  }

  /**
   * Convert an instance of GetCampaignRecommendationsRequestV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

