/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import java.io.IOException;
import java.util.*;

/**
 * Response object for the POST /sp/targets/category/{categoryId}/refinements endpoint, containing information on Brand Nodes, Age Range Nodes, and Genre Nodes.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class RefinementsLoP {
  public static final String SERIALIZED_NAME_AGE_RANGES = "ageRanges";
  @SerializedName(SERIALIZED_NAME_AGE_RANGES)
  @javax.annotation.Nullable
  private List<@Valid AgeRangeLoP> ageRanges = new ArrayList<>();

  public static final String SERIALIZED_NAME_BRANDS = "brands";
  @SerializedName(SERIALIZED_NAME_BRANDS)
  @javax.annotation.Nullable
  private List<@Valid BrandLoP> brands = new ArrayList<>();

  public static final String SERIALIZED_NAME_GENRES = "genres";
  @SerializedName(SERIALIZED_NAME_GENRES)
  @javax.annotation.Nullable
  private List<@Valid GenreLoP> genres = new ArrayList<>();

  public RefinementsLoP() {
  }

  public RefinementsLoP ageRanges(@javax.annotation.Nullable List<@Valid AgeRangeLoP> ageRanges) {
    this.ageRanges = ageRanges;
    return this;
  }

  public RefinementsLoP addAgeRangesItem(AgeRangeLoP ageRangesItem) {
    if (this.ageRanges == null) {
      this.ageRanges = new ArrayList<>();
    }
    this.ageRanges.add(ageRangesItem);
    return this;
  }

  /**
   * List of Age Ranges in a language of preference (LoP). Use the POST /sp/targets/category/{categoryId}/refinements endpoint to retrieve Age Ranges. Age Ranges are only available for categories related to children&#39;s toys and games.
   * @return ageRanges
   */
  @javax.annotation.Nullable
  @Valid

  public List<@Valid AgeRangeLoP> getAgeRanges() {
    return ageRanges;
  }

  public void setAgeRanges(@javax.annotation.Nullable List<@Valid AgeRangeLoP> ageRanges) {
    this.ageRanges = ageRanges;
  }


  public RefinementsLoP brands(@javax.annotation.Nullable List<@Valid BrandLoP> brands) {
    this.brands = brands;
    return this;
  }

  public RefinementsLoP addBrandsItem(BrandLoP brandsItem) {
    if (this.brands == null) {
      this.brands = new ArrayList<>();
    }
    this.brands.add(brandsItem);
    return this;
  }

  /**
   * List of Brands.
   * @return brands
   */
  @javax.annotation.Nullable
  @Valid

  public List<@Valid BrandLoP> getBrands() {
    return brands;
  }

  public void setBrands(@javax.annotation.Nullable List<@Valid BrandLoP> brands) {
    this.brands = brands;
  }


  public RefinementsLoP genres(@javax.annotation.Nullable List<@Valid GenreLoP> genres) {
    this.genres = genres;
    return this;
  }

  public RefinementsLoP addGenresItem(GenreLoP genresItem) {
    if (this.genres == null) {
      this.genres = new ArrayList<>();
    }
    this.genres.add(genresItem);
    return this;
  }

  /**
   * List of Genres in a language of preference (LoP). Use the POST /sp/targets/category/{categoryId}/refinements endpoint to retrieve Genre Node IDs. Genres are only available for categories related to books.
   * @return genres
   */
  @javax.annotation.Nullable
  @Valid

  public List<@Valid GenreLoP> getGenres() {
    return genres;
  }

  public void setGenres(@javax.annotation.Nullable List<@Valid GenreLoP> genres) {
    this.genres = genres;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefinementsLoP refinementsLoP = (RefinementsLoP) o;
    return Objects.equals(this.ageRanges, refinementsLoP.ageRanges) &&
        Objects.equals(this.brands, refinementsLoP.brands) &&
        Objects.equals(this.genres, refinementsLoP.genres);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ageRanges, brands, genres);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefinementsLoP {\n");
    sb.append("    ageRanges: ").append(toIndentedString(ageRanges)).append("\n");
    sb.append("    brands: ").append(toIndentedString(brands)).append("\n");
    sb.append("    genres: ").append(toIndentedString(genres)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ageRanges");
    openapiFields.add("brands");
    openapiFields.add("genres");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RefinementsLoP
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RefinementsLoP.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RefinementsLoP is not found in the empty JSON string", RefinementsLoP.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RefinementsLoP.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RefinementsLoP` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("ageRanges") != null && !jsonObj.get("ageRanges").isJsonNull()) {
        JsonArray jsonArrayageRanges = jsonObj.getAsJsonArray("ageRanges");
        if (jsonArrayageRanges != null) {
          // ensure the json data is an array
          if (!jsonObj.get("ageRanges").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `ageRanges` to be an array in the JSON string but got `%s`", jsonObj.get("ageRanges").toString()));
          }

          // validate the optional field `ageRanges` (array)
          for (int i = 0; i < jsonArrayageRanges.size(); i++) {
            AgeRangeLoP.validateJsonElement(jsonArrayageRanges.get(i));
          };
        }
      }
      if (jsonObj.get("brands") != null && !jsonObj.get("brands").isJsonNull()) {
        JsonArray jsonArraybrands = jsonObj.getAsJsonArray("brands");
        if (jsonArraybrands != null) {
          // ensure the json data is an array
          if (!jsonObj.get("brands").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `brands` to be an array in the JSON string but got `%s`", jsonObj.get("brands").toString()));
          }

          // validate the optional field `brands` (array)
          for (int i = 0; i < jsonArraybrands.size(); i++) {
            BrandLoP.validateJsonElement(jsonArraybrands.get(i));
          };
        }
      }
      if (jsonObj.get("genres") != null && !jsonObj.get("genres").isJsonNull()) {
        JsonArray jsonArraygenres = jsonObj.getAsJsonArray("genres");
        if (jsonArraygenres != null) {
          // ensure the json data is an array
          if (!jsonObj.get("genres").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `genres` to be an array in the JSON string but got `%s`", jsonObj.get("genres").toString()));
          }

          // validate the optional field `genres` (array)
          for (int i = 0; i < jsonArraygenres.size(); i++) {
            GenreLoP.validateJsonElement(jsonArraygenres.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RefinementsLoP.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RefinementsLoP' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RefinementsLoP> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RefinementsLoP.class));

       return (TypeAdapter<T>) new TypeAdapter<RefinementsLoP>() {
           @Override
           public void write(JsonWriter out, RefinementsLoP value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RefinementsLoP read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RefinementsLoP given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RefinementsLoP
   * @throws IOException if the JSON string is invalid with respect to RefinementsLoP
   */
  public static RefinementsLoP fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RefinementsLoP.class);
  }

  /**
   * Convert an instance of RefinementsLoP to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

