/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * A product target.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class SponsoredProductsProductTargetV2 {
  public static final String SERIALIZED_NAME_DESTINATION_AD_GROUP_ID = "destinationAdGroupId";
  @SerializedName(SERIALIZED_NAME_DESTINATION_AD_GROUP_ID)
  @javax.annotation.Nullable
  private String destinationAdGroupId;

  public static final String SERIALIZED_NAME_EXPRESSION_TYPE = "expressionType";
  @SerializedName(SERIALIZED_NAME_EXPRESSION_TYPE)
  @javax.annotation.Nullable
  private String expressionType;

  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  @javax.annotation.Nullable
  private String target;

  public static final String SERIALIZED_NAME_TARGET_ID = "targetId";
  @SerializedName(SERIALIZED_NAME_TARGET_ID)
  @javax.annotation.Nullable
  private String targetId;

  public static final String SERIALIZED_NAME_TARGET_PROMOTION_GROUP_ID = "targetPromotionGroupId";
  @SerializedName(SERIALIZED_NAME_TARGET_PROMOTION_GROUP_ID)
  @javax.annotation.Nullable
  private String targetPromotionGroupId;

  public SponsoredProductsProductTargetV2() {
  }

  public SponsoredProductsProductTargetV2 destinationAdGroupId(@javax.annotation.Nullable String destinationAdGroupId) {
    this.destinationAdGroupId = destinationAdGroupId;
    return this;
  }

  /**
   * The adGroupId of the destination manual-targeting adGroup where the target belongs.
   * @return destinationAdGroupId
   */
  @javax.annotation.Nullable

  public String getDestinationAdGroupId() {
    return destinationAdGroupId;
  }

  public void setDestinationAdGroupId(@javax.annotation.Nullable String destinationAdGroupId) {
    this.destinationAdGroupId = destinationAdGroupId;
  }


  public SponsoredProductsProductTargetV2 expressionType(@javax.annotation.Nullable String expressionType) {
    this.expressionType = expressionType;
    return this;
  }

  /**
   * The the expression type (for PRODUCT). One of PRODUCT_EXACT, PRODUCT_SIMILAR
   * @return expressionType
   */
  @javax.annotation.Nullable

  public String getExpressionType() {
    return expressionType;
  }

  public void setExpressionType(@javax.annotation.Nullable String expressionType) {
    this.expressionType = expressionType;
  }


  public SponsoredProductsProductTargetV2 target(@javax.annotation.Nullable String target) {
    this.target = target;
    return this;
  }

  /**
   * The product ASIN of the target.
   * @return target
   */
  @javax.annotation.Nullable

  public String getTarget() {
    return target;
  }

  public void setTarget(@javax.annotation.Nullable String target) {
    this.target = target;
  }


  public SponsoredProductsProductTargetV2 targetId(@javax.annotation.Nullable String targetId) {
    this.targetId = targetId;
    return this;
  }

  /**
   * The id of the product target.
   * @return targetId
   */
  @javax.annotation.Nullable

  public String getTargetId() {
    return targetId;
  }

  public void setTargetId(@javax.annotation.Nullable String targetId) {
    this.targetId = targetId;
  }


  public SponsoredProductsProductTargetV2 targetPromotionGroupId(@javax.annotation.Nullable String targetPromotionGroupId) {
    this.targetPromotionGroupId = targetPromotionGroupId;
    return this;
  }

  /**
   * The id of the target promotion group.
   * @return targetPromotionGroupId
   */
  @javax.annotation.Nullable

  public String getTargetPromotionGroupId() {
    return targetPromotionGroupId;
  }

  public void setTargetPromotionGroupId(@javax.annotation.Nullable String targetPromotionGroupId) {
    this.targetPromotionGroupId = targetPromotionGroupId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SponsoredProductsProductTargetV2 sponsoredProductsProductTargetV2 = (SponsoredProductsProductTargetV2) o;
    return Objects.equals(this.destinationAdGroupId, sponsoredProductsProductTargetV2.destinationAdGroupId) &&
        Objects.equals(this.expressionType, sponsoredProductsProductTargetV2.expressionType) &&
        Objects.equals(this.target, sponsoredProductsProductTargetV2.target) &&
        Objects.equals(this.targetId, sponsoredProductsProductTargetV2.targetId) &&
        Objects.equals(this.targetPromotionGroupId, sponsoredProductsProductTargetV2.targetPromotionGroupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destinationAdGroupId, expressionType, target, targetId, targetPromotionGroupId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SponsoredProductsProductTargetV2 {\n");
    sb.append("    destinationAdGroupId: ").append(toIndentedString(destinationAdGroupId)).append("\n");
    sb.append("    expressionType: ").append(toIndentedString(expressionType)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
    sb.append("    targetPromotionGroupId: ").append(toIndentedString(targetPromotionGroupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("destinationAdGroupId");
    openapiFields.add("expressionType");
    openapiFields.add("target");
    openapiFields.add("targetId");
    openapiFields.add("targetPromotionGroupId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SponsoredProductsProductTargetV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SponsoredProductsProductTargetV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SponsoredProductsProductTargetV2 is not found in the empty JSON string", SponsoredProductsProductTargetV2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SponsoredProductsProductTargetV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SponsoredProductsProductTargetV2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("destinationAdGroupId") != null && !jsonObj.get("destinationAdGroupId").isJsonNull()) && !jsonObj.get("destinationAdGroupId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinationAdGroupId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinationAdGroupId").toString()));
      }
      if ((jsonObj.get("expressionType") != null && !jsonObj.get("expressionType").isJsonNull()) && !jsonObj.get("expressionType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expressionType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expressionType").toString()));
      }
      if ((jsonObj.get("target") != null && !jsonObj.get("target").isJsonNull()) && !jsonObj.get("target").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `target` to be a primitive type in the JSON string but got `%s`", jsonObj.get("target").toString()));
      }
      if ((jsonObj.get("targetId") != null && !jsonObj.get("targetId").isJsonNull()) && !jsonObj.get("targetId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetId").toString()));
      }
      if ((jsonObj.get("targetPromotionGroupId") != null && !jsonObj.get("targetPromotionGroupId").isJsonNull()) && !jsonObj.get("targetPromotionGroupId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetPromotionGroupId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetPromotionGroupId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SponsoredProductsProductTargetV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SponsoredProductsProductTargetV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SponsoredProductsProductTargetV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SponsoredProductsProductTargetV2.class));

       return (TypeAdapter<T>) new TypeAdapter<SponsoredProductsProductTargetV2>() {
           @Override
           public void write(JsonWriter out, SponsoredProductsProductTargetV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SponsoredProductsProductTargetV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SponsoredProductsProductTargetV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SponsoredProductsProductTargetV2
   * @throws IOException if the JSON string is invalid with respect to SponsoredProductsProductTargetV2
   */
  public static SponsoredProductsProductTargetV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SponsoredProductsProductTargetV2.class);
  }

  /**
   * Convert an instance of SponsoredProductsProductTargetV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

