/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent {
  public static final String SERIALIZED_NAME_NEGATIVE_TARGET_ID_FILTER = "negativeTargetIdFilter";
  @SerializedName(SERIALIZED_NAME_NEGATIVE_TARGET_ID_FILTER)
  @javax.annotation.Nonnull
  private SponsoredProductsObjectIdFilter negativeTargetIdFilter;

  public SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent() {
  }

  public SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent negativeTargetIdFilter(@javax.annotation.Nonnull SponsoredProductsObjectIdFilter negativeTargetIdFilter) {
    this.negativeTargetIdFilter = negativeTargetIdFilter;
    return this;
  }

  /**
   * Get negativeTargetIdFilter
   * @return negativeTargetIdFilter
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  public SponsoredProductsObjectIdFilter getNegativeTargetIdFilter() {
    return negativeTargetIdFilter;
  }

  public void setNegativeTargetIdFilter(@javax.annotation.Nonnull SponsoredProductsObjectIdFilter negativeTargetIdFilter) {
    this.negativeTargetIdFilter = negativeTargetIdFilter;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent sponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent = (SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent) o;
    return Objects.equals(this.negativeTargetIdFilter, sponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent.negativeTargetIdFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(negativeTargetIdFilter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent {\n");
    sb.append("    negativeTargetIdFilter: ").append(toIndentedString(negativeTargetIdFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("negativeTargetIdFilter");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("negativeTargetIdFilter");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent is not found in the empty JSON string", SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `negativeTargetIdFilter`
      SponsoredProductsObjectIdFilter.validateJsonElement(jsonObj.get("negativeTargetIdFilter"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent.class));

       return (TypeAdapter<T>) new TypeAdapter<SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent>() {
           @Override
           public void write(JsonWriter out, SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent
   * @throws IOException if the JSON string is invalid with respect to SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent
   */
  public static SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent.class);
  }

  /**
   * Convert an instance of SponsoredProductsDeleteSponsoredProductsNegativeTargetingClausesRequestContent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

