/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.IOException;
import java.util.*;

/**
 * SponsoredProductsCreateSponsoredProductsCampaignsRequestContent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class SponsoredProductsCreateSponsoredProductsCampaignsRequestContent {
  public static final String SERIALIZED_NAME_CAMPAIGNS = "campaigns";
  @SerializedName(SERIALIZED_NAME_CAMPAIGNS)
  @javax.annotation.Nonnull
  private List<@Valid SponsoredProductsCreateCampaign> campaigns = new ArrayList<>();

  public SponsoredProductsCreateSponsoredProductsCampaignsRequestContent() {
  }

  public SponsoredProductsCreateSponsoredProductsCampaignsRequestContent campaigns(@javax.annotation.Nonnull List<@Valid SponsoredProductsCreateCampaign> campaigns) {
    this.campaigns = campaigns;
    return this;
  }

  public SponsoredProductsCreateSponsoredProductsCampaignsRequestContent addCampaignsItem(SponsoredProductsCreateCampaign campaignsItem) {
    if (this.campaigns == null) {
      this.campaigns = new ArrayList<>();
    }
    this.campaigns.add(campaignsItem);
    return this;
  }

  /**
   * An array of campaigns.
   * @return campaigns
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid
 @Size(min=0,max=1000)
  public List<@Valid SponsoredProductsCreateCampaign> getCampaigns() {
    return campaigns;
  }

  public void setCampaigns(@javax.annotation.Nonnull List<@Valid SponsoredProductsCreateCampaign> campaigns) {
    this.campaigns = campaigns;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SponsoredProductsCreateSponsoredProductsCampaignsRequestContent sponsoredProductsCreateSponsoredProductsCampaignsRequestContent = (SponsoredProductsCreateSponsoredProductsCampaignsRequestContent) o;
    return Objects.equals(this.campaigns, sponsoredProductsCreateSponsoredProductsCampaignsRequestContent.campaigns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaigns);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SponsoredProductsCreateSponsoredProductsCampaignsRequestContent {\n");
    sb.append("    campaigns: ").append(toIndentedString(campaigns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("campaigns");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("campaigns");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SponsoredProductsCreateSponsoredProductsCampaignsRequestContent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SponsoredProductsCreateSponsoredProductsCampaignsRequestContent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SponsoredProductsCreateSponsoredProductsCampaignsRequestContent is not found in the empty JSON string", SponsoredProductsCreateSponsoredProductsCampaignsRequestContent.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SponsoredProductsCreateSponsoredProductsCampaignsRequestContent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SponsoredProductsCreateSponsoredProductsCampaignsRequestContent` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SponsoredProductsCreateSponsoredProductsCampaignsRequestContent.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("campaigns").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `campaigns` to be an array in the JSON string but got `%s`", jsonObj.get("campaigns").toString()));
      }

      JsonArray jsonArraycampaigns = jsonObj.getAsJsonArray("campaigns");
      // validate the required field `campaigns` (array)
      for (int i = 0; i < jsonArraycampaigns.size(); i++) {
        SponsoredProductsCreateCampaign.validateJsonElement(jsonArraycampaigns.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SponsoredProductsCreateSponsoredProductsCampaignsRequestContent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SponsoredProductsCreateSponsoredProductsCampaignsRequestContent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SponsoredProductsCreateSponsoredProductsCampaignsRequestContent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SponsoredProductsCreateSponsoredProductsCampaignsRequestContent.class));

       return (TypeAdapter<T>) new TypeAdapter<SponsoredProductsCreateSponsoredProductsCampaignsRequestContent>() {
           @Override
           public void write(JsonWriter out, SponsoredProductsCreateSponsoredProductsCampaignsRequestContent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SponsoredProductsCreateSponsoredProductsCampaignsRequestContent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SponsoredProductsCreateSponsoredProductsCampaignsRequestContent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SponsoredProductsCreateSponsoredProductsCampaignsRequestContent
   * @throws IOException if the JSON string is invalid with respect to SponsoredProductsCreateSponsoredProductsCampaignsRequestContent
   */
  public static SponsoredProductsCreateSponsoredProductsCampaignsRequestContent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SponsoredProductsCreateSponsoredProductsCampaignsRequestContent.class);
  }

  /**
   * Convert an instance of SponsoredProductsCreateSponsoredProductsCampaignsRequestContent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

