/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import java.io.IOException;
import java.util.*;

/**
 * SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent {
  public static final String SERIALIZED_NAME_AD_GROUP_ID_FILTER = "adGroupIdFilter";
  @SerializedName(SERIALIZED_NAME_AD_GROUP_ID_FILTER)
  @javax.annotation.Nullable
  private SponsoredProductsReducedObjectIdFilter adGroupIdFilter;

  public static final String SERIALIZED_NAME_CAMPAIGN_ID_FILTER = "campaignIdFilter";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_ID_FILTER)
  @javax.annotation.Nullable
  private SponsoredProductsReducedObjectIdFilter campaignIdFilter;

  public static final String SERIALIZED_NAME_INCLUDE_EXTENDED_DATA_FIELDS = "includeExtendedDataFields";
  @SerializedName(SERIALIZED_NAME_INCLUDE_EXTENDED_DATA_FIELDS)
  @javax.annotation.Nullable
  private Boolean includeExtendedDataFields;

  public static final String SERIALIZED_NAME_LOCALE = "locale";
  @SerializedName(SERIALIZED_NAME_LOCALE)
  @javax.annotation.Nullable
  private String locale;

  public static final String SERIALIZED_NAME_MATCH_TYPE_FILTER = "matchTypeFilter";
  @SerializedName(SERIALIZED_NAME_MATCH_TYPE_FILTER)
  @javax.annotation.Nullable
  private List<SponsoredProductsNegativeMatchType> matchTypeFilter = new ArrayList<>();

  public static final String SERIALIZED_NAME_MAX_RESULTS = "maxResults";
  @SerializedName(SERIALIZED_NAME_MAX_RESULTS)
  @javax.annotation.Nullable
  private Integer maxResults;

  public static final String SERIALIZED_NAME_NEGATIVE_KEYWORD_ID_FILTER = "negativeKeywordIdFilter";
  @SerializedName(SERIALIZED_NAME_NEGATIVE_KEYWORD_ID_FILTER)
  @javax.annotation.Nullable
  private SponsoredProductsObjectIdFilter negativeKeywordIdFilter;

  public static final String SERIALIZED_NAME_NEGATIVE_KEYWORD_TEXT_FILTER = "negativeKeywordTextFilter";
  @SerializedName(SERIALIZED_NAME_NEGATIVE_KEYWORD_TEXT_FILTER)
  @javax.annotation.Nullable
  private SponsoredProductsKeywordTextFilter negativeKeywordTextFilter;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "nextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public static final String SERIALIZED_NAME_STATE_FILTER = "stateFilter";
  @SerializedName(SERIALIZED_NAME_STATE_FILTER)
  @javax.annotation.Nullable
  private SponsoredProductsEntityStateFilter stateFilter;

  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent() {
  }

  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent adGroupIdFilter(@javax.annotation.Nullable SponsoredProductsReducedObjectIdFilter adGroupIdFilter) {
    this.adGroupIdFilter = adGroupIdFilter;
    return this;
  }

  /**
   * Get adGroupIdFilter
   * @return adGroupIdFilter
   */
  @javax.annotation.Nullable
  @Valid

  public SponsoredProductsReducedObjectIdFilter getAdGroupIdFilter() {
    return adGroupIdFilter;
  }

  public void setAdGroupIdFilter(@javax.annotation.Nullable SponsoredProductsReducedObjectIdFilter adGroupIdFilter) {
    this.adGroupIdFilter = adGroupIdFilter;
  }


  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent campaignIdFilter(@javax.annotation.Nullable SponsoredProductsReducedObjectIdFilter campaignIdFilter) {
    this.campaignIdFilter = campaignIdFilter;
    return this;
  }

  /**
   * Get campaignIdFilter
   * @return campaignIdFilter
   */
  @javax.annotation.Nullable
  @Valid

  public SponsoredProductsReducedObjectIdFilter getCampaignIdFilter() {
    return campaignIdFilter;
  }

  public void setCampaignIdFilter(@javax.annotation.Nullable SponsoredProductsReducedObjectIdFilter campaignIdFilter) {
    this.campaignIdFilter = campaignIdFilter;
  }


  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent includeExtendedDataFields(@javax.annotation.Nullable Boolean includeExtendedDataFields) {
    this.includeExtendedDataFields = includeExtendedDataFields;
    return this;
  }

  /**
   * Whether to get entity with extended data fields such as creationDate, lastUpdateDate, servingStatus
   * @return includeExtendedDataFields
   */
  @javax.annotation.Nullable

  public Boolean getIncludeExtendedDataFields() {
    return includeExtendedDataFields;
  }

  public void setIncludeExtendedDataFields(@javax.annotation.Nullable Boolean includeExtendedDataFields) {
    this.includeExtendedDataFields = includeExtendedDataFields;
  }


  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent locale(@javax.annotation.Nullable String locale) {
    this.locale = locale;
    return this;
  }

  /**
   * Restricts results to negativeKeywords that match the specified locale.
   * @return locale
   */
  @javax.annotation.Nullable

  public String getLocale() {
    return locale;
  }

  public void setLocale(@javax.annotation.Nullable String locale) {
    this.locale = locale;
  }


  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent matchTypeFilter(@javax.annotation.Nullable List<SponsoredProductsNegativeMatchType> matchTypeFilter) {
    this.matchTypeFilter = matchTypeFilter;
    return this;
  }

  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent addMatchTypeFilterItem(SponsoredProductsNegativeMatchType matchTypeFilterItem) {
    if (this.matchTypeFilter == null) {
      this.matchTypeFilter = new ArrayList<>();
    }
    this.matchTypeFilter.add(matchTypeFilterItem);
    return this;
  }

  /**
   * Only the negativeKeyword with the match type that is in this list will be listed
   * @return matchTypeFilter
   */
  @javax.annotation.Nullable
  @Valid

  public List<SponsoredProductsNegativeMatchType> getMatchTypeFilter() {
    return matchTypeFilter;
  }

  public void setMatchTypeFilter(@javax.annotation.Nullable List<SponsoredProductsNegativeMatchType> matchTypeFilter) {
    this.matchTypeFilter = matchTypeFilter;
  }


  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent maxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
    return this;
  }

  /**
   * Number of records to include in the paginated response. Defaults to max page size for given API
   * @return maxResults
   */
  @javax.annotation.Nullable

  public Integer getMaxResults() {
    return maxResults;
  }

  public void setMaxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
  }


  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent negativeKeywordIdFilter(@javax.annotation.Nullable SponsoredProductsObjectIdFilter negativeKeywordIdFilter) {
    this.negativeKeywordIdFilter = negativeKeywordIdFilter;
    return this;
  }

  /**
   * Get negativeKeywordIdFilter
   * @return negativeKeywordIdFilter
   */
  @javax.annotation.Nullable
  @Valid

  public SponsoredProductsObjectIdFilter getNegativeKeywordIdFilter() {
    return negativeKeywordIdFilter;
  }

  public void setNegativeKeywordIdFilter(@javax.annotation.Nullable SponsoredProductsObjectIdFilter negativeKeywordIdFilter) {
    this.negativeKeywordIdFilter = negativeKeywordIdFilter;
  }


  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent negativeKeywordTextFilter(@javax.annotation.Nullable SponsoredProductsKeywordTextFilter negativeKeywordTextFilter) {
    this.negativeKeywordTextFilter = negativeKeywordTextFilter;
    return this;
  }

  /**
   * Get negativeKeywordTextFilter
   * @return negativeKeywordTextFilter
   */
  @javax.annotation.Nullable
  @Valid

  public SponsoredProductsKeywordTextFilter getNegativeKeywordTextFilter() {
    return negativeKeywordTextFilter;
  }

  public void setNegativeKeywordTextFilter(@javax.annotation.Nullable SponsoredProductsKeywordTextFilter negativeKeywordTextFilter) {
    this.negativeKeywordTextFilter = negativeKeywordTextFilter;
  }


  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * token value allowing to navigate to the next response page
   * @return nextToken
   */
  @javax.annotation.Nullable

  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }


  public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent stateFilter(@javax.annotation.Nullable SponsoredProductsEntityStateFilter stateFilter) {
    this.stateFilter = stateFilter;
    return this;
  }

  /**
   * Get stateFilter
   * @return stateFilter
   */
  @javax.annotation.Nullable
  @Valid

  public SponsoredProductsEntityStateFilter getStateFilter() {
    return stateFilter;
  }

  public void setStateFilter(@javax.annotation.Nullable SponsoredProductsEntityStateFilter stateFilter) {
    this.stateFilter = stateFilter;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent = (SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent) o;
    return Objects.equals(this.adGroupIdFilter, sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.adGroupIdFilter) &&
        Objects.equals(this.campaignIdFilter, sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.campaignIdFilter) &&
        Objects.equals(this.includeExtendedDataFields, sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.includeExtendedDataFields) &&
        Objects.equals(this.locale, sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.locale) &&
        Objects.equals(this.matchTypeFilter, sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.matchTypeFilter) &&
        Objects.equals(this.maxResults, sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.maxResults) &&
        Objects.equals(this.negativeKeywordIdFilter, sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.negativeKeywordIdFilter) &&
        Objects.equals(this.negativeKeywordTextFilter, sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.negativeKeywordTextFilter) &&
        Objects.equals(this.nextToken, sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.nextToken) &&
        Objects.equals(this.stateFilter, sponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.stateFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adGroupIdFilter, campaignIdFilter, includeExtendedDataFields, locale, matchTypeFilter, maxResults, negativeKeywordIdFilter, negativeKeywordTextFilter, nextToken, stateFilter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent {\n");
    sb.append("    adGroupIdFilter: ").append(toIndentedString(adGroupIdFilter)).append("\n");
    sb.append("    campaignIdFilter: ").append(toIndentedString(campaignIdFilter)).append("\n");
    sb.append("    includeExtendedDataFields: ").append(toIndentedString(includeExtendedDataFields)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    matchTypeFilter: ").append(toIndentedString(matchTypeFilter)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("    negativeKeywordIdFilter: ").append(toIndentedString(negativeKeywordIdFilter)).append("\n");
    sb.append("    negativeKeywordTextFilter: ").append(toIndentedString(negativeKeywordTextFilter)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    stateFilter: ").append(toIndentedString(stateFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("adGroupIdFilter");
    openapiFields.add("campaignIdFilter");
    openapiFields.add("includeExtendedDataFields");
    openapiFields.add("locale");
    openapiFields.add("matchTypeFilter");
    openapiFields.add("maxResults");
    openapiFields.add("negativeKeywordIdFilter");
    openapiFields.add("negativeKeywordTextFilter");
    openapiFields.add("nextToken");
    openapiFields.add("stateFilter");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent is not found in the empty JSON string", SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `adGroupIdFilter`
      if (jsonObj.get("adGroupIdFilter") != null && !jsonObj.get("adGroupIdFilter").isJsonNull()) {
        SponsoredProductsReducedObjectIdFilter.validateJsonElement(jsonObj.get("adGroupIdFilter"));
      }
      // validate the optional field `campaignIdFilter`
      if (jsonObj.get("campaignIdFilter") != null && !jsonObj.get("campaignIdFilter").isJsonNull()) {
        SponsoredProductsReducedObjectIdFilter.validateJsonElement(jsonObj.get("campaignIdFilter"));
      }
      if ((jsonObj.get("locale") != null && !jsonObj.get("locale").isJsonNull()) && !jsonObj.get("locale").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `locale` to be a primitive type in the JSON string but got `%s`", jsonObj.get("locale").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("matchTypeFilter") != null && !jsonObj.get("matchTypeFilter").isJsonNull() && !jsonObj.get("matchTypeFilter").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `matchTypeFilter` to be an array in the JSON string but got `%s`", jsonObj.get("matchTypeFilter").toString()));
      }
      // validate the optional field `negativeKeywordIdFilter`
      if (jsonObj.get("negativeKeywordIdFilter") != null && !jsonObj.get("negativeKeywordIdFilter").isJsonNull()) {
        SponsoredProductsObjectIdFilter.validateJsonElement(jsonObj.get("negativeKeywordIdFilter"));
      }
      // validate the optional field `negativeKeywordTextFilter`
      if (jsonObj.get("negativeKeywordTextFilter") != null && !jsonObj.get("negativeKeywordTextFilter").isJsonNull()) {
        SponsoredProductsKeywordTextFilter.validateJsonElement(jsonObj.get("negativeKeywordTextFilter"));
      }
      if ((jsonObj.get("nextToken") != null && !jsonObj.get("nextToken").isJsonNull()) && !jsonObj.get("nextToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nextToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextToken").toString()));
      }
      // validate the optional field `stateFilter`
      if (jsonObj.get("stateFilter") != null && !jsonObj.get("stateFilter").isJsonNull()) {
        SponsoredProductsEntityStateFilter.validateJsonElement(jsonObj.get("stateFilter"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.class));

       return (TypeAdapter<T>) new TypeAdapter<SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent>() {
           @Override
           public void write(JsonWriter out, SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent
   * @throws IOException if the JSON string is invalid with respect to SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent
   */
  public static SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent.class);
  }

  /**
   * Convert an instance of SponsoredProductsListSponsoredProductsNegativeKeywordsRequestContent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

