/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.model.spv3;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.chenyilei2016.adv.JSON;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-25T11:08:58.036830+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent {
  public static final String SERIALIZED_NAME_CAMPAIGN_NEGATIVE_KEYWORDS = "campaignNegativeKeywords";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_NEGATIVE_KEYWORDS)
  @javax.annotation.Nonnull
  private SponsoredProductsBulkCampaignNegativeKeywordOperationResponse campaignNegativeKeywords;

  public SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent() {
  }

  public SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent campaignNegativeKeywords(@javax.annotation.Nonnull SponsoredProductsBulkCampaignNegativeKeywordOperationResponse campaignNegativeKeywords) {
    this.campaignNegativeKeywords = campaignNegativeKeywords;
    return this;
  }

  /**
   * Get campaignNegativeKeywords
   * @return campaignNegativeKeywords
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  public SponsoredProductsBulkCampaignNegativeKeywordOperationResponse getCampaignNegativeKeywords() {
    return campaignNegativeKeywords;
  }

  public void setCampaignNegativeKeywords(@javax.annotation.Nonnull SponsoredProductsBulkCampaignNegativeKeywordOperationResponse campaignNegativeKeywords) {
    this.campaignNegativeKeywords = campaignNegativeKeywords;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent sponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent = (SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent) o;
    return Objects.equals(this.campaignNegativeKeywords, sponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent.campaignNegativeKeywords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignNegativeKeywords);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent {\n");
    sb.append("    campaignNegativeKeywords: ").append(toIndentedString(campaignNegativeKeywords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("campaignNegativeKeywords");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("campaignNegativeKeywords");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent is not found in the empty JSON string", SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `campaignNegativeKeywords`
      SponsoredProductsBulkCampaignNegativeKeywordOperationResponse.validateJsonElement(jsonObj.get("campaignNegativeKeywords"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent.class));

       return (TypeAdapter<T>) new TypeAdapter<SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent>() {
           @Override
           public void write(JsonWriter out, SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent
   * @throws IOException if the JSON string is invalid with respect to SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent
   */
  public static SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent.class);
  }

  /**
   * Convert an instance of SponsoredProductsUpdateSponsoredProductsCampaignNegativeKeywordsResponseContent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

