/*
 * Sponsored Products
 *  
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.adv.api.spv3;

import com.google.gson.reflect.TypeToken;
import io.github.chenyilei2016.adv.*;
import io.github.chenyilei2016.adv.model.spv3.*;

import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.ValidatorFactory;
import javax.validation.constraints.NotNull;
import javax.validation.executable.ExecutableValidator;
import java.lang.reflect.Method;
import java.lang.reflect.Type;
import java.util.*;

public class ProductAdsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ProductAdsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ProductAdsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createSponsoredProductsProductAds
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsCreateSponsoredProductsProductAdsRequestContent  (required)
     * @param prefer The \&quot;Prefer\&quot; header, as defined in [RFC7240], allows clients to request certain behavior from the service. The service ignores preference values that are either not supported or not known by the service. Either multiple Prefer headers are passed or single one with comma separated values, both forms are equivalent Supported preferences: return&#x3D;representation - return the full object when doing create/update/delete operations instead of ids. Please note that the extendedData field will be part of the full object for /list endpoints only. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> CreateSponsoredProductsProductAds 207 response </td><td>  * Preference-Applied - Header containing preferences applied while processing API call <br>  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createSponsoredProductsProductAdsCall(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsCreateSponsoredProductsProductAdsRequestContent sponsoredProductsCreateSponsoredProductsProductAdsRequestContent, String prefer, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = sponsoredProductsCreateSponsoredProductsProductAdsRequestContent;

        // create path and map variables
        String localVarPath = "/sp/productAds";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/vnd.spProductAd.v3+json",
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/vnd.spProductAd.v3+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (amazonAdvertisingAPIClientId != null) {
            localVarHeaderParams.put("Amazon-Advertising-API-ClientId", localVarApiClient.parameterToString(amazonAdvertisingAPIClientId));
        }


        if (amazonAdvertisingAPIScope != null) {
            localVarHeaderParams.put("Amazon-Advertising-API-Scope", localVarApiClient.parameterToString(amazonAdvertisingAPIScope));
        }


        if (prefer != null) {
            localVarHeaderParams.put("Prefer", localVarApiClient.parameterToString(prefer));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createSponsoredProductsProductAdsValidateBeforeCall(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsCreateSponsoredProductsProductAdsRequestContent sponsoredProductsCreateSponsoredProductsProductAdsRequestContent, String prefer, final ApiCallback _callback) throws ApiException {
        try {
            ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
            ExecutableValidator executableValidator = factory.getValidator().forExecutables();

            Object[] parameterValues = { amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsCreateSponsoredProductsProductAdsRequestContent, prefer };
            Method method = this.getClass().getMethod("createSponsoredProductsProductAdsWithHttpInfo", String.class, String.class, SponsoredProductsCreateSponsoredProductsProductAdsRequestContent.class, String.class);
            Set<ConstraintViolation<ProductAdsApi>> violations = executableValidator.validateParameters(this, method,
                    parameterValues);

            if (violations.size() == 0) {
                return createSponsoredProductsProductAdsCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsCreateSponsoredProductsProductAdsRequestContent, prefer, _callback);
            } else {
                throw new BeanValidationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    /**
     * 
     * Create product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;campaign_proposed\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsCreateSponsoredProductsProductAdsRequestContent  (required)
     * @param prefer The \&quot;Prefer\&quot; header, as defined in [RFC7240], allows clients to request certain behavior from the service. The service ignores preference values that are either not supported or not known by the service. Either multiple Prefer headers are passed or single one with comma separated values, both forms are equivalent Supported preferences: return&#x3D;representation - return the full object when doing create/update/delete operations instead of ids. Please note that the extendedData field will be part of the full object for /list endpoints only. (optional)
     * @return SponsoredProductsCreateSponsoredProductsProductAdsResponseContent
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> CreateSponsoredProductsProductAds 207 response </td><td>  * Preference-Applied - Header containing preferences applied while processing API call <br>  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public SponsoredProductsCreateSponsoredProductsProductAdsResponseContent createSponsoredProductsProductAds(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsCreateSponsoredProductsProductAdsRequestContent sponsoredProductsCreateSponsoredProductsProductAdsRequestContent, String prefer) throws ApiException {
        ApiResponse<SponsoredProductsCreateSponsoredProductsProductAdsResponseContent> localVarResp = createSponsoredProductsProductAdsWithHttpInfo(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsCreateSponsoredProductsProductAdsRequestContent, prefer);
        return localVarResp.getData();
    }

    /**
     * 
     * Create product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;campaign_proposed\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsCreateSponsoredProductsProductAdsRequestContent  (required)
     * @param prefer The \&quot;Prefer\&quot; header, as defined in [RFC7240], allows clients to request certain behavior from the service. The service ignores preference values that are either not supported or not known by the service. Either multiple Prefer headers are passed or single one with comma separated values, both forms are equivalent Supported preferences: return&#x3D;representation - return the full object when doing create/update/delete operations instead of ids. Please note that the extendedData field will be part of the full object for /list endpoints only. (optional)
     * @return ApiResponse&lt;SponsoredProductsCreateSponsoredProductsProductAdsResponseContent&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> CreateSponsoredProductsProductAds 207 response </td><td>  * Preference-Applied - Header containing preferences applied while processing API call <br>  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SponsoredProductsCreateSponsoredProductsProductAdsResponseContent> createSponsoredProductsProductAdsWithHttpInfo( @NotNull String amazonAdvertisingAPIClientId,  @NotNull String amazonAdvertisingAPIScope,  @NotNull SponsoredProductsCreateSponsoredProductsProductAdsRequestContent sponsoredProductsCreateSponsoredProductsProductAdsRequestContent, String prefer) throws ApiException {
        okhttp3.Call localVarCall = createSponsoredProductsProductAdsValidateBeforeCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsCreateSponsoredProductsProductAdsRequestContent, prefer, null);
        Type localVarReturnType = new TypeToken<SponsoredProductsCreateSponsoredProductsProductAdsResponseContent>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Create product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;campaign_proposed\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsCreateSponsoredProductsProductAdsRequestContent  (required)
     * @param prefer The \&quot;Prefer\&quot; header, as defined in [RFC7240], allows clients to request certain behavior from the service. The service ignores preference values that are either not supported or not known by the service. Either multiple Prefer headers are passed or single one with comma separated values, both forms are equivalent Supported preferences: return&#x3D;representation - return the full object when doing create/update/delete operations instead of ids. Please note that the extendedData field will be part of the full object for /list endpoints only. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> CreateSponsoredProductsProductAds 207 response </td><td>  * Preference-Applied - Header containing preferences applied while processing API call <br>  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createSponsoredProductsProductAdsAsync(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsCreateSponsoredProductsProductAdsRequestContent sponsoredProductsCreateSponsoredProductsProductAdsRequestContent, String prefer, final ApiCallback<SponsoredProductsCreateSponsoredProductsProductAdsResponseContent> _callback) throws ApiException {

        okhttp3.Call localVarCall = createSponsoredProductsProductAdsValidateBeforeCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsCreateSponsoredProductsProductAdsRequestContent, prefer, _callback);
        Type localVarReturnType = new TypeToken<SponsoredProductsCreateSponsoredProductsProductAdsResponseContent>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteSponsoredProductsProductAds
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> DeleteSponsoredProductsProductAds 207 response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteSponsoredProductsProductAdsCall(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsDeleteSponsoredProductsProductAdsRequestContent sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent;

        // create path and map variables
        String localVarPath = "/sp/productAds/delete";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/vnd.spProductAd.v3+json",
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/vnd.spProductAd.v3+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (amazonAdvertisingAPIClientId != null) {
            localVarHeaderParams.put("Amazon-Advertising-API-ClientId", localVarApiClient.parameterToString(amazonAdvertisingAPIClientId));
        }


        if (amazonAdvertisingAPIScope != null) {
            localVarHeaderParams.put("Amazon-Advertising-API-Scope", localVarApiClient.parameterToString(amazonAdvertisingAPIScope));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteSponsoredProductsProductAdsValidateBeforeCall(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsDeleteSponsoredProductsProductAdsRequestContent sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent, final ApiCallback _callback) throws ApiException {
        try {
            ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
            ExecutableValidator executableValidator = factory.getValidator().forExecutables();

            Object[] parameterValues = { amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent };
            Method method = this.getClass().getMethod("deleteSponsoredProductsProductAdsWithHttpInfo", String.class, String.class, SponsoredProductsDeleteSponsoredProductsProductAdsRequestContent.class);
            Set<ConstraintViolation<ProductAdsApi>> violations = executableValidator.validateParameters(this, method,
                    parameterValues);

            if (violations.size() == 0) {
                return deleteSponsoredProductsProductAdsCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent, _callback);
            } else {
                throw new BeanValidationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    /**
     * 
     * Delete product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;campaign_proposed\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent  (required)
     * @return SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> DeleteSponsoredProductsProductAds 207 response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent deleteSponsoredProductsProductAds(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsDeleteSponsoredProductsProductAdsRequestContent sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent) throws ApiException {
        ApiResponse<SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent> localVarResp = deleteSponsoredProductsProductAdsWithHttpInfo(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent);
        return localVarResp.getData();
    }

    /**
     * 
     * Delete product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;campaign_proposed\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent  (required)
     * @return ApiResponse&lt;SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> DeleteSponsoredProductsProductAds 207 response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent> deleteSponsoredProductsProductAdsWithHttpInfo( @NotNull String amazonAdvertisingAPIClientId,  @NotNull String amazonAdvertisingAPIScope,  @NotNull SponsoredProductsDeleteSponsoredProductsProductAdsRequestContent sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent) throws ApiException {
        okhttp3.Call localVarCall = deleteSponsoredProductsProductAdsValidateBeforeCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent, null);
        Type localVarReturnType = new TypeToken<SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Delete product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;campaign_proposed\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> DeleteSponsoredProductsProductAds 207 response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteSponsoredProductsProductAdsAsync(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsDeleteSponsoredProductsProductAdsRequestContent sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent, final ApiCallback<SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteSponsoredProductsProductAdsValidateBeforeCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsDeleteSponsoredProductsProductAdsRequestContent, _callback);
        Type localVarReturnType = new TypeToken<SponsoredProductsDeleteSponsoredProductsProductAdsResponseContent>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listSponsoredProductsProductAds
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsListSponsoredProductsProductAdsRequestContent  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ListSponsoredProductsProductAds 200 response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ProductAdAccessException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listSponsoredProductsProductAdsCall(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsListSponsoredProductsProductAdsRequestContent sponsoredProductsListSponsoredProductsProductAdsRequestContent, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = sponsoredProductsListSponsoredProductsProductAdsRequestContent;

        // create path and map variables
        String localVarPath = "/sp/productAds/list";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/vnd.spProductAd.v3+json",
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/vnd.spProductAd.v3+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (amazonAdvertisingAPIClientId != null) {
            localVarHeaderParams.put("Amazon-Advertising-API-ClientId", localVarApiClient.parameterToString(amazonAdvertisingAPIClientId));
        }


        if (amazonAdvertisingAPIScope != null) {
            localVarHeaderParams.put("Amazon-Advertising-API-Scope", localVarApiClient.parameterToString(amazonAdvertisingAPIScope));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listSponsoredProductsProductAdsValidateBeforeCall(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsListSponsoredProductsProductAdsRequestContent sponsoredProductsListSponsoredProductsProductAdsRequestContent, final ApiCallback _callback) throws ApiException {
        try {
            ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
            ExecutableValidator executableValidator = factory.getValidator().forExecutables();

            Object[] parameterValues = { amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsListSponsoredProductsProductAdsRequestContent };
            Method method = this.getClass().getMethod("listSponsoredProductsProductAdsWithHttpInfo", String.class, String.class, SponsoredProductsListSponsoredProductsProductAdsRequestContent.class);
            Set<ConstraintViolation<ProductAdsApi>> violations = executableValidator.validateParameters(this, method,
                    parameterValues);

            if (violations.size() == 0) {
                return listSponsoredProductsProductAdsCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsListSponsoredProductsProductAdsRequestContent, _callback);
            } else {
                throw new BeanValidationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    /**
     * 
     * List product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;advertiser_campaign_view\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsListSponsoredProductsProductAdsRequestContent  (optional)
     * @return SponsoredProductsListSponsoredProductsProductAdsResponseContent
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ListSponsoredProductsProductAds 200 response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ProductAdAccessException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public SponsoredProductsListSponsoredProductsProductAdsResponseContent listSponsoredProductsProductAds(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsListSponsoredProductsProductAdsRequestContent sponsoredProductsListSponsoredProductsProductAdsRequestContent) throws ApiException {
        ApiResponse<SponsoredProductsListSponsoredProductsProductAdsResponseContent> localVarResp = listSponsoredProductsProductAdsWithHttpInfo(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsListSponsoredProductsProductAdsRequestContent);
        return localVarResp.getData();
    }

    /**
     * 
     * List product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;advertiser_campaign_view\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsListSponsoredProductsProductAdsRequestContent  (optional)
     * @return ApiResponse&lt;SponsoredProductsListSponsoredProductsProductAdsResponseContent&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ListSponsoredProductsProductAds 200 response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ProductAdAccessException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SponsoredProductsListSponsoredProductsProductAdsResponseContent> listSponsoredProductsProductAdsWithHttpInfo( @NotNull String amazonAdvertisingAPIClientId,  @NotNull String amazonAdvertisingAPIScope, SponsoredProductsListSponsoredProductsProductAdsRequestContent sponsoredProductsListSponsoredProductsProductAdsRequestContent) throws ApiException {
        okhttp3.Call localVarCall = listSponsoredProductsProductAdsValidateBeforeCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsListSponsoredProductsProductAdsRequestContent, null);
        Type localVarReturnType = new TypeToken<SponsoredProductsListSponsoredProductsProductAdsResponseContent>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * List product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;advertiser_campaign_view\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsListSponsoredProductsProductAdsRequestContent  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ListSponsoredProductsProductAds 200 response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ProductAdAccessException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listSponsoredProductsProductAdsAsync(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsListSponsoredProductsProductAdsRequestContent sponsoredProductsListSponsoredProductsProductAdsRequestContent, final ApiCallback<SponsoredProductsListSponsoredProductsProductAdsResponseContent> _callback) throws ApiException {

        okhttp3.Call localVarCall = listSponsoredProductsProductAdsValidateBeforeCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsListSponsoredProductsProductAdsRequestContent, _callback);
        Type localVarReturnType = new TypeToken<SponsoredProductsListSponsoredProductsProductAdsResponseContent>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateSponsoredProductsProductAds
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent  (required)
     * @param prefer The \&quot;Prefer\&quot; header, as defined in [RFC7240], allows clients to request certain behavior from the service. The service ignores preference values that are either not supported or not known by the service. Either multiple Prefer headers are passed or single one with comma separated values, both forms are equivalent Supported preferences: return&#x3D;representation - return the full object when doing create/update/delete operations instead of ids. Please note that the extendedData field will be part of the full object for /list endpoints only. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> UpdateSponsoredProductsProductAds 207 response </td><td>  * Preference-Applied - Header containing preferences applied while processing API call <br>  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateSponsoredProductsProductAdsCall(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsUpdateSponsoredProductsProductAdsRequestContent sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent, String prefer, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent;

        // create path and map variables
        String localVarPath = "/sp/productAds";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/vnd.spProductAd.v3+json",
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/vnd.spProductAd.v3+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (amazonAdvertisingAPIClientId != null) {
            localVarHeaderParams.put("Amazon-Advertising-API-ClientId", localVarApiClient.parameterToString(amazonAdvertisingAPIClientId));
        }


        if (amazonAdvertisingAPIScope != null) {
            localVarHeaderParams.put("Amazon-Advertising-API-Scope", localVarApiClient.parameterToString(amazonAdvertisingAPIScope));
        }


        if (prefer != null) {
            localVarHeaderParams.put("Prefer", localVarApiClient.parameterToString(prefer));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateSponsoredProductsProductAdsValidateBeforeCall(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsUpdateSponsoredProductsProductAdsRequestContent sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent, String prefer, final ApiCallback _callback) throws ApiException {
        try {
            ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
            ExecutableValidator executableValidator = factory.getValidator().forExecutables();

            Object[] parameterValues = { amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent, prefer };
            Method method = this.getClass().getMethod("updateSponsoredProductsProductAdsWithHttpInfo", String.class, String.class, SponsoredProductsUpdateSponsoredProductsProductAdsRequestContent.class, String.class);
            Set<ConstraintViolation<ProductAdsApi>> violations = executableValidator.validateParameters(this, method,
                    parameterValues);

            if (violations.size() == 0) {
                return updateSponsoredProductsProductAdsCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent, prefer, _callback);
            } else {
                throw new BeanValidationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    /**
     * 
     * Update product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;campaign_proposed\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent  (required)
     * @param prefer The \&quot;Prefer\&quot; header, as defined in [RFC7240], allows clients to request certain behavior from the service. The service ignores preference values that are either not supported or not known by the service. Either multiple Prefer headers are passed or single one with comma separated values, both forms are equivalent Supported preferences: return&#x3D;representation - return the full object when doing create/update/delete operations instead of ids. Please note that the extendedData field will be part of the full object for /list endpoints only. (optional)
     * @return SponsoredProductsUpdateSponsoredProductsProductAdsResponseContent
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> UpdateSponsoredProductsProductAds 207 response </td><td>  * Preference-Applied - Header containing preferences applied while processing API call <br>  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public SponsoredProductsUpdateSponsoredProductsProductAdsResponseContent updateSponsoredProductsProductAds(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsUpdateSponsoredProductsProductAdsRequestContent sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent, String prefer) throws ApiException {
        ApiResponse<SponsoredProductsUpdateSponsoredProductsProductAdsResponseContent> localVarResp = updateSponsoredProductsProductAdsWithHttpInfo(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent, prefer);
        return localVarResp.getData();
    }

    /**
     * 
     * Update product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;campaign_proposed\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent  (required)
     * @param prefer The \&quot;Prefer\&quot; header, as defined in [RFC7240], allows clients to request certain behavior from the service. The service ignores preference values that are either not supported or not known by the service. Either multiple Prefer headers are passed or single one with comma separated values, both forms are equivalent Supported preferences: return&#x3D;representation - return the full object when doing create/update/delete operations instead of ids. Please note that the extendedData field will be part of the full object for /list endpoints only. (optional)
     * @return ApiResponse&lt;SponsoredProductsUpdateSponsoredProductsProductAdsResponseContent&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> UpdateSponsoredProductsProductAds 207 response </td><td>  * Preference-Applied - Header containing preferences applied while processing API call <br>  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SponsoredProductsUpdateSponsoredProductsProductAdsResponseContent> updateSponsoredProductsProductAdsWithHttpInfo( @NotNull String amazonAdvertisingAPIClientId,  @NotNull String amazonAdvertisingAPIScope,  @NotNull SponsoredProductsUpdateSponsoredProductsProductAdsRequestContent sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent, String prefer) throws ApiException {
        okhttp3.Call localVarCall = updateSponsoredProductsProductAdsValidateBeforeCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent, prefer, null);
        Type localVarReturnType = new TypeToken<SponsoredProductsUpdateSponsoredProductsProductAdsResponseContent>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Update product ads  **Requires one of these permissions**: [\&quot;advertiser_campaign_edit\&quot;,\&quot;campaign_proposed\&quot;]
     * @param amazonAdvertisingAPIClientId The identifier of a client associated with a \&quot;Login with Amazon\&quot; account. (required)
     * @param amazonAdvertisingAPIScope The identifier of a profile associated with the advertiser account. Use GET method on Profiles resource to list profiles associated with the access token passed in the HTTP Authorization header. (required)
     * @param sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent  (required)
     * @param prefer The \&quot;Prefer\&quot; header, as defined in [RFC7240], allows clients to request certain behavior from the service. The service ignores preference values that are either not supported or not known by the service. Either multiple Prefer headers are passed or single one with comma separated values, both forms are equivalent Supported preferences: return&#x3D;representation - return the full object when doing create/update/delete operations instead of ids. Please note that the extendedData field will be part of the full object for /list endpoints only. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 207 </td><td> UpdateSponsoredProductsProductAds 207 response </td><td>  * Preference-Applied - Header containing preferences applied while processing API call <br>  </td></tr>
        <tr><td> 400 </td><td> ProductAdMutationException 400 response </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UnauthorizedException 401 response </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> AccessDeniedException 403 response </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> UnsupportedMediaTypeException 415 response </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> ThrottlingException 429 response </td><td>  * Retry-After - Delay in seconds, before the next re-try attempt to the operation is recommended <br>  </td></tr>
        <tr><td> 500 </td><td> InternalServerException 500 response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateSponsoredProductsProductAdsAsync(String amazonAdvertisingAPIClientId, String amazonAdvertisingAPIScope, SponsoredProductsUpdateSponsoredProductsProductAdsRequestContent sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent, String prefer, final ApiCallback<SponsoredProductsUpdateSponsoredProductsProductAdsResponseContent> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateSponsoredProductsProductAdsValidateBeforeCall(amazonAdvertisingAPIClientId, amazonAdvertisingAPIScope, sponsoredProductsUpdateSponsoredProductsProductAdsRequestContent, prefer, _callback);
        Type localVarReturnType = new TypeToken<SponsoredProductsUpdateSponsoredProductsProductAdsResponseContent>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
