/*
 * Amazon Ads Targets API
 * Focused Java SDK specification containing only Targets operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.targets.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.ContentRating;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.ContentRatingTypes;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


import io.github.chenyilei2016.amazonads.client.ApiClient;
/**
 * Target based on the rating of content being viewed.
 */
@JsonPropertyOrder({
  ContentRatingTarget.JSON_PROPERTY_CONTENT_RATING_TYPE,
  ContentRatingTarget.JSON_PROPERTY_CONTENT_RATING_TYPE_DETAILS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ContentRatingTarget {
  public static final String JSON_PROPERTY_CONTENT_RATING_TYPE = "contentRatingType";
  @jakarta.annotation.Nonnull
  private ContentRatingTypes contentRatingType;

  public static final String JSON_PROPERTY_CONTENT_RATING_TYPE_DETAILS = "contentRatingTypeDetails";
  @jakarta.annotation.Nonnull
  private ContentRating contentRatingTypeDetails;

  public ContentRatingTarget() {
  }

  public ContentRatingTarget contentRatingType(@jakarta.annotation.Nonnull ContentRatingTypes contentRatingType) {
    this.contentRatingType = contentRatingType;
    return this;
  }

  /**
   * Get contentRatingType
   * @return contentRatingType
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONTENT_RATING_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ContentRatingTypes getContentRatingType() {
    return contentRatingType;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_RATING_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContentRatingType(@jakarta.annotation.Nonnull ContentRatingTypes contentRatingType) {
    this.contentRatingType = contentRatingType;
  }


  public ContentRatingTarget contentRatingTypeDetails(@jakarta.annotation.Nonnull ContentRating contentRatingTypeDetails) {
    this.contentRatingTypeDetails = contentRatingTypeDetails;
    return this;
  }

  /**
   * Get contentRatingTypeDetails
   * @return contentRatingTypeDetails
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONTENT_RATING_TYPE_DETAILS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ContentRating getContentRatingTypeDetails() {
    return contentRatingTypeDetails;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_RATING_TYPE_DETAILS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContentRatingTypeDetails(@jakarta.annotation.Nonnull ContentRating contentRatingTypeDetails) {
    this.contentRatingTypeDetails = contentRatingTypeDetails;
  }


  /**
   * Return true if this ContentRatingTarget object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentRatingTarget contentRatingTarget = (ContentRatingTarget) o;
    return Objects.equals(this.contentRatingType, contentRatingTarget.contentRatingType) &&
        Objects.equals(this.contentRatingTypeDetails, contentRatingTarget.contentRatingTypeDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentRatingType, contentRatingTypeDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentRatingTarget {\n");
    sb.append("    contentRatingType: ").append(toIndentedString(contentRatingType)).append("\n");
    sb.append("    contentRatingTypeDetails: ").append(toIndentedString(contentRatingTypeDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `contentRatingType` to the URL query string
    if (getContentRatingType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontentRatingType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContentRatingType()))));
    }

    // add `contentRatingTypeDetails` to the URL query string
    if (getContentRatingTypeDetails() != null) {
      joiner.add(getContentRatingTypeDetails().toUrlQueryString(prefix + "contentRatingTypeDetails" + suffix));
    }

    return joiner.toString();
  }
}

