/*
 * Amazon Ads Targets API
 * Focused Java SDK specification containing only Targets operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.targets.model;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateAdInitiationTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateAdPlayerSizeTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateAppTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateAudienceTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateBrandSafetyCategoryTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateBrandSafetyTierTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateContentCategoryTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateContentGenreTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateContentInstreamPositionTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateContentOutstreamPositionTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateContentRatingTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateDayPartTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateDeviceTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateDomainTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateFoldPositionTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateInventorySourceTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateKeywordTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateLocationTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateNativeContentPositionTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreatePlacementTypeTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateProductAudienceTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateProductCategoryTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateProductTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateThemeTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateThirdPartyTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateVideoAdFormatTarget;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.CreateVideoContentDurationTarget;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


import io.github.chenyilei2016.amazonads.client.ApiClient;
/**
 * Typed CreateTargetDetails. The source contract uses one property per alternative.
 */
@JsonPropertyOrder({
  CreateTargetDetails.JSON_PROPERTY_KEYWORD_TARGET,
  CreateTargetDetails.JSON_PROPERTY_PRODUCT_TARGET,
  CreateTargetDetails.JSON_PROPERTY_PRODUCT_CATEGORY_TARGET,
  CreateTargetDetails.JSON_PROPERTY_PRODUCT_AUDIENCE_TARGET,
  CreateTargetDetails.JSON_PROPERTY_AUDIENCE_TARGET,
  CreateTargetDetails.JSON_PROPERTY_LOCATION_TARGET,
  CreateTargetDetails.JSON_PROPERTY_DOMAIN_TARGET,
  CreateTargetDetails.JSON_PROPERTY_APP_TARGET,
  CreateTargetDetails.JSON_PROPERTY_DEVICE_TARGET,
  CreateTargetDetails.JSON_PROPERTY_DAY_PART_TARGET,
  CreateTargetDetails.JSON_PROPERTY_CONTENT_CATEGORY_TARGET,
  CreateTargetDetails.JSON_PROPERTY_CONTENT_GENRE_TARGET,
  CreateTargetDetails.JSON_PROPERTY_CONTENT_RATING_TARGET,
  CreateTargetDetails.JSON_PROPERTY_BRAND_SAFETY_TIER_TARGET,
  CreateTargetDetails.JSON_PROPERTY_BRAND_SAFETY_CATEGORY_TARGET,
  CreateTargetDetails.JSON_PROPERTY_INVENTORY_SOURCE_TARGET,
  CreateTargetDetails.JSON_PROPERTY_AD_INITIATION_TARGET,
  CreateTargetDetails.JSON_PROPERTY_AD_PLAYER_SIZE_TARGET,
  CreateTargetDetails.JSON_PROPERTY_VIDEO_AD_FORMAT_TARGET,
  CreateTargetDetails.JSON_PROPERTY_THIRD_PARTY_TARGET,
  CreateTargetDetails.JSON_PROPERTY_THEME_TARGET,
  CreateTargetDetails.JSON_PROPERTY_CONTENT_INSTREAM_POSITION_TARGET,
  CreateTargetDetails.JSON_PROPERTY_CONTENT_OUTSTREAM_POSITION_TARGET,
  CreateTargetDetails.JSON_PROPERTY_VIDEO_CONTENT_DURATION_TARGET,
  CreateTargetDetails.JSON_PROPERTY_FOLD_POSITION_TARGET,
  CreateTargetDetails.JSON_PROPERTY_NATIVE_CONTENT_POSITION_TARGET,
  CreateTargetDetails.JSON_PROPERTY_PLACEMENT_TYPE_TARGET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CreateTargetDetails {
  public static final String JSON_PROPERTY_KEYWORD_TARGET = "keywordTarget";
  @jakarta.annotation.Nullable
  private CreateKeywordTarget keywordTarget;

  public static final String JSON_PROPERTY_PRODUCT_TARGET = "productTarget";
  @jakarta.annotation.Nullable
  private CreateProductTarget productTarget;

  public static final String JSON_PROPERTY_PRODUCT_CATEGORY_TARGET = "productCategoryTarget";
  @jakarta.annotation.Nullable
  private CreateProductCategoryTarget productCategoryTarget;

  public static final String JSON_PROPERTY_PRODUCT_AUDIENCE_TARGET = "productAudienceTarget";
  @jakarta.annotation.Nullable
  private CreateProductAudienceTarget productAudienceTarget;

  public static final String JSON_PROPERTY_AUDIENCE_TARGET = "audienceTarget";
  @jakarta.annotation.Nullable
  private CreateAudienceTarget audienceTarget;

  public static final String JSON_PROPERTY_LOCATION_TARGET = "locationTarget";
  @jakarta.annotation.Nullable
  private CreateLocationTarget locationTarget;

  public static final String JSON_PROPERTY_DOMAIN_TARGET = "domainTarget";
  @jakarta.annotation.Nullable
  private CreateDomainTarget domainTarget;

  public static final String JSON_PROPERTY_APP_TARGET = "appTarget";
  @jakarta.annotation.Nullable
  private CreateAppTarget appTarget;

  public static final String JSON_PROPERTY_DEVICE_TARGET = "deviceTarget";
  @jakarta.annotation.Nullable
  private CreateDeviceTarget deviceTarget;

  public static final String JSON_PROPERTY_DAY_PART_TARGET = "dayPartTarget";
  @jakarta.annotation.Nullable
  private CreateDayPartTarget dayPartTarget;

  public static final String JSON_PROPERTY_CONTENT_CATEGORY_TARGET = "contentCategoryTarget";
  @jakarta.annotation.Nullable
  private CreateContentCategoryTarget contentCategoryTarget;

  public static final String JSON_PROPERTY_CONTENT_GENRE_TARGET = "contentGenreTarget";
  @jakarta.annotation.Nullable
  private CreateContentGenreTarget contentGenreTarget;

  public static final String JSON_PROPERTY_CONTENT_RATING_TARGET = "contentRatingTarget";
  @jakarta.annotation.Nullable
  private CreateContentRatingTarget contentRatingTarget;

  public static final String JSON_PROPERTY_BRAND_SAFETY_TIER_TARGET = "brandSafetyTierTarget";
  @jakarta.annotation.Nullable
  private CreateBrandSafetyTierTarget brandSafetyTierTarget;

  public static final String JSON_PROPERTY_BRAND_SAFETY_CATEGORY_TARGET = "brandSafetyCategoryTarget";
  @jakarta.annotation.Nullable
  private CreateBrandSafetyCategoryTarget brandSafetyCategoryTarget;

  public static final String JSON_PROPERTY_INVENTORY_SOURCE_TARGET = "inventorySourceTarget";
  @jakarta.annotation.Nullable
  private CreateInventorySourceTarget inventorySourceTarget;

  public static final String JSON_PROPERTY_AD_INITIATION_TARGET = "adInitiationTarget";
  @jakarta.annotation.Nullable
  private CreateAdInitiationTarget adInitiationTarget;

  public static final String JSON_PROPERTY_AD_PLAYER_SIZE_TARGET = "adPlayerSizeTarget";
  @jakarta.annotation.Nullable
  private CreateAdPlayerSizeTarget adPlayerSizeTarget;

  public static final String JSON_PROPERTY_VIDEO_AD_FORMAT_TARGET = "videoAdFormatTarget";
  @jakarta.annotation.Nullable
  private CreateVideoAdFormatTarget videoAdFormatTarget;

  public static final String JSON_PROPERTY_THIRD_PARTY_TARGET = "thirdPartyTarget";
  @jakarta.annotation.Nullable
  private CreateThirdPartyTarget thirdPartyTarget;

  public static final String JSON_PROPERTY_THEME_TARGET = "themeTarget";
  @jakarta.annotation.Nullable
  private CreateThemeTarget themeTarget;

  public static final String JSON_PROPERTY_CONTENT_INSTREAM_POSITION_TARGET = "contentInstreamPositionTarget";
  @jakarta.annotation.Nullable
  private CreateContentInstreamPositionTarget contentInstreamPositionTarget;

  public static final String JSON_PROPERTY_CONTENT_OUTSTREAM_POSITION_TARGET = "contentOutstreamPositionTarget";
  @jakarta.annotation.Nullable
  private CreateContentOutstreamPositionTarget contentOutstreamPositionTarget;

  public static final String JSON_PROPERTY_VIDEO_CONTENT_DURATION_TARGET = "videoContentDurationTarget";
  @jakarta.annotation.Nullable
  private CreateVideoContentDurationTarget videoContentDurationTarget;

  public static final String JSON_PROPERTY_FOLD_POSITION_TARGET = "foldPositionTarget";
  @jakarta.annotation.Nullable
  private CreateFoldPositionTarget foldPositionTarget;

  public static final String JSON_PROPERTY_NATIVE_CONTENT_POSITION_TARGET = "nativeContentPositionTarget";
  @jakarta.annotation.Nullable
  private CreateNativeContentPositionTarget nativeContentPositionTarget;

  public static final String JSON_PROPERTY_PLACEMENT_TYPE_TARGET = "placementTypeTarget";
  @jakarta.annotation.Nullable
  private CreatePlacementTypeTarget placementTypeTarget;

  public CreateTargetDetails() {
  }

  public CreateTargetDetails keywordTarget(@jakarta.annotation.Nullable CreateKeywordTarget keywordTarget) {
    this.keywordTarget = keywordTarget;
    return this;
  }

  /**
   * Get keywordTarget
   * @return keywordTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_KEYWORD_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateKeywordTarget getKeywordTarget() {
    return keywordTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_KEYWORD_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeywordTarget(@jakarta.annotation.Nullable CreateKeywordTarget keywordTarget) {
    this.keywordTarget = keywordTarget;
  }


  public CreateTargetDetails productTarget(@jakarta.annotation.Nullable CreateProductTarget productTarget) {
    this.productTarget = productTarget;
    return this;
  }

  /**
   * Get productTarget
   * @return productTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PRODUCT_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateProductTarget getProductTarget() {
    return productTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductTarget(@jakarta.annotation.Nullable CreateProductTarget productTarget) {
    this.productTarget = productTarget;
  }


  public CreateTargetDetails productCategoryTarget(@jakarta.annotation.Nullable CreateProductCategoryTarget productCategoryTarget) {
    this.productCategoryTarget = productCategoryTarget;
    return this;
  }

  /**
   * Get productCategoryTarget
   * @return productCategoryTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PRODUCT_CATEGORY_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateProductCategoryTarget getProductCategoryTarget() {
    return productCategoryTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_CATEGORY_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductCategoryTarget(@jakarta.annotation.Nullable CreateProductCategoryTarget productCategoryTarget) {
    this.productCategoryTarget = productCategoryTarget;
  }


  public CreateTargetDetails productAudienceTarget(@jakarta.annotation.Nullable CreateProductAudienceTarget productAudienceTarget) {
    this.productAudienceTarget = productAudienceTarget;
    return this;
  }

  /**
   * Get productAudienceTarget
   * @return productAudienceTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PRODUCT_AUDIENCE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateProductAudienceTarget getProductAudienceTarget() {
    return productAudienceTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_AUDIENCE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductAudienceTarget(@jakarta.annotation.Nullable CreateProductAudienceTarget productAudienceTarget) {
    this.productAudienceTarget = productAudienceTarget;
  }


  public CreateTargetDetails audienceTarget(@jakarta.annotation.Nullable CreateAudienceTarget audienceTarget) {
    this.audienceTarget = audienceTarget;
    return this;
  }

  /**
   * Get audienceTarget
   * @return audienceTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_AUDIENCE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateAudienceTarget getAudienceTarget() {
    return audienceTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_AUDIENCE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAudienceTarget(@jakarta.annotation.Nullable CreateAudienceTarget audienceTarget) {
    this.audienceTarget = audienceTarget;
  }


  public CreateTargetDetails locationTarget(@jakarta.annotation.Nullable CreateLocationTarget locationTarget) {
    this.locationTarget = locationTarget;
    return this;
  }

  /**
   * Get locationTarget
   * @return locationTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_LOCATION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateLocationTarget getLocationTarget() {
    return locationTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocationTarget(@jakarta.annotation.Nullable CreateLocationTarget locationTarget) {
    this.locationTarget = locationTarget;
  }


  public CreateTargetDetails domainTarget(@jakarta.annotation.Nullable CreateDomainTarget domainTarget) {
    this.domainTarget = domainTarget;
    return this;
  }

  /**
   * Get domainTarget
   * @return domainTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_DOMAIN_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateDomainTarget getDomainTarget() {
    return domainTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAIN_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomainTarget(@jakarta.annotation.Nullable CreateDomainTarget domainTarget) {
    this.domainTarget = domainTarget;
  }


  public CreateTargetDetails appTarget(@jakarta.annotation.Nullable CreateAppTarget appTarget) {
    this.appTarget = appTarget;
    return this;
  }

  /**
   * Get appTarget
   * @return appTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_APP_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateAppTarget getAppTarget() {
    return appTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppTarget(@jakarta.annotation.Nullable CreateAppTarget appTarget) {
    this.appTarget = appTarget;
  }


  public CreateTargetDetails deviceTarget(@jakarta.annotation.Nullable CreateDeviceTarget deviceTarget) {
    this.deviceTarget = deviceTarget;
    return this;
  }

  /**
   * Get deviceTarget
   * @return deviceTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_DEVICE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateDeviceTarget getDeviceTarget() {
    return deviceTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceTarget(@jakarta.annotation.Nullable CreateDeviceTarget deviceTarget) {
    this.deviceTarget = deviceTarget;
  }


  public CreateTargetDetails dayPartTarget(@jakarta.annotation.Nullable CreateDayPartTarget dayPartTarget) {
    this.dayPartTarget = dayPartTarget;
    return this;
  }

  /**
   * Get dayPartTarget
   * @return dayPartTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_DAY_PART_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateDayPartTarget getDayPartTarget() {
    return dayPartTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_DAY_PART_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDayPartTarget(@jakarta.annotation.Nullable CreateDayPartTarget dayPartTarget) {
    this.dayPartTarget = dayPartTarget;
  }


  public CreateTargetDetails contentCategoryTarget(@jakarta.annotation.Nullable CreateContentCategoryTarget contentCategoryTarget) {
    this.contentCategoryTarget = contentCategoryTarget;
    return this;
  }

  /**
   * Get contentCategoryTarget
   * @return contentCategoryTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONTENT_CATEGORY_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateContentCategoryTarget getContentCategoryTarget() {
    return contentCategoryTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_CATEGORY_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentCategoryTarget(@jakarta.annotation.Nullable CreateContentCategoryTarget contentCategoryTarget) {
    this.contentCategoryTarget = contentCategoryTarget;
  }


  public CreateTargetDetails contentGenreTarget(@jakarta.annotation.Nullable CreateContentGenreTarget contentGenreTarget) {
    this.contentGenreTarget = contentGenreTarget;
    return this;
  }

  /**
   * Get contentGenreTarget
   * @return contentGenreTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONTENT_GENRE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateContentGenreTarget getContentGenreTarget() {
    return contentGenreTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_GENRE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentGenreTarget(@jakarta.annotation.Nullable CreateContentGenreTarget contentGenreTarget) {
    this.contentGenreTarget = contentGenreTarget;
  }


  public CreateTargetDetails contentRatingTarget(@jakarta.annotation.Nullable CreateContentRatingTarget contentRatingTarget) {
    this.contentRatingTarget = contentRatingTarget;
    return this;
  }

  /**
   * Get contentRatingTarget
   * @return contentRatingTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONTENT_RATING_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateContentRatingTarget getContentRatingTarget() {
    return contentRatingTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_RATING_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentRatingTarget(@jakarta.annotation.Nullable CreateContentRatingTarget contentRatingTarget) {
    this.contentRatingTarget = contentRatingTarget;
  }


  public CreateTargetDetails brandSafetyTierTarget(@jakarta.annotation.Nullable CreateBrandSafetyTierTarget brandSafetyTierTarget) {
    this.brandSafetyTierTarget = brandSafetyTierTarget;
    return this;
  }

  /**
   * Get brandSafetyTierTarget
   * @return brandSafetyTierTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_BRAND_SAFETY_TIER_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateBrandSafetyTierTarget getBrandSafetyTierTarget() {
    return brandSafetyTierTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_BRAND_SAFETY_TIER_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrandSafetyTierTarget(@jakarta.annotation.Nullable CreateBrandSafetyTierTarget brandSafetyTierTarget) {
    this.brandSafetyTierTarget = brandSafetyTierTarget;
  }


  public CreateTargetDetails brandSafetyCategoryTarget(@jakarta.annotation.Nullable CreateBrandSafetyCategoryTarget brandSafetyCategoryTarget) {
    this.brandSafetyCategoryTarget = brandSafetyCategoryTarget;
    return this;
  }

  /**
   * Get brandSafetyCategoryTarget
   * @return brandSafetyCategoryTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_BRAND_SAFETY_CATEGORY_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateBrandSafetyCategoryTarget getBrandSafetyCategoryTarget() {
    return brandSafetyCategoryTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_BRAND_SAFETY_CATEGORY_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrandSafetyCategoryTarget(@jakarta.annotation.Nullable CreateBrandSafetyCategoryTarget brandSafetyCategoryTarget) {
    this.brandSafetyCategoryTarget = brandSafetyCategoryTarget;
  }


  public CreateTargetDetails inventorySourceTarget(@jakarta.annotation.Nullable CreateInventorySourceTarget inventorySourceTarget) {
    this.inventorySourceTarget = inventorySourceTarget;
    return this;
  }

  /**
   * Get inventorySourceTarget
   * @return inventorySourceTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_INVENTORY_SOURCE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateInventorySourceTarget getInventorySourceTarget() {
    return inventorySourceTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_INVENTORY_SOURCE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInventorySourceTarget(@jakarta.annotation.Nullable CreateInventorySourceTarget inventorySourceTarget) {
    this.inventorySourceTarget = inventorySourceTarget;
  }


  public CreateTargetDetails adInitiationTarget(@jakarta.annotation.Nullable CreateAdInitiationTarget adInitiationTarget) {
    this.adInitiationTarget = adInitiationTarget;
    return this;
  }

  /**
   * Get adInitiationTarget
   * @return adInitiationTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_AD_INITIATION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateAdInitiationTarget getAdInitiationTarget() {
    return adInitiationTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_AD_INITIATION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdInitiationTarget(@jakarta.annotation.Nullable CreateAdInitiationTarget adInitiationTarget) {
    this.adInitiationTarget = adInitiationTarget;
  }


  public CreateTargetDetails adPlayerSizeTarget(@jakarta.annotation.Nullable CreateAdPlayerSizeTarget adPlayerSizeTarget) {
    this.adPlayerSizeTarget = adPlayerSizeTarget;
    return this;
  }

  /**
   * Get adPlayerSizeTarget
   * @return adPlayerSizeTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_AD_PLAYER_SIZE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateAdPlayerSizeTarget getAdPlayerSizeTarget() {
    return adPlayerSizeTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_AD_PLAYER_SIZE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdPlayerSizeTarget(@jakarta.annotation.Nullable CreateAdPlayerSizeTarget adPlayerSizeTarget) {
    this.adPlayerSizeTarget = adPlayerSizeTarget;
  }


  public CreateTargetDetails videoAdFormatTarget(@jakarta.annotation.Nullable CreateVideoAdFormatTarget videoAdFormatTarget) {
    this.videoAdFormatTarget = videoAdFormatTarget;
    return this;
  }

  /**
   * Get videoAdFormatTarget
   * @return videoAdFormatTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_VIDEO_AD_FORMAT_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateVideoAdFormatTarget getVideoAdFormatTarget() {
    return videoAdFormatTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_VIDEO_AD_FORMAT_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideoAdFormatTarget(@jakarta.annotation.Nullable CreateVideoAdFormatTarget videoAdFormatTarget) {
    this.videoAdFormatTarget = videoAdFormatTarget;
  }


  public CreateTargetDetails thirdPartyTarget(@jakarta.annotation.Nullable CreateThirdPartyTarget thirdPartyTarget) {
    this.thirdPartyTarget = thirdPartyTarget;
    return this;
  }

  /**
   * Get thirdPartyTarget
   * @return thirdPartyTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_THIRD_PARTY_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateThirdPartyTarget getThirdPartyTarget() {
    return thirdPartyTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_THIRD_PARTY_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThirdPartyTarget(@jakarta.annotation.Nullable CreateThirdPartyTarget thirdPartyTarget) {
    this.thirdPartyTarget = thirdPartyTarget;
  }


  public CreateTargetDetails themeTarget(@jakarta.annotation.Nullable CreateThemeTarget themeTarget) {
    this.themeTarget = themeTarget;
    return this;
  }

  /**
   * Get themeTarget
   * @return themeTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_THEME_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateThemeTarget getThemeTarget() {
    return themeTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_THEME_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThemeTarget(@jakarta.annotation.Nullable CreateThemeTarget themeTarget) {
    this.themeTarget = themeTarget;
  }


  public CreateTargetDetails contentInstreamPositionTarget(@jakarta.annotation.Nullable CreateContentInstreamPositionTarget contentInstreamPositionTarget) {
    this.contentInstreamPositionTarget = contentInstreamPositionTarget;
    return this;
  }

  /**
   * Get contentInstreamPositionTarget
   * @return contentInstreamPositionTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONTENT_INSTREAM_POSITION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateContentInstreamPositionTarget getContentInstreamPositionTarget() {
    return contentInstreamPositionTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_INSTREAM_POSITION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentInstreamPositionTarget(@jakarta.annotation.Nullable CreateContentInstreamPositionTarget contentInstreamPositionTarget) {
    this.contentInstreamPositionTarget = contentInstreamPositionTarget;
  }


  public CreateTargetDetails contentOutstreamPositionTarget(@jakarta.annotation.Nullable CreateContentOutstreamPositionTarget contentOutstreamPositionTarget) {
    this.contentOutstreamPositionTarget = contentOutstreamPositionTarget;
    return this;
  }

  /**
   * Get contentOutstreamPositionTarget
   * @return contentOutstreamPositionTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONTENT_OUTSTREAM_POSITION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateContentOutstreamPositionTarget getContentOutstreamPositionTarget() {
    return contentOutstreamPositionTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_OUTSTREAM_POSITION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentOutstreamPositionTarget(@jakarta.annotation.Nullable CreateContentOutstreamPositionTarget contentOutstreamPositionTarget) {
    this.contentOutstreamPositionTarget = contentOutstreamPositionTarget;
  }


  public CreateTargetDetails videoContentDurationTarget(@jakarta.annotation.Nullable CreateVideoContentDurationTarget videoContentDurationTarget) {
    this.videoContentDurationTarget = videoContentDurationTarget;
    return this;
  }

  /**
   * Get videoContentDurationTarget
   * @return videoContentDurationTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_VIDEO_CONTENT_DURATION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateVideoContentDurationTarget getVideoContentDurationTarget() {
    return videoContentDurationTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_VIDEO_CONTENT_DURATION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideoContentDurationTarget(@jakarta.annotation.Nullable CreateVideoContentDurationTarget videoContentDurationTarget) {
    this.videoContentDurationTarget = videoContentDurationTarget;
  }


  public CreateTargetDetails foldPositionTarget(@jakarta.annotation.Nullable CreateFoldPositionTarget foldPositionTarget) {
    this.foldPositionTarget = foldPositionTarget;
    return this;
  }

  /**
   * Get foldPositionTarget
   * @return foldPositionTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_FOLD_POSITION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateFoldPositionTarget getFoldPositionTarget() {
    return foldPositionTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_FOLD_POSITION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFoldPositionTarget(@jakarta.annotation.Nullable CreateFoldPositionTarget foldPositionTarget) {
    this.foldPositionTarget = foldPositionTarget;
  }


  public CreateTargetDetails nativeContentPositionTarget(@jakarta.annotation.Nullable CreateNativeContentPositionTarget nativeContentPositionTarget) {
    this.nativeContentPositionTarget = nativeContentPositionTarget;
    return this;
  }

  /**
   * Get nativeContentPositionTarget
   * @return nativeContentPositionTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_NATIVE_CONTENT_POSITION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateNativeContentPositionTarget getNativeContentPositionTarget() {
    return nativeContentPositionTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_NATIVE_CONTENT_POSITION_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNativeContentPositionTarget(@jakarta.annotation.Nullable CreateNativeContentPositionTarget nativeContentPositionTarget) {
    this.nativeContentPositionTarget = nativeContentPositionTarget;
  }


  public CreateTargetDetails placementTypeTarget(@jakarta.annotation.Nullable CreatePlacementTypeTarget placementTypeTarget) {
    this.placementTypeTarget = placementTypeTarget;
    return this;
  }

  /**
   * Get placementTypeTarget
   * @return placementTypeTarget
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PLACEMENT_TYPE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreatePlacementTypeTarget getPlacementTypeTarget() {
    return placementTypeTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_PLACEMENT_TYPE_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlacementTypeTarget(@jakarta.annotation.Nullable CreatePlacementTypeTarget placementTypeTarget) {
    this.placementTypeTarget = placementTypeTarget;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public CreateTargetDetails putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  /**
   * Return true if this CreateTargetDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTargetDetails createTargetDetails = (CreateTargetDetails) o;
    return Objects.equals(this.keywordTarget, createTargetDetails.keywordTarget) &&
        Objects.equals(this.productTarget, createTargetDetails.productTarget) &&
        Objects.equals(this.productCategoryTarget, createTargetDetails.productCategoryTarget) &&
        Objects.equals(this.productAudienceTarget, createTargetDetails.productAudienceTarget) &&
        Objects.equals(this.audienceTarget, createTargetDetails.audienceTarget) &&
        Objects.equals(this.locationTarget, createTargetDetails.locationTarget) &&
        Objects.equals(this.domainTarget, createTargetDetails.domainTarget) &&
        Objects.equals(this.appTarget, createTargetDetails.appTarget) &&
        Objects.equals(this.deviceTarget, createTargetDetails.deviceTarget) &&
        Objects.equals(this.dayPartTarget, createTargetDetails.dayPartTarget) &&
        Objects.equals(this.contentCategoryTarget, createTargetDetails.contentCategoryTarget) &&
        Objects.equals(this.contentGenreTarget, createTargetDetails.contentGenreTarget) &&
        Objects.equals(this.contentRatingTarget, createTargetDetails.contentRatingTarget) &&
        Objects.equals(this.brandSafetyTierTarget, createTargetDetails.brandSafetyTierTarget) &&
        Objects.equals(this.brandSafetyCategoryTarget, createTargetDetails.brandSafetyCategoryTarget) &&
        Objects.equals(this.inventorySourceTarget, createTargetDetails.inventorySourceTarget) &&
        Objects.equals(this.adInitiationTarget, createTargetDetails.adInitiationTarget) &&
        Objects.equals(this.adPlayerSizeTarget, createTargetDetails.adPlayerSizeTarget) &&
        Objects.equals(this.videoAdFormatTarget, createTargetDetails.videoAdFormatTarget) &&
        Objects.equals(this.thirdPartyTarget, createTargetDetails.thirdPartyTarget) &&
        Objects.equals(this.themeTarget, createTargetDetails.themeTarget) &&
        Objects.equals(this.contentInstreamPositionTarget, createTargetDetails.contentInstreamPositionTarget) &&
        Objects.equals(this.contentOutstreamPositionTarget, createTargetDetails.contentOutstreamPositionTarget) &&
        Objects.equals(this.videoContentDurationTarget, createTargetDetails.videoContentDurationTarget) &&
        Objects.equals(this.foldPositionTarget, createTargetDetails.foldPositionTarget) &&
        Objects.equals(this.nativeContentPositionTarget, createTargetDetails.nativeContentPositionTarget) &&
        Objects.equals(this.placementTypeTarget, createTargetDetails.placementTypeTarget)&&
        Objects.equals(this.additionalProperties, createTargetDetails.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keywordTarget, productTarget, productCategoryTarget, productAudienceTarget, audienceTarget, locationTarget, domainTarget, appTarget, deviceTarget, dayPartTarget, contentCategoryTarget, contentGenreTarget, contentRatingTarget, brandSafetyTierTarget, brandSafetyCategoryTarget, inventorySourceTarget, adInitiationTarget, adPlayerSizeTarget, videoAdFormatTarget, thirdPartyTarget, themeTarget, contentInstreamPositionTarget, contentOutstreamPositionTarget, videoContentDurationTarget, foldPositionTarget, nativeContentPositionTarget, placementTypeTarget, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTargetDetails {\n");
    sb.append("    keywordTarget: ").append(toIndentedString(keywordTarget)).append("\n");
    sb.append("    productTarget: ").append(toIndentedString(productTarget)).append("\n");
    sb.append("    productCategoryTarget: ").append(toIndentedString(productCategoryTarget)).append("\n");
    sb.append("    productAudienceTarget: ").append(toIndentedString(productAudienceTarget)).append("\n");
    sb.append("    audienceTarget: ").append(toIndentedString(audienceTarget)).append("\n");
    sb.append("    locationTarget: ").append(toIndentedString(locationTarget)).append("\n");
    sb.append("    domainTarget: ").append(toIndentedString(domainTarget)).append("\n");
    sb.append("    appTarget: ").append(toIndentedString(appTarget)).append("\n");
    sb.append("    deviceTarget: ").append(toIndentedString(deviceTarget)).append("\n");
    sb.append("    dayPartTarget: ").append(toIndentedString(dayPartTarget)).append("\n");
    sb.append("    contentCategoryTarget: ").append(toIndentedString(contentCategoryTarget)).append("\n");
    sb.append("    contentGenreTarget: ").append(toIndentedString(contentGenreTarget)).append("\n");
    sb.append("    contentRatingTarget: ").append(toIndentedString(contentRatingTarget)).append("\n");
    sb.append("    brandSafetyTierTarget: ").append(toIndentedString(brandSafetyTierTarget)).append("\n");
    sb.append("    brandSafetyCategoryTarget: ").append(toIndentedString(brandSafetyCategoryTarget)).append("\n");
    sb.append("    inventorySourceTarget: ").append(toIndentedString(inventorySourceTarget)).append("\n");
    sb.append("    adInitiationTarget: ").append(toIndentedString(adInitiationTarget)).append("\n");
    sb.append("    adPlayerSizeTarget: ").append(toIndentedString(adPlayerSizeTarget)).append("\n");
    sb.append("    videoAdFormatTarget: ").append(toIndentedString(videoAdFormatTarget)).append("\n");
    sb.append("    thirdPartyTarget: ").append(toIndentedString(thirdPartyTarget)).append("\n");
    sb.append("    themeTarget: ").append(toIndentedString(themeTarget)).append("\n");
    sb.append("    contentInstreamPositionTarget: ").append(toIndentedString(contentInstreamPositionTarget)).append("\n");
    sb.append("    contentOutstreamPositionTarget: ").append(toIndentedString(contentOutstreamPositionTarget)).append("\n");
    sb.append("    videoContentDurationTarget: ").append(toIndentedString(videoContentDurationTarget)).append("\n");
    sb.append("    foldPositionTarget: ").append(toIndentedString(foldPositionTarget)).append("\n");
    sb.append("    nativeContentPositionTarget: ").append(toIndentedString(nativeContentPositionTarget)).append("\n");
    sb.append("    placementTypeTarget: ").append(toIndentedString(placementTypeTarget)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `keywordTarget` to the URL query string
    if (getKeywordTarget() != null) {
      joiner.add(getKeywordTarget().toUrlQueryString(prefix + "keywordTarget" + suffix));
    }

    // add `productTarget` to the URL query string
    if (getProductTarget() != null) {
      joiner.add(getProductTarget().toUrlQueryString(prefix + "productTarget" + suffix));
    }

    // add `productCategoryTarget` to the URL query string
    if (getProductCategoryTarget() != null) {
      joiner.add(getProductCategoryTarget().toUrlQueryString(prefix + "productCategoryTarget" + suffix));
    }

    // add `productAudienceTarget` to the URL query string
    if (getProductAudienceTarget() != null) {
      joiner.add(getProductAudienceTarget().toUrlQueryString(prefix + "productAudienceTarget" + suffix));
    }

    // add `audienceTarget` to the URL query string
    if (getAudienceTarget() != null) {
      joiner.add(getAudienceTarget().toUrlQueryString(prefix + "audienceTarget" + suffix));
    }

    // add `locationTarget` to the URL query string
    if (getLocationTarget() != null) {
      joiner.add(getLocationTarget().toUrlQueryString(prefix + "locationTarget" + suffix));
    }

    // add `domainTarget` to the URL query string
    if (getDomainTarget() != null) {
      joiner.add(getDomainTarget().toUrlQueryString(prefix + "domainTarget" + suffix));
    }

    // add `appTarget` to the URL query string
    if (getAppTarget() != null) {
      joiner.add(getAppTarget().toUrlQueryString(prefix + "appTarget" + suffix));
    }

    // add `deviceTarget` to the URL query string
    if (getDeviceTarget() != null) {
      joiner.add(getDeviceTarget().toUrlQueryString(prefix + "deviceTarget" + suffix));
    }

    // add `dayPartTarget` to the URL query string
    if (getDayPartTarget() != null) {
      joiner.add(getDayPartTarget().toUrlQueryString(prefix + "dayPartTarget" + suffix));
    }

    // add `contentCategoryTarget` to the URL query string
    if (getContentCategoryTarget() != null) {
      joiner.add(getContentCategoryTarget().toUrlQueryString(prefix + "contentCategoryTarget" + suffix));
    }

    // add `contentGenreTarget` to the URL query string
    if (getContentGenreTarget() != null) {
      joiner.add(getContentGenreTarget().toUrlQueryString(prefix + "contentGenreTarget" + suffix));
    }

    // add `contentRatingTarget` to the URL query string
    if (getContentRatingTarget() != null) {
      joiner.add(getContentRatingTarget().toUrlQueryString(prefix + "contentRatingTarget" + suffix));
    }

    // add `brandSafetyTierTarget` to the URL query string
    if (getBrandSafetyTierTarget() != null) {
      joiner.add(getBrandSafetyTierTarget().toUrlQueryString(prefix + "brandSafetyTierTarget" + suffix));
    }

    // add `brandSafetyCategoryTarget` to the URL query string
    if (getBrandSafetyCategoryTarget() != null) {
      joiner.add(getBrandSafetyCategoryTarget().toUrlQueryString(prefix + "brandSafetyCategoryTarget" + suffix));
    }

    // add `inventorySourceTarget` to the URL query string
    if (getInventorySourceTarget() != null) {
      joiner.add(getInventorySourceTarget().toUrlQueryString(prefix + "inventorySourceTarget" + suffix));
    }

    // add `adInitiationTarget` to the URL query string
    if (getAdInitiationTarget() != null) {
      joiner.add(getAdInitiationTarget().toUrlQueryString(prefix + "adInitiationTarget" + suffix));
    }

    // add `adPlayerSizeTarget` to the URL query string
    if (getAdPlayerSizeTarget() != null) {
      joiner.add(getAdPlayerSizeTarget().toUrlQueryString(prefix + "adPlayerSizeTarget" + suffix));
    }

    // add `videoAdFormatTarget` to the URL query string
    if (getVideoAdFormatTarget() != null) {
      joiner.add(getVideoAdFormatTarget().toUrlQueryString(prefix + "videoAdFormatTarget" + suffix));
    }

    // add `thirdPartyTarget` to the URL query string
    if (getThirdPartyTarget() != null) {
      joiner.add(getThirdPartyTarget().toUrlQueryString(prefix + "thirdPartyTarget" + suffix));
    }

    // add `themeTarget` to the URL query string
    if (getThemeTarget() != null) {
      joiner.add(getThemeTarget().toUrlQueryString(prefix + "themeTarget" + suffix));
    }

    // add `contentInstreamPositionTarget` to the URL query string
    if (getContentInstreamPositionTarget() != null) {
      joiner.add(getContentInstreamPositionTarget().toUrlQueryString(prefix + "contentInstreamPositionTarget" + suffix));
    }

    // add `contentOutstreamPositionTarget` to the URL query string
    if (getContentOutstreamPositionTarget() != null) {
      joiner.add(getContentOutstreamPositionTarget().toUrlQueryString(prefix + "contentOutstreamPositionTarget" + suffix));
    }

    // add `videoContentDurationTarget` to the URL query string
    if (getVideoContentDurationTarget() != null) {
      joiner.add(getVideoContentDurationTarget().toUrlQueryString(prefix + "videoContentDurationTarget" + suffix));
    }

    // add `foldPositionTarget` to the URL query string
    if (getFoldPositionTarget() != null) {
      joiner.add(getFoldPositionTarget().toUrlQueryString(prefix + "foldPositionTarget" + suffix));
    }

    // add `nativeContentPositionTarget` to the URL query string
    if (getNativeContentPositionTarget() != null) {
      joiner.add(getNativeContentPositionTarget().toUrlQueryString(prefix + "nativeContentPositionTarget" + suffix));
    }

    // add `placementTypeTarget` to the URL query string
    if (getPlacementTypeTarget() != null) {
      joiner.add(getPlacementTypeTarget().toUrlQueryString(prefix + "placementTypeTarget" + suffix));
    }

    return joiner.toString();
  }
}

