/*
 * Amazon Ads Targets API
 * Focused Java SDK specification containing only Targets operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.targets.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


import io.github.chenyilei2016.amazonads.adsv1.client.ApiClient;
/**
 * CreateProductGenreRefinement
 */
@JsonPropertyOrder({
  CreateProductGenreRefinement.JSON_PROPERTY_PRODUCT_GENRE_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CreateProductGenreRefinement {
  public static final String JSON_PROPERTY_PRODUCT_GENRE_ID = "productGenreId";
  @jakarta.annotation.Nonnull
  private String productGenreId;

  public CreateProductGenreRefinement() {
  }

  public CreateProductGenreRefinement productGenreId(@jakarta.annotation.Nonnull String productGenreId) {
    this.productGenreId = productGenreId;
    return this;
  }

  /**
   * The product genre ID to target.
   * @return productGenreId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_PRODUCT_GENRE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProductGenreId() {
    return productGenreId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_GENRE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductGenreId(@jakarta.annotation.Nonnull String productGenreId) {
    this.productGenreId = productGenreId;
  }


  /**
   * Return true if this CreateProductGenreRefinement object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateProductGenreRefinement createProductGenreRefinement = (CreateProductGenreRefinement) o;
    return Objects.equals(this.productGenreId, createProductGenreRefinement.productGenreId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productGenreId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateProductGenreRefinement {\n");
    sb.append("    productGenreId: ").append(toIndentedString(productGenreId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `productGenreId` to the URL query string
    if (getProductGenreId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproductGenreId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProductGenreId()))));
    }

    return joiner.toString();
  }
}

