/*
 * Amazon Ads Targets API
 * Focused Java SDK specification containing only Targets operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.targets.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets DVBrandSafetyAppAgeRatingType
 */
public enum DVBrandSafetyAppAgeRatingType {

  ADULTS_ONLY_18_PLUS("ADULTS_ONLY_18_PLUS"),

  EVERYONE_4_PLUS("EVERYONE_4_PLUS"),

  MATURE_17_PLUS("MATURE_17_PLUS"),

  TEENS_12_PLUS("TEENS_12_PLUS"),

  TWEENS_9_PLUS("TWEENS_9_PLUS"),

  UNKNOWN("UNKNOWN"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  DVBrandSafetyAppAgeRatingType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DVBrandSafetyAppAgeRatingType fromValue(String value) {
    for (DVBrandSafetyAppAgeRatingType b : DVBrandSafetyAppAgeRatingType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format(java.util.Locale.ROOT, "%s=%s", prefix, this.toString());
  }

}

