/*
 * Amazon Ads Targets API
 * Focused Java SDK specification containing only Targets operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.targets.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.Error;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.github.chenyilei2016.amazonads.adsv1.client.ApiClient;
/**
 * ErrorsIndex
 */
@JsonPropertyOrder({
  ErrorsIndex.JSON_PROPERTY_ERRORS,
  ErrorsIndex.JSON_PROPERTY_INDEX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ErrorsIndex {
  public static final String JSON_PROPERTY_ERRORS = "errors";
  @jakarta.annotation.Nonnull
  private List<Error> errors = new ArrayList<>();

  public static final String JSON_PROPERTY_INDEX = "index";
  @jakarta.annotation.Nonnull
  private Integer index;

  public ErrorsIndex() {
  }

  public ErrorsIndex errors(@jakarta.annotation.Nonnull List<Error> errors) {
    this.errors = errors;
    return this;
  }

  public ErrorsIndex addErrorsItem(Error errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Error> getErrors() {
    return errors;
  }


  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setErrors(@jakarta.annotation.Nonnull List<Error> errors) {
    this.errors = errors;
  }


  public ErrorsIndex index(@jakarta.annotation.Nonnull Integer index) {
    this.index = index;
    return this;
  }

  /**
   * Get index
   * minimum: 0
   * maximum: 4999
   * @return index
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getIndex() {
    return index;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIndex(@jakarta.annotation.Nonnull Integer index) {
    this.index = index;
  }


  /**
   * Return true if this ErrorsIndex object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorsIndex errorsIndex = (ErrorsIndex) o;
    return Objects.equals(this.errors, errorsIndex.errors) &&
        Objects.equals(this.index, errorsIndex.index);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, index);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorsIndex {\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `errors` to the URL query string
    if (getErrors() != null) {
      for (int i = 0; i < getErrors().size(); i++) {
        if (getErrors().get(i) != null) {
          joiner.add(getErrors().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%serrors%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `index` to the URL query string
    if (getIndex() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sindex%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIndex()))));
    }

    return joiner.toString();
  }
}

