/*
 * Amazon Ads Targets API
 * Focused Java SDK specification containing only Targets operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.targets.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.Marketplace;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.MarketplaceTargetFieldOverrides;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.github.chenyilei2016.amazonads.adsv1.client.ApiClient;
/**
 * MarketplaceTargetConfigurations
 */
@JsonPropertyOrder({
  MarketplaceTargetConfigurations.JSON_PROPERTY_MARKETPLACE,
  MarketplaceTargetConfigurations.JSON_PROPERTY_OVERRIDES,
  MarketplaceTargetConfigurations.JSON_PROPERTY_TARGET_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class MarketplaceTargetConfigurations {
  public static final String JSON_PROPERTY_MARKETPLACE = "marketplace";
  @jakarta.annotation.Nonnull
  private Marketplace marketplace;

  public static final String JSON_PROPERTY_OVERRIDES = "overrides";
  @jakarta.annotation.Nonnull
  private MarketplaceTargetFieldOverrides overrides;

  public static final String JSON_PROPERTY_TARGET_ID = "targetId";
  @jakarta.annotation.Nonnull
  private String targetId;

  public MarketplaceTargetConfigurations() {
  }

  public MarketplaceTargetConfigurations marketplace(@jakarta.annotation.Nonnull Marketplace marketplace) {
    this.marketplace = marketplace;
    return this;
  }

  /**
   * Get marketplace
   * @return marketplace
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MARKETPLACE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Marketplace getMarketplace() {
    return marketplace;
  }


  @JsonProperty(value = JSON_PROPERTY_MARKETPLACE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMarketplace(@jakarta.annotation.Nonnull Marketplace marketplace) {
    this.marketplace = marketplace;
  }


  public MarketplaceTargetConfigurations overrides(@jakarta.annotation.Nonnull MarketplaceTargetFieldOverrides overrides) {
    this.overrides = overrides;
    return this;
  }

  /**
   * Get overrides
   * @return overrides
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OVERRIDES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public MarketplaceTargetFieldOverrides getOverrides() {
    return overrides;
  }


  @JsonProperty(value = JSON_PROPERTY_OVERRIDES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOverrides(@jakarta.annotation.Nonnull MarketplaceTargetFieldOverrides overrides) {
    this.overrides = overrides;
  }


  public MarketplaceTargetConfigurations targetId(@jakarta.annotation.Nonnull String targetId) {
    this.targetId = targetId;
    return this;
  }

  /**
   * Represents marketplace target id (Ex: targetId-US) associated to global target (Ex: targetId-Global)
   * @return targetId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TARGET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTargetId() {
    return targetId;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTargetId(@jakarta.annotation.Nonnull String targetId) {
    this.targetId = targetId;
  }


  /**
   * Return true if this MarketplaceTargetConfigurations object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketplaceTargetConfigurations marketplaceTargetConfigurations = (MarketplaceTargetConfigurations) o;
    return Objects.equals(this.marketplace, marketplaceTargetConfigurations.marketplace) &&
        Objects.equals(this.overrides, marketplaceTargetConfigurations.overrides) &&
        Objects.equals(this.targetId, marketplaceTargetConfigurations.targetId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(marketplace, overrides, targetId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketplaceTargetConfigurations {\n");
    sb.append("    marketplace: ").append(toIndentedString(marketplace)).append("\n");
    sb.append("    overrides: ").append(toIndentedString(overrides)).append("\n");
    sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `marketplace` to the URL query string
    if (getMarketplace() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smarketplace%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMarketplace()))));
    }

    // add `overrides` to the URL query string
    if (getOverrides() != null) {
      joiner.add(getOverrides().toUrlQueryString(prefix + "overrides" + suffix));
    }

    // add `targetId` to the URL query string
    if (getTargetId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stargetId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTargetId()))));
    }

    return joiner.toString();
  }
}

