/*
 * Amazon Ads Targets API
 * Focused Java SDK specification containing only Targets operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.targets.model;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyAuthenticAttention;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyAuthenticAttention1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyAuthenticBrandSafety;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyAuthenticBrandSafety1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyBrandSafety;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyBrandSafety1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyCustomContextualSegmentId;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyCustomContextualSegmentId1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyFraudInvalidTraffic;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyFraudInvalidTraffic1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyStandardDisplayBrandSafety;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyStandardDisplayBrandSafety1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyViewability;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.DoubleVerifyViewability1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceBrandSafety;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceBrandSafety1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceContextualAvoidance;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceContextualAvoidance1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceContextualTargeting;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceContextualTargeting1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceFraudInvalidTraffic;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceFraudInvalidTraffic1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceQualitySync;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceQualitySync1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceViewability;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.IntegralAdScienceViewability1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.NewsGuardBrandGuardMisinformationSafety;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.NewsGuardBrandGuardMisinformationSafety1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.NewsGuardBrandGuardTrustedNewsTargeting;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.NewsGuardBrandGuardTrustedNewsTargeting1;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.PixalateFraudInvalidTraffic;
import io.github.chenyilei2016.amazonads.adsv1.targets.model.PixalateFraudInvalidTraffic1;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

import tools.jackson.core.type.TypeReference;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import tools.jackson.core.JacksonException;
import tools.jackson.databind.DatabindException;
import tools.jackson.databind.SerializationContext;
import tools.jackson.core.JsonGenerator;
import tools.jackson.core.JsonParser;
import tools.jackson.core.JsonToken;
import tools.jackson.databind.DeserializationContext;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.annotation.JsonDeserialize;
import tools.jackson.databind.annotation.JsonSerialize;
import tools.jackson.databind.deser.std.StdDeserializer;
import tools.jackson.databind.ser.std.StdSerializer;
import io.github.chenyilei2016.amazonads.adsv1.client.ApiClient;
import io.github.chenyilei2016.amazonads.adsv1.client.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
@JsonDeserialize(using = ThirdPartyTargetDetails.ThirdPartyTargetDetailsDeserializer.class)
@JsonSerialize(using = ThirdPartyTargetDetails.ThirdPartyTargetDetailsSerializer.class)
public class ThirdPartyTargetDetails extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ThirdPartyTargetDetails.class.getName());

    public static class ThirdPartyTargetDetailsSerializer extends StdSerializer<ThirdPartyTargetDetails> {
        public ThirdPartyTargetDetailsSerializer(Class<ThirdPartyTargetDetails> t) {
            super(t);
        }

        public ThirdPartyTargetDetailsSerializer() {
            this(null);
        }

        @Override
        public void serialize(ThirdPartyTargetDetails value, JsonGenerator jgen, SerializationContext serializationContext) throws JacksonException {
            serializationContext.writeValue(jgen, value.getActualInstance());
        }
    }

    public static class ThirdPartyTargetDetailsDeserializer extends StdDeserializer<ThirdPartyTargetDetails> {
        public ThirdPartyTargetDetailsDeserializer() {
            this(ThirdPartyTargetDetails.class);
        }

        public ThirdPartyTargetDetailsDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public ThirdPartyTargetDetails deserialize(JsonParser jp, DeserializationContext ctxt) throws JacksonException {
            JsonNode tree = ctxt.readTree(jp);
            Object deserialized = null;
            boolean typeCoercion = false; // MapperFeature.ALLOW_COERCION_OF_SCALARS was removed in Jackson 3
            int match = 0;
            JsonToken token = tree.asToken();
            // deserialize DoubleVerifyAuthenticAttention1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DoubleVerifyAuthenticAttention1.class.equals(Integer.class) || DoubleVerifyAuthenticAttention1.class.equals(Long.class) || DoubleVerifyAuthenticAttention1.class.equals(Float.class) || DoubleVerifyAuthenticAttention1.class.equals(Double.class) || DoubleVerifyAuthenticAttention1.class.equals(Boolean.class) || DoubleVerifyAuthenticAttention1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DoubleVerifyAuthenticAttention1.class.equals(Integer.class) || DoubleVerifyAuthenticAttention1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DoubleVerifyAuthenticAttention1.class.equals(Float.class) || DoubleVerifyAuthenticAttention1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DoubleVerifyAuthenticAttention1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DoubleVerifyAuthenticAttention1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, DoubleVerifyAuthenticAttention1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DoubleVerifyAuthenticAttention1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DoubleVerifyAuthenticAttention1'", e);
            }

            // deserialize DoubleVerifyAuthenticBrandSafety1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DoubleVerifyAuthenticBrandSafety1.class.equals(Integer.class) || DoubleVerifyAuthenticBrandSafety1.class.equals(Long.class) || DoubleVerifyAuthenticBrandSafety1.class.equals(Float.class) || DoubleVerifyAuthenticBrandSafety1.class.equals(Double.class) || DoubleVerifyAuthenticBrandSafety1.class.equals(Boolean.class) || DoubleVerifyAuthenticBrandSafety1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DoubleVerifyAuthenticBrandSafety1.class.equals(Integer.class) || DoubleVerifyAuthenticBrandSafety1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DoubleVerifyAuthenticBrandSafety1.class.equals(Float.class) || DoubleVerifyAuthenticBrandSafety1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DoubleVerifyAuthenticBrandSafety1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DoubleVerifyAuthenticBrandSafety1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, DoubleVerifyAuthenticBrandSafety1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DoubleVerifyAuthenticBrandSafety1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DoubleVerifyAuthenticBrandSafety1'", e);
            }

            // deserialize DoubleVerifyBrandSafety1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DoubleVerifyBrandSafety1.class.equals(Integer.class) || DoubleVerifyBrandSafety1.class.equals(Long.class) || DoubleVerifyBrandSafety1.class.equals(Float.class) || DoubleVerifyBrandSafety1.class.equals(Double.class) || DoubleVerifyBrandSafety1.class.equals(Boolean.class) || DoubleVerifyBrandSafety1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DoubleVerifyBrandSafety1.class.equals(Integer.class) || DoubleVerifyBrandSafety1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DoubleVerifyBrandSafety1.class.equals(Float.class) || DoubleVerifyBrandSafety1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DoubleVerifyBrandSafety1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DoubleVerifyBrandSafety1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, DoubleVerifyBrandSafety1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DoubleVerifyBrandSafety1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DoubleVerifyBrandSafety1'", e);
            }

            // deserialize DoubleVerifyCustomContextualSegmentId1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DoubleVerifyCustomContextualSegmentId1.class.equals(Integer.class) || DoubleVerifyCustomContextualSegmentId1.class.equals(Long.class) || DoubleVerifyCustomContextualSegmentId1.class.equals(Float.class) || DoubleVerifyCustomContextualSegmentId1.class.equals(Double.class) || DoubleVerifyCustomContextualSegmentId1.class.equals(Boolean.class) || DoubleVerifyCustomContextualSegmentId1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DoubleVerifyCustomContextualSegmentId1.class.equals(Integer.class) || DoubleVerifyCustomContextualSegmentId1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DoubleVerifyCustomContextualSegmentId1.class.equals(Float.class) || DoubleVerifyCustomContextualSegmentId1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DoubleVerifyCustomContextualSegmentId1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DoubleVerifyCustomContextualSegmentId1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, DoubleVerifyCustomContextualSegmentId1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DoubleVerifyCustomContextualSegmentId1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DoubleVerifyCustomContextualSegmentId1'", e);
            }

            // deserialize DoubleVerifyFraudInvalidTraffic1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DoubleVerifyFraudInvalidTraffic1.class.equals(Integer.class) || DoubleVerifyFraudInvalidTraffic1.class.equals(Long.class) || DoubleVerifyFraudInvalidTraffic1.class.equals(Float.class) || DoubleVerifyFraudInvalidTraffic1.class.equals(Double.class) || DoubleVerifyFraudInvalidTraffic1.class.equals(Boolean.class) || DoubleVerifyFraudInvalidTraffic1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DoubleVerifyFraudInvalidTraffic1.class.equals(Integer.class) || DoubleVerifyFraudInvalidTraffic1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DoubleVerifyFraudInvalidTraffic1.class.equals(Float.class) || DoubleVerifyFraudInvalidTraffic1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DoubleVerifyFraudInvalidTraffic1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DoubleVerifyFraudInvalidTraffic1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, DoubleVerifyFraudInvalidTraffic1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DoubleVerifyFraudInvalidTraffic1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DoubleVerifyFraudInvalidTraffic1'", e);
            }

            // deserialize DoubleVerifyStandardDisplayBrandSafety1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DoubleVerifyStandardDisplayBrandSafety1.class.equals(Integer.class) || DoubleVerifyStandardDisplayBrandSafety1.class.equals(Long.class) || DoubleVerifyStandardDisplayBrandSafety1.class.equals(Float.class) || DoubleVerifyStandardDisplayBrandSafety1.class.equals(Double.class) || DoubleVerifyStandardDisplayBrandSafety1.class.equals(Boolean.class) || DoubleVerifyStandardDisplayBrandSafety1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DoubleVerifyStandardDisplayBrandSafety1.class.equals(Integer.class) || DoubleVerifyStandardDisplayBrandSafety1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DoubleVerifyStandardDisplayBrandSafety1.class.equals(Float.class) || DoubleVerifyStandardDisplayBrandSafety1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DoubleVerifyStandardDisplayBrandSafety1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DoubleVerifyStandardDisplayBrandSafety1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, DoubleVerifyStandardDisplayBrandSafety1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DoubleVerifyStandardDisplayBrandSafety1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DoubleVerifyStandardDisplayBrandSafety1'", e);
            }

            // deserialize DoubleVerifyViewability1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DoubleVerifyViewability1.class.equals(Integer.class) || DoubleVerifyViewability1.class.equals(Long.class) || DoubleVerifyViewability1.class.equals(Float.class) || DoubleVerifyViewability1.class.equals(Double.class) || DoubleVerifyViewability1.class.equals(Boolean.class) || DoubleVerifyViewability1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DoubleVerifyViewability1.class.equals(Integer.class) || DoubleVerifyViewability1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DoubleVerifyViewability1.class.equals(Float.class) || DoubleVerifyViewability1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DoubleVerifyViewability1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DoubleVerifyViewability1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, DoubleVerifyViewability1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DoubleVerifyViewability1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DoubleVerifyViewability1'", e);
            }

            // deserialize IntegralAdScienceBrandSafety1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (IntegralAdScienceBrandSafety1.class.equals(Integer.class) || IntegralAdScienceBrandSafety1.class.equals(Long.class) || IntegralAdScienceBrandSafety1.class.equals(Float.class) || IntegralAdScienceBrandSafety1.class.equals(Double.class) || IntegralAdScienceBrandSafety1.class.equals(Boolean.class) || IntegralAdScienceBrandSafety1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((IntegralAdScienceBrandSafety1.class.equals(Integer.class) || IntegralAdScienceBrandSafety1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((IntegralAdScienceBrandSafety1.class.equals(Float.class) || IntegralAdScienceBrandSafety1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (IntegralAdScienceBrandSafety1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (IntegralAdScienceBrandSafety1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, IntegralAdScienceBrandSafety1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'IntegralAdScienceBrandSafety1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'IntegralAdScienceBrandSafety1'", e);
            }

            // deserialize IntegralAdScienceContextualAvoidance1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (IntegralAdScienceContextualAvoidance1.class.equals(Integer.class) || IntegralAdScienceContextualAvoidance1.class.equals(Long.class) || IntegralAdScienceContextualAvoidance1.class.equals(Float.class) || IntegralAdScienceContextualAvoidance1.class.equals(Double.class) || IntegralAdScienceContextualAvoidance1.class.equals(Boolean.class) || IntegralAdScienceContextualAvoidance1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((IntegralAdScienceContextualAvoidance1.class.equals(Integer.class) || IntegralAdScienceContextualAvoidance1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((IntegralAdScienceContextualAvoidance1.class.equals(Float.class) || IntegralAdScienceContextualAvoidance1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (IntegralAdScienceContextualAvoidance1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (IntegralAdScienceContextualAvoidance1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, IntegralAdScienceContextualAvoidance1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'IntegralAdScienceContextualAvoidance1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'IntegralAdScienceContextualAvoidance1'", e);
            }

            // deserialize IntegralAdScienceContextualTargeting1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (IntegralAdScienceContextualTargeting1.class.equals(Integer.class) || IntegralAdScienceContextualTargeting1.class.equals(Long.class) || IntegralAdScienceContextualTargeting1.class.equals(Float.class) || IntegralAdScienceContextualTargeting1.class.equals(Double.class) || IntegralAdScienceContextualTargeting1.class.equals(Boolean.class) || IntegralAdScienceContextualTargeting1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((IntegralAdScienceContextualTargeting1.class.equals(Integer.class) || IntegralAdScienceContextualTargeting1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((IntegralAdScienceContextualTargeting1.class.equals(Float.class) || IntegralAdScienceContextualTargeting1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (IntegralAdScienceContextualTargeting1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (IntegralAdScienceContextualTargeting1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, IntegralAdScienceContextualTargeting1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'IntegralAdScienceContextualTargeting1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'IntegralAdScienceContextualTargeting1'", e);
            }

            // deserialize IntegralAdScienceFraudInvalidTraffic1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (IntegralAdScienceFraudInvalidTraffic1.class.equals(Integer.class) || IntegralAdScienceFraudInvalidTraffic1.class.equals(Long.class) || IntegralAdScienceFraudInvalidTraffic1.class.equals(Float.class) || IntegralAdScienceFraudInvalidTraffic1.class.equals(Double.class) || IntegralAdScienceFraudInvalidTraffic1.class.equals(Boolean.class) || IntegralAdScienceFraudInvalidTraffic1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((IntegralAdScienceFraudInvalidTraffic1.class.equals(Integer.class) || IntegralAdScienceFraudInvalidTraffic1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((IntegralAdScienceFraudInvalidTraffic1.class.equals(Float.class) || IntegralAdScienceFraudInvalidTraffic1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (IntegralAdScienceFraudInvalidTraffic1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (IntegralAdScienceFraudInvalidTraffic1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, IntegralAdScienceFraudInvalidTraffic1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'IntegralAdScienceFraudInvalidTraffic1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'IntegralAdScienceFraudInvalidTraffic1'", e);
            }

            // deserialize IntegralAdScienceQualitySync1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (IntegralAdScienceQualitySync1.class.equals(Integer.class) || IntegralAdScienceQualitySync1.class.equals(Long.class) || IntegralAdScienceQualitySync1.class.equals(Float.class) || IntegralAdScienceQualitySync1.class.equals(Double.class) || IntegralAdScienceQualitySync1.class.equals(Boolean.class) || IntegralAdScienceQualitySync1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((IntegralAdScienceQualitySync1.class.equals(Integer.class) || IntegralAdScienceQualitySync1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((IntegralAdScienceQualitySync1.class.equals(Float.class) || IntegralAdScienceQualitySync1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (IntegralAdScienceQualitySync1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (IntegralAdScienceQualitySync1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, IntegralAdScienceQualitySync1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'IntegralAdScienceQualitySync1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'IntegralAdScienceQualitySync1'", e);
            }

            // deserialize IntegralAdScienceViewability1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (IntegralAdScienceViewability1.class.equals(Integer.class) || IntegralAdScienceViewability1.class.equals(Long.class) || IntegralAdScienceViewability1.class.equals(Float.class) || IntegralAdScienceViewability1.class.equals(Double.class) || IntegralAdScienceViewability1.class.equals(Boolean.class) || IntegralAdScienceViewability1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((IntegralAdScienceViewability1.class.equals(Integer.class) || IntegralAdScienceViewability1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((IntegralAdScienceViewability1.class.equals(Float.class) || IntegralAdScienceViewability1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (IntegralAdScienceViewability1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (IntegralAdScienceViewability1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, IntegralAdScienceViewability1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'IntegralAdScienceViewability1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'IntegralAdScienceViewability1'", e);
            }

            // deserialize NewsGuardBrandGuardMisinformationSafety1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (NewsGuardBrandGuardMisinformationSafety1.class.equals(Integer.class) || NewsGuardBrandGuardMisinformationSafety1.class.equals(Long.class) || NewsGuardBrandGuardMisinformationSafety1.class.equals(Float.class) || NewsGuardBrandGuardMisinformationSafety1.class.equals(Double.class) || NewsGuardBrandGuardMisinformationSafety1.class.equals(Boolean.class) || NewsGuardBrandGuardMisinformationSafety1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((NewsGuardBrandGuardMisinformationSafety1.class.equals(Integer.class) || NewsGuardBrandGuardMisinformationSafety1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((NewsGuardBrandGuardMisinformationSafety1.class.equals(Float.class) || NewsGuardBrandGuardMisinformationSafety1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (NewsGuardBrandGuardMisinformationSafety1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (NewsGuardBrandGuardMisinformationSafety1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, NewsGuardBrandGuardMisinformationSafety1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'NewsGuardBrandGuardMisinformationSafety1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'NewsGuardBrandGuardMisinformationSafety1'", e);
            }

            // deserialize NewsGuardBrandGuardTrustedNewsTargeting1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(Integer.class) || NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(Long.class) || NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(Float.class) || NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(Double.class) || NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(Boolean.class) || NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(Integer.class) || NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(Float.class) || NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (NewsGuardBrandGuardTrustedNewsTargeting1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, NewsGuardBrandGuardTrustedNewsTargeting1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'NewsGuardBrandGuardTrustedNewsTargeting1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'NewsGuardBrandGuardTrustedNewsTargeting1'", e);
            }

            // deserialize PixalateFraudInvalidTraffic1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PixalateFraudInvalidTraffic1.class.equals(Integer.class) || PixalateFraudInvalidTraffic1.class.equals(Long.class) || PixalateFraudInvalidTraffic1.class.equals(Float.class) || PixalateFraudInvalidTraffic1.class.equals(Double.class) || PixalateFraudInvalidTraffic1.class.equals(Boolean.class) || PixalateFraudInvalidTraffic1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PixalateFraudInvalidTraffic1.class.equals(Integer.class) || PixalateFraudInvalidTraffic1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PixalateFraudInvalidTraffic1.class.equals(Float.class) || PixalateFraudInvalidTraffic1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PixalateFraudInvalidTraffic1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PixalateFraudInvalidTraffic1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = ctxt.readTreeAsValue(tree, PixalateFraudInvalidTraffic1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PixalateFraudInvalidTraffic1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PixalateFraudInvalidTraffic1'", e);
            }

            if (match == 1) {
                ThirdPartyTargetDetails ret = new ThirdPartyTargetDetails();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw DatabindException.from(jp, String.format(java.util.Locale.ROOT, "Failed deserialization for ThirdPartyTargetDetails: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public ThirdPartyTargetDetails getNullValue(DeserializationContext ctxt) {
            throw DatabindException.from(ctxt.getParser(), "ThirdPartyTargetDetails cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public ThirdPartyTargetDetails() {
        super("oneOf", Boolean.FALSE);
    }
  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public ThirdPartyTargetDetails putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

    /**
     * Return true if this ThirdPartyTargetDetails object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        return super.equals(o) && Objects.equals(this.additionalProperties, ((ThirdPartyTargetDetails)o).additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(getActualInstance(), isNullable(), getSchemaType(), additionalProperties);
    }
    public ThirdPartyTargetDetails(DoubleVerifyAuthenticAttention1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(DoubleVerifyAuthenticBrandSafety1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(DoubleVerifyBrandSafety1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(DoubleVerifyCustomContextualSegmentId1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(DoubleVerifyFraudInvalidTraffic1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(DoubleVerifyStandardDisplayBrandSafety1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(DoubleVerifyViewability1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(IntegralAdScienceBrandSafety1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(IntegralAdScienceContextualAvoidance1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(IntegralAdScienceContextualTargeting1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(IntegralAdScienceFraudInvalidTraffic1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(IntegralAdScienceQualitySync1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(IntegralAdScienceViewability1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(NewsGuardBrandGuardMisinformationSafety1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(NewsGuardBrandGuardTrustedNewsTargeting1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ThirdPartyTargetDetails(PixalateFraudInvalidTraffic1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("DoubleVerifyAuthenticAttention1", DoubleVerifyAuthenticAttention1.class);
        schemas.put("DoubleVerifyAuthenticBrandSafety1", DoubleVerifyAuthenticBrandSafety1.class);
        schemas.put("DoubleVerifyBrandSafety1", DoubleVerifyBrandSafety1.class);
        schemas.put("DoubleVerifyCustomContextualSegmentId1", DoubleVerifyCustomContextualSegmentId1.class);
        schemas.put("DoubleVerifyFraudInvalidTraffic1", DoubleVerifyFraudInvalidTraffic1.class);
        schemas.put("DoubleVerifyStandardDisplayBrandSafety1", DoubleVerifyStandardDisplayBrandSafety1.class);
        schemas.put("DoubleVerifyViewability1", DoubleVerifyViewability1.class);
        schemas.put("IntegralAdScienceBrandSafety1", IntegralAdScienceBrandSafety1.class);
        schemas.put("IntegralAdScienceContextualAvoidance1", IntegralAdScienceContextualAvoidance1.class);
        schemas.put("IntegralAdScienceContextualTargeting1", IntegralAdScienceContextualTargeting1.class);
        schemas.put("IntegralAdScienceFraudInvalidTraffic1", IntegralAdScienceFraudInvalidTraffic1.class);
        schemas.put("IntegralAdScienceQualitySync1", IntegralAdScienceQualitySync1.class);
        schemas.put("IntegralAdScienceViewability1", IntegralAdScienceViewability1.class);
        schemas.put("NewsGuardBrandGuardMisinformationSafety1", NewsGuardBrandGuardMisinformationSafety1.class);
        schemas.put("NewsGuardBrandGuardTrustedNewsTargeting1", NewsGuardBrandGuardTrustedNewsTargeting1.class);
        schemas.put("PixalateFraudInvalidTraffic1", PixalateFraudInvalidTraffic1.class);
        JSON.registerDescendants(ThirdPartyTargetDetails.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return ThirdPartyTargetDetails.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * DoubleVerifyAuthenticAttention1, DoubleVerifyAuthenticBrandSafety1, DoubleVerifyBrandSafety1, DoubleVerifyCustomContextualSegmentId1, DoubleVerifyFraudInvalidTraffic1, DoubleVerifyStandardDisplayBrandSafety1, DoubleVerifyViewability1, IntegralAdScienceBrandSafety1, IntegralAdScienceContextualAvoidance1, IntegralAdScienceContextualTargeting1, IntegralAdScienceFraudInvalidTraffic1, IntegralAdScienceQualitySync1, IntegralAdScienceViewability1, NewsGuardBrandGuardMisinformationSafety1, NewsGuardBrandGuardTrustedNewsTargeting1, PixalateFraudInvalidTraffic1
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(DoubleVerifyAuthenticAttention1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DoubleVerifyAuthenticBrandSafety1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DoubleVerifyBrandSafety1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DoubleVerifyCustomContextualSegmentId1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DoubleVerifyFraudInvalidTraffic1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DoubleVerifyStandardDisplayBrandSafety1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DoubleVerifyViewability1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(IntegralAdScienceBrandSafety1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(IntegralAdScienceContextualAvoidance1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(IntegralAdScienceContextualTargeting1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(IntegralAdScienceFraudInvalidTraffic1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(IntegralAdScienceQualitySync1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(IntegralAdScienceViewability1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(NewsGuardBrandGuardMisinformationSafety1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(NewsGuardBrandGuardTrustedNewsTargeting1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PixalateFraudInvalidTraffic1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be DoubleVerifyAuthenticAttention1, DoubleVerifyAuthenticBrandSafety1, DoubleVerifyBrandSafety1, DoubleVerifyCustomContextualSegmentId1, DoubleVerifyFraudInvalidTraffic1, DoubleVerifyStandardDisplayBrandSafety1, DoubleVerifyViewability1, IntegralAdScienceBrandSafety1, IntegralAdScienceContextualAvoidance1, IntegralAdScienceContextualTargeting1, IntegralAdScienceFraudInvalidTraffic1, IntegralAdScienceQualitySync1, IntegralAdScienceViewability1, NewsGuardBrandGuardMisinformationSafety1, NewsGuardBrandGuardTrustedNewsTargeting1, PixalateFraudInvalidTraffic1");
    }

    /**
     * Get the actual instance, which can be the following:
     * DoubleVerifyAuthenticAttention1, DoubleVerifyAuthenticBrandSafety1, DoubleVerifyBrandSafety1, DoubleVerifyCustomContextualSegmentId1, DoubleVerifyFraudInvalidTraffic1, DoubleVerifyStandardDisplayBrandSafety1, DoubleVerifyViewability1, IntegralAdScienceBrandSafety1, IntegralAdScienceContextualAvoidance1, IntegralAdScienceContextualTargeting1, IntegralAdScienceFraudInvalidTraffic1, IntegralAdScienceQualitySync1, IntegralAdScienceViewability1, NewsGuardBrandGuardMisinformationSafety1, NewsGuardBrandGuardTrustedNewsTargeting1, PixalateFraudInvalidTraffic1
     *
     * @return The actual instance (DoubleVerifyAuthenticAttention1, DoubleVerifyAuthenticBrandSafety1, DoubleVerifyBrandSafety1, DoubleVerifyCustomContextualSegmentId1, DoubleVerifyFraudInvalidTraffic1, DoubleVerifyStandardDisplayBrandSafety1, DoubleVerifyViewability1, IntegralAdScienceBrandSafety1, IntegralAdScienceContextualAvoidance1, IntegralAdScienceContextualTargeting1, IntegralAdScienceFraudInvalidTraffic1, IntegralAdScienceQualitySync1, IntegralAdScienceViewability1, NewsGuardBrandGuardMisinformationSafety1, NewsGuardBrandGuardTrustedNewsTargeting1, PixalateFraudInvalidTraffic1)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `DoubleVerifyAuthenticAttention1`. If the actual instance is not `DoubleVerifyAuthenticAttention1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DoubleVerifyAuthenticAttention1`
     * @throws ClassCastException if the instance is not `DoubleVerifyAuthenticAttention1`
     */
    public DoubleVerifyAuthenticAttention1 getDoubleVerifyAuthenticAttention1() throws ClassCastException {
        return (DoubleVerifyAuthenticAttention1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DoubleVerifyAuthenticBrandSafety1`. If the actual instance is not `DoubleVerifyAuthenticBrandSafety1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DoubleVerifyAuthenticBrandSafety1`
     * @throws ClassCastException if the instance is not `DoubleVerifyAuthenticBrandSafety1`
     */
    public DoubleVerifyAuthenticBrandSafety1 getDoubleVerifyAuthenticBrandSafety1() throws ClassCastException {
        return (DoubleVerifyAuthenticBrandSafety1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DoubleVerifyBrandSafety1`. If the actual instance is not `DoubleVerifyBrandSafety1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DoubleVerifyBrandSafety1`
     * @throws ClassCastException if the instance is not `DoubleVerifyBrandSafety1`
     */
    public DoubleVerifyBrandSafety1 getDoubleVerifyBrandSafety1() throws ClassCastException {
        return (DoubleVerifyBrandSafety1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DoubleVerifyCustomContextualSegmentId1`. If the actual instance is not `DoubleVerifyCustomContextualSegmentId1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DoubleVerifyCustomContextualSegmentId1`
     * @throws ClassCastException if the instance is not `DoubleVerifyCustomContextualSegmentId1`
     */
    public DoubleVerifyCustomContextualSegmentId1 getDoubleVerifyCustomContextualSegmentId1() throws ClassCastException {
        return (DoubleVerifyCustomContextualSegmentId1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DoubleVerifyFraudInvalidTraffic1`. If the actual instance is not `DoubleVerifyFraudInvalidTraffic1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DoubleVerifyFraudInvalidTraffic1`
     * @throws ClassCastException if the instance is not `DoubleVerifyFraudInvalidTraffic1`
     */
    public DoubleVerifyFraudInvalidTraffic1 getDoubleVerifyFraudInvalidTraffic1() throws ClassCastException {
        return (DoubleVerifyFraudInvalidTraffic1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DoubleVerifyStandardDisplayBrandSafety1`. If the actual instance is not `DoubleVerifyStandardDisplayBrandSafety1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DoubleVerifyStandardDisplayBrandSafety1`
     * @throws ClassCastException if the instance is not `DoubleVerifyStandardDisplayBrandSafety1`
     */
    public DoubleVerifyStandardDisplayBrandSafety1 getDoubleVerifyStandardDisplayBrandSafety1() throws ClassCastException {
        return (DoubleVerifyStandardDisplayBrandSafety1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DoubleVerifyViewability1`. If the actual instance is not `DoubleVerifyViewability1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DoubleVerifyViewability1`
     * @throws ClassCastException if the instance is not `DoubleVerifyViewability1`
     */
    public DoubleVerifyViewability1 getDoubleVerifyViewability1() throws ClassCastException {
        return (DoubleVerifyViewability1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `IntegralAdScienceBrandSafety1`. If the actual instance is not `IntegralAdScienceBrandSafety1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IntegralAdScienceBrandSafety1`
     * @throws ClassCastException if the instance is not `IntegralAdScienceBrandSafety1`
     */
    public IntegralAdScienceBrandSafety1 getIntegralAdScienceBrandSafety1() throws ClassCastException {
        return (IntegralAdScienceBrandSafety1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `IntegralAdScienceContextualAvoidance1`. If the actual instance is not `IntegralAdScienceContextualAvoidance1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IntegralAdScienceContextualAvoidance1`
     * @throws ClassCastException if the instance is not `IntegralAdScienceContextualAvoidance1`
     */
    public IntegralAdScienceContextualAvoidance1 getIntegralAdScienceContextualAvoidance1() throws ClassCastException {
        return (IntegralAdScienceContextualAvoidance1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `IntegralAdScienceContextualTargeting1`. If the actual instance is not `IntegralAdScienceContextualTargeting1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IntegralAdScienceContextualTargeting1`
     * @throws ClassCastException if the instance is not `IntegralAdScienceContextualTargeting1`
     */
    public IntegralAdScienceContextualTargeting1 getIntegralAdScienceContextualTargeting1() throws ClassCastException {
        return (IntegralAdScienceContextualTargeting1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `IntegralAdScienceFraudInvalidTraffic1`. If the actual instance is not `IntegralAdScienceFraudInvalidTraffic1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IntegralAdScienceFraudInvalidTraffic1`
     * @throws ClassCastException if the instance is not `IntegralAdScienceFraudInvalidTraffic1`
     */
    public IntegralAdScienceFraudInvalidTraffic1 getIntegralAdScienceFraudInvalidTraffic1() throws ClassCastException {
        return (IntegralAdScienceFraudInvalidTraffic1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `IntegralAdScienceQualitySync1`. If the actual instance is not `IntegralAdScienceQualitySync1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IntegralAdScienceQualitySync1`
     * @throws ClassCastException if the instance is not `IntegralAdScienceQualitySync1`
     */
    public IntegralAdScienceQualitySync1 getIntegralAdScienceQualitySync1() throws ClassCastException {
        return (IntegralAdScienceQualitySync1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `IntegralAdScienceViewability1`. If the actual instance is not `IntegralAdScienceViewability1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IntegralAdScienceViewability1`
     * @throws ClassCastException if the instance is not `IntegralAdScienceViewability1`
     */
    public IntegralAdScienceViewability1 getIntegralAdScienceViewability1() throws ClassCastException {
        return (IntegralAdScienceViewability1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `NewsGuardBrandGuardMisinformationSafety1`. If the actual instance is not `NewsGuardBrandGuardMisinformationSafety1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `NewsGuardBrandGuardMisinformationSafety1`
     * @throws ClassCastException if the instance is not `NewsGuardBrandGuardMisinformationSafety1`
     */
    public NewsGuardBrandGuardMisinformationSafety1 getNewsGuardBrandGuardMisinformationSafety1() throws ClassCastException {
        return (NewsGuardBrandGuardMisinformationSafety1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `NewsGuardBrandGuardTrustedNewsTargeting1`. If the actual instance is not `NewsGuardBrandGuardTrustedNewsTargeting1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `NewsGuardBrandGuardTrustedNewsTargeting1`
     * @throws ClassCastException if the instance is not `NewsGuardBrandGuardTrustedNewsTargeting1`
     */
    public NewsGuardBrandGuardTrustedNewsTargeting1 getNewsGuardBrandGuardTrustedNewsTargeting1() throws ClassCastException {
        return (NewsGuardBrandGuardTrustedNewsTargeting1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PixalateFraudInvalidTraffic1`. If the actual instance is not `PixalateFraudInvalidTraffic1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PixalateFraudInvalidTraffic1`
     * @throws ClassCastException if the instance is not `PixalateFraudInvalidTraffic1`
     */
    public PixalateFraudInvalidTraffic1 getPixalateFraudInvalidTraffic1() throws ClassCastException {
        return (PixalateFraudInvalidTraffic1)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof DoubleVerifyAuthenticAttention1) {
        if (getActualInstance() != null) {
          joiner.add(((DoubleVerifyAuthenticAttention1)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DoubleVerifyAuthenticBrandSafety1) {
        if (getActualInstance() != null) {
          joiner.add(((DoubleVerifyAuthenticBrandSafety1)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DoubleVerifyBrandSafety1) {
        if (getActualInstance() != null) {
          joiner.add(((DoubleVerifyBrandSafety1)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DoubleVerifyCustomContextualSegmentId1) {
        if (getActualInstance() != null) {
          joiner.add(((DoubleVerifyCustomContextualSegmentId1)getActualInstance()).toUrlQueryString(prefix + "one_of_3" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DoubleVerifyFraudInvalidTraffic1) {
        if (getActualInstance() != null) {
          joiner.add(((DoubleVerifyFraudInvalidTraffic1)getActualInstance()).toUrlQueryString(prefix + "one_of_4" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DoubleVerifyStandardDisplayBrandSafety1) {
        if (getActualInstance() != null) {
          joiner.add(((DoubleVerifyStandardDisplayBrandSafety1)getActualInstance()).toUrlQueryString(prefix + "one_of_5" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DoubleVerifyViewability1) {
        if (getActualInstance() != null) {
          joiner.add(((DoubleVerifyViewability1)getActualInstance()).toUrlQueryString(prefix + "one_of_6" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof IntegralAdScienceBrandSafety1) {
        if (getActualInstance() != null) {
          joiner.add(((IntegralAdScienceBrandSafety1)getActualInstance()).toUrlQueryString(prefix + "one_of_7" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof IntegralAdScienceContextualAvoidance1) {
        if (getActualInstance() != null) {
          joiner.add(((IntegralAdScienceContextualAvoidance1)getActualInstance()).toUrlQueryString(prefix + "one_of_8" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof IntegralAdScienceContextualTargeting1) {
        if (getActualInstance() != null) {
          joiner.add(((IntegralAdScienceContextualTargeting1)getActualInstance()).toUrlQueryString(prefix + "one_of_9" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof IntegralAdScienceFraudInvalidTraffic1) {
        if (getActualInstance() != null) {
          joiner.add(((IntegralAdScienceFraudInvalidTraffic1)getActualInstance()).toUrlQueryString(prefix + "one_of_10" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof IntegralAdScienceQualitySync1) {
        if (getActualInstance() != null) {
          joiner.add(((IntegralAdScienceQualitySync1)getActualInstance()).toUrlQueryString(prefix + "one_of_11" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof IntegralAdScienceViewability1) {
        if (getActualInstance() != null) {
          joiner.add(((IntegralAdScienceViewability1)getActualInstance()).toUrlQueryString(prefix + "one_of_12" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof NewsGuardBrandGuardMisinformationSafety1) {
        if (getActualInstance() != null) {
          joiner.add(((NewsGuardBrandGuardMisinformationSafety1)getActualInstance()).toUrlQueryString(prefix + "one_of_13" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof NewsGuardBrandGuardTrustedNewsTargeting1) {
        if (getActualInstance() != null) {
          joiner.add(((NewsGuardBrandGuardTrustedNewsTargeting1)getActualInstance()).toUrlQueryString(prefix + "one_of_14" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PixalateFraudInvalidTraffic1) {
        if (getActualInstance() != null) {
          joiner.add(((PixalateFraudInvalidTraffic1)getActualInstance()).toUrlQueryString(prefix + "one_of_15" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

