/*
 * Amazon Ads Campaign Management API
 * Focused Java SDK specification containing only Campaigns operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.campaigns.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.chenyilei2016.amazonads.adsv1.campaigns.model.Campaign;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


import io.github.chenyilei2016.amazonads.client.ApiClient;
/**
 * CampaignSuccessResponse
 */
@JsonPropertyOrder({
  CampaignSuccessResponse.JSON_PROPERTY_CAMPAIGNS,
  CampaignSuccessResponse.JSON_PROPERTY_NEXT_TOKEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CampaignSuccessResponse {
  public static final String JSON_PROPERTY_CAMPAIGNS = "campaigns";
  @jakarta.annotation.Nullable
  private List<@Valid Campaign> campaigns = new ArrayList<>();

  public static final String JSON_PROPERTY_NEXT_TOKEN = "nextToken";
  @jakarta.annotation.Nullable
  private String nextToken;

  public CampaignSuccessResponse() {
  }

  public CampaignSuccessResponse campaigns(@jakarta.annotation.Nullable List<@Valid Campaign> campaigns) {
    this.campaigns = campaigns;
    return this;
  }

  public CampaignSuccessResponse addCampaignsItem(Campaign campaignsItem) {
    if (this.campaigns == null) {
      this.campaigns = new ArrayList<>();
    }
    this.campaigns.add(campaignsItem);
    return this;
  }

  /**
   * Get campaigns
   * @return campaigns
   */
  @jakarta.annotation.Nullable
  @Valid
  @Size(min=0,max=5000)
  @JsonProperty(value = JSON_PROPERTY_CAMPAIGNS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Campaign> getCampaigns() {
    return campaigns;
  }


  @JsonProperty(value = JSON_PROPERTY_CAMPAIGNS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampaigns(@jakarta.annotation.Nullable List<@Valid Campaign> campaigns) {
    this.campaigns = campaigns;
  }


  public CampaignSuccessResponse nextToken(@jakarta.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * Get nextToken
   * @return nextToken
   */
  @jakarta.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_NEXT_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNextToken() {
    return nextToken;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextToken(@jakarta.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }


  /**
   * Return true if this CampaignSuccessResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignSuccessResponse campaignSuccessResponse = (CampaignSuccessResponse) o;
    return Objects.equals(this.campaigns, campaignSuccessResponse.campaigns) &&
        Objects.equals(this.nextToken, campaignSuccessResponse.nextToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaigns, nextToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignSuccessResponse {\n");
    sb.append("    campaigns: ").append(toIndentedString(campaigns)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `campaigns` to the URL query string
    if (getCampaigns() != null) {
      for (int i = 0; i < getCampaigns().size(); i++) {
        if (getCampaigns().get(i) != null) {
          joiner.add(getCampaigns().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scampaigns%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `nextToken` to the URL query string
    if (getNextToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snextToken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNextToken()))));
    }

    return joiner.toString();
  }
}

