/*
 * Amazon Ads Campaign Management API
 * Focused Java SDK specification containing only Campaigns operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.campaigns.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Reason codes for why a tactic type is ineligible **IneligibleAutomatedTargetingTacticReasonCode Enum:**  | IneligibleAutomatedTargetingTacticReasonCode | Description | |------|------| | &#x60;CONVERSION_SELECTIONS_EMPTY&#x60; | Campaign has no product or conversion event associations. | | &#x60;CONVERSION_SELECTIONS_EXCEEDED&#x60; | Campaign is associated with too many products or conversion events. | | &#x60;CONVERSION_SELECTIONS_MINIMUM_NOT_MET&#x60; | Minimum product or conversion event constraints not met. | | &#x60;NOT_ELIGIBLE_ADVERTISER&#x60; | The advertiser is not eligible for this tactic. | | &#x60;NOT_ELIGIBLE_GOAL&#x60; | The current campaign goal is not compatible with this tactic type. | | &#x60;NOT_ELIGIBLE_INVENTORY_TYPE&#x60; | This campaign&#39;s primary inventory types are not supported with this tactic type. | | &#x60;UNSUPPORTED_COUNTRY&#x60; | Selected tactic type is not available for the given country. |
 */
public enum IneligibleAutomatedTargetingTacticReasonCode {

  CONVERSION_SELECTIONS_EMPTY("CONVERSION_SELECTIONS_EMPTY"),

  CONVERSION_SELECTIONS_EXCEEDED("CONVERSION_SELECTIONS_EXCEEDED"),

  CONVERSION_SELECTIONS_MINIMUM_NOT_MET("CONVERSION_SELECTIONS_MINIMUM_NOT_MET"),

  NOT_ELIGIBLE_ADVERTISER("NOT_ELIGIBLE_ADVERTISER"),

  NOT_ELIGIBLE_GOAL("NOT_ELIGIBLE_GOAL"),

  NOT_ELIGIBLE_INVENTORY_TYPE("NOT_ELIGIBLE_INVENTORY_TYPE"),

  UNSUPPORTED_COUNTRY("UNSUPPORTED_COUNTRY"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  IneligibleAutomatedTargetingTacticReasonCode(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static IneligibleAutomatedTargetingTacticReasonCode fromValue(String value) {
    for (IneligibleAutomatedTargetingTacticReasonCode b : IneligibleAutomatedTargetingTacticReasonCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format(java.util.Locale.ROOT, "%s=%s", prefix, this.toString());
  }

}

