/*
 * Amazon Ads Campaign Management API
 * Focused Java SDK specification containing only Campaigns operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.campaigns.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * **Placement Enum:**  | Placement | Description | |------|------| | &#x60;HOME_PAGE&#x60; | Home page. | | &#x60;PRODUCT_PAGE&#x60; | Placements on the product detail page, and all nonsearch placements such as the add-to-cart page. | | &#x60;REST_OF_SEARCH&#x60; | Placements on the middle or the bottom of the first-page search results. Also refers to ads on the second page of search results and beyond. | | &#x60;SITE_AMAZON_BUSINESS&#x60; | Amazon Business site placements. | | &#x60;TOP_OF_SEARCH&#x60; | Placements on the top row of the first-page search results. |
 */
public enum Placement {

  HOME_PAGE("HOME_PAGE"),

  PRODUCT_PAGE("PRODUCT_PAGE"),

  REST_OF_SEARCH("REST_OF_SEARCH"),

  SITE_AMAZON_BUSINESS("SITE_AMAZON_BUSINESS"),

  TOP_OF_SEARCH("TOP_OF_SEARCH"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  Placement(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Placement fromValue(String value) {
    for (Placement b : Placement.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format(java.util.Locale.ROOT, "%s=%s", prefix, this.toString());
  }

}

