/*
 * Amazon Ads Campaign Management API
 * Focused Java SDK specification containing only Campaigns operations.
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.chenyilei2016.amazonads.adsv1.campaigns.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * **PrimaryInventoryType Enum:**  | PrimaryInventoryType | Description | |------|------| | &#x60;AUDIO&#x60; | Audio ads that serve on streaming audio and podcast inventory. | | &#x60;DISPLAY&#x60; | Image ads that serve across Amazon and third-party inventory. | | &#x60;VIDEO_OLV&#x60; | Video ads that serve on online video inventory. | | &#x60;VIDEO_STV&#x60; | Video ads that serve on streaming TV inventory. |
 */
public enum PrimaryInventoryType {

  AUDIO("AUDIO"),

  DISPLAY("DISPLAY"),

  VIDEO_OLV("VIDEO_OLV"),

  VIDEO_STV("VIDEO_STV"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  PrimaryInventoryType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PrimaryInventoryType fromValue(String value) {
    for (PrimaryInventoryType b : PrimaryInventoryType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format(java.util.Locale.ROOT, "%s=%s", prefix, this.toString());
  }

}

